### ISSUE TITLE
Errors calling discord.py in Win10

### ISSUE THREAD

**Issue by Tygah** [Rapptz/discord.py#1434] opened 2018-07-18 18:32 UTC
Whenever I attempt to run the bot it prints these errors.

>C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python.exe "C:/Users/Administrator/Desktop/PyBot Test/bot.py"
>
>Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/PyBot Test/bot.py", line 1, in <module>
    import discord
>
>  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
>
>  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 38, in <module>
>    from .state import ConnectionState
>
>  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 36, in <module>
>    from . import utils, compat
>
>  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\compat.py", line 32
>    create_task = asyncio.async
>                              ^
>SyntaxError: invalid syntax

**Comment by Harmon758** [comment] 2018-07-18 19:47
Duplicate of #1249

**Comment by magicgoose** [comment] 2018-07-19 13:46
> There are already some similar reports.

perhaps it's a good hint to update the README, right now it says

> Python 3.4.2+

**Closed** 2018-08-20 01:30 UTC
Labels: duplicate
