### ISSUE TITLE
Function for user banner color

### ISSUE THREAD

**Issue by pyxiis** [Rapptz/discord.py#7108] opened 2021-06-25 15:51 UTC
### Summary

Have a function for a user banner's default color.

### What is the feature request for?

The core library

### The Problem

There is no function in the library for finding the default color of a user's banner. However, knowing what this color is could open up a few possibilities for bots.

### The Ideal Solution

Ideally, there would be a function for this, something like `discord.User.default_banner` (or perhaps `discord.Member.default_banner` due to per-guild avatars). This would return a `discord.Colour`.

### Additional Context

As far as I know, this color is computed from a user's avatar, but I'm not sure if there are other factors involved. It's also not simply the mean color of an image, because pixels near the edge weigh more than pixels in the center of an avatar in whatever algorithm Discord uses.

**Comment by Rapptz** [comment] 2021-06-25 15:52
Duplicate of https://github.com/Rapptz/discord.py/issues/6969

**Closed by Rapptz** 2021-06-25 15:52 UTC
Labels: feature request
