### ISSUE TITLE
voicechannel.members result in a error ('NoneType' object has no attribute 'id')

### ISSUE THREAD

**Issue by Minlor** [Rapptz/discord.py#6602] opened 2021-03-31 21:47 UTC
### Summary

Due to a new update on discord (stage channels) getting members from a voice channel results in a error.

### Reproduction Steps

I enabled community on my guild and then made a stage channel after that I joined a normal voice channel and when I tried to grab the members of a voice channel I would always get a error

### Minimal Reproducible Code

```python
Aivo.get_channel(channelid).members
```

### Expected Results

Returns all the members in a normal voice channel

### Actual Results

It errors out

Screenshot:
https://cdn.discordapp.com/attachments/821520339242057749/826935480531943424/Discord_tE2MBXrLAD.png

Error:

Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/root/Azure/Azure.py", line 137, in on_voice_state_update
    await if_channel_empty_delete(member, before, after)
  File "/root/Azure/Azure.py", line 118, in if_channel_empty_delete
    check = checkch.members
  File "/usr/local/lib/python3.8/dist-packages/discord/channel.py", line 630, in members
    if state.channel.id == self.id:
AttributeError: 'NoneType' object has no attribute 'id'

### Intents

All intents enabled

### System Information

- Python v3.8.5-final
- discord.py v1.6.0-final
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Asherlam** [comment] 2021-04-01 01:13
Same as mine,

Screenshot:
![image](https://user-images.githubusercontent.com/35485292/113229865-61fdbc80-92ca-11eb-8e64-fd665a647921.png)

**Comment by numbermaniac** [comment] 2021-04-01 01:22
Stage channels are brand new, so discord.py doesn't support them yet. You'll have to wait for the library to add support before they become usable.

**Comment by Minlor** [comment] 2021-04-01 01:23
> Stage channels are brand new, so discord.py doesn't support them yet. You'll have to wait for the library to add support before they become usable.

I know just reporting the issiue.

**Comment by Rapptz** [comment] 2021-04-01 01:24
Yes, this issue will be closed when the issue is fixed. Thanks for reporting it.

**Comment by Minlor** [comment] 2021-04-01 01:25
I just accidentally pressed close the close button since I was replying from my phone.

**Comment by Rapptz** [comment] 2021-04-04 03:03
Fixed by #6608

**Closed by Rapptz** 2021-04-04 03:03 UTC
Labels: bug
