### ISSUE TITLE
__new__() got an unexpected keyword argument 'deny_new'/'allow_new' still affects me

### ISSUE THREAD

**Issue by Cuber112** [Rapptz/discord.py#5764] opened 2020-08-28 22:39 UTC
### Summary

Hello there, for some reason I still receive the error __new__() got an unexpected keyword argument 'deny_new', when scanning through the error, it states at the the the the last line of every single script I have ever made: client.run(TOKEN) is the issue. I did also update and have tried different editors that lead to the same result (Current editor: Visual Studio Code)

### Reproduction Steps

import discord
from discord.ext import commands

client=commands.Bot(command_prefix='?')

TOKEN = 'The token none of you get to use'

@client.event
async def on_ready():
    print('We ready')

client.run(TOKEN)

### Expected Results

Script should run smoothly and show the bot as online.

### Actual Results

  File "c:\Users\MyName\Desktop\Hyper Discord Bot\Hyper Discord Bot\Python things\pleasework.py", line 12, in <module>
    client.run(TOKEN)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 491, in start
    yield from self.connect()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 448, in connect
    yield from self.ws.poll_event()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\gateway.py", line 431, in poll_event
    yield from self.received_message(msg)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\gateway.py", line 390, in received_message
    func(data)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\state.py", line 509, in parse_guild_create
    server = self._get_create_server(data)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\state.py", line 483, in _get_create_server
    server._from_data(data)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\server.py", line 218, in _from_data
    self._sync(guild)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\server.py", line 250, in _sync
    channel = Channel(server=self, **c)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\channel.py", line 89, in __init__
    self._update(**kwargs)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\channel.py", line 116, in _update
    self._permission_overwrites.append(Overwrites(**overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
Task was destroyed but it is pending!

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.4-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

Thanks for help if any found 👍

**Comment by Gobot1234** [comment] 2020-08-28 22:41
You're on the old async branch, which is not maintained anymore, looking at your traceback. You will need to update on the correct environment.

Duplicate of #5109.

**Closed** 2020-08-28 22:45 UTC
Labels: duplicate
