### ISSUE TITLE
Accessing Member.Roles returns old data

### ISSUE THREAD

**Issue by mojoex** [Rapptz/discord.py#4185] opened 2020-06-08 00:41 UTC
### Summary

I have a bot that fetches updates from an external source and based on that data, needs to update users roles. This consists of removing a user role, and replacing it with another.
The functionality for performing this action actually works fine, using member.edit(roles=[roles]).

As I found out, using the below would not work, as you cannot perform updates sumultaneously;

```
await member.remove_roles(oldRole)
await member.add_roles(newRole)
```

So after using member.edit() instead, the updates are applied successfully. However, if the same user is accessed again (it can happen N times while the bot is running), the data in Member.Roles is always returned as the initial value, the first time that Member.Roles is accessed.
This is a problem for logging and comparing.

### Reproduction Steps

Simply call this method multiple times, where newRoles should contain a different member.
Notice that the logging of the oldRolesNames will persist with original values, even after the updates are performed in later iterations.

```
# Iterate through and add the users current roles, removing any we don't want
    for r in user.roles:
        oldRolesNames.append(r.name)
        if r not in roles:
            newRoles.append(r)
            newRolesNames.append(r.name)
    print('# ' + user.name + " old roles: \n", oldRolesNames)
    # Commit the role changes
    try:
        await user.edit(roles=newRoles)
        print('# ' + user.name + ' new roles: \n', newRolesNames)
    except:
        print('Error occurred trying to assign ' + user.name + ' new role..')
```

### Expected Results

Accessing Member.Roles should always return the CURRENT active roles of the member.

### Actual Results

Accessing Member.Roles seems to cache on first access, then return the cached result on subsequent attempts.

### Checklist

- [ x ] I have searched the open issues for duplicates.
- [ x ] I have shown the entire traceback, if possible.
- [ x ] I have removed my token from display, if visible.

### System Information

- Python v3.8.3-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by Rapptz** [comment] 2020-06-08 00:45
Duplicate of https://github.com/Rapptz/discord.py/issues/4087 fixed by https://github.com/Rapptz/discord.py/pull/4157

**Closed by Rapptz** 2020-06-08 00:45 UTC
