### ISSUE TITLE
Allow kwargs when loading a cog

### ISSUE THREAD

**Issue by shahriyardx** [Rapptz/discord.py#8031] opened 2022-05-12 13:23 UTC
### Summary

When we load a cog we can only load it and the bot object gets passed to the setup function. But having additional kwarg can be usefull in some cases

### What is the feature request for?

The core library

### The Problem

Loading a cog currently looks like this

```py
bot.load_extension('cog', package)
```

And the setup function gets the bot object only, no way we can pass something else unless we are manually adding the using `bot.add_cog()`

So the setup looks like this
```py
def setup(bot):
    bot.add_cog(MyCog(bot))
```

And in the cog we can accept the passed bot variable

```py
class MyCog(commands.Cog):
    def __init__(self, bot):
        pass
```

What if we was able to have kwargs in the setup like

```py
# Loading
bot.load_extension('cog', package, something='Interesting')

# Setup
def setup(bot, **kwargs):
    # pass something to the cog
    bot.add_cog(MyCog(bot, **kwargs)

# In Cog
class MyCog(commands.Cog):
    def __init__(self, bot, **kwargs):
        something = kwargs.get('seomthing')
```

### The Ideal Solution

Allow passing kwargs when loading an extension

### The Current Solution

Setting up bot level variable (botvar) or load the cog by importing it

**Comment by Rapptz** [comment] 2022-05-12 13:29
Duplicate of https://github.com/Rapptz/discord.py/issues/7394

**Closed by Rapptz** 2022-05-12 13:29 UTC
Labels: feature request
