### ISSUE TITLE
Bot crashes right after starting...

### ISSUE THREAD

**Issue by Cybergenik** [Rapptz/discord.py#5156] opened 2020-07-23 22:13 UTC
### Summary
Running simple bot in Heroku, it starts up and crashes on the `client.run(TOKEN)` line.
**Yes I checked that I had the correct token**

### Reproduction Steps

It was literally working yesterday
My repo for the bot is public: you can look at the whole thing(main issue is in runemaster.py): https://github.com/Cybergenik/RuneMaster

### Expected Results

To just run

### Actual Results

```
2020-07-23T22:02:50.392970+00:00 app[worker.1]: Traceback (most recent call last):
2020-07-23T22:02:50.392989+00:00 app[worker.1]:   File "runemaster.py", line 291, in <module>
2020-07-23T22:02:50.393371+00:00 app[worker.1]:     client.run(TOKEN)
2020-07-23T22:02:50.393376+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 640, in run
2020-07-23T22:02:50.393702+00:00 app[worker.1]:     return future.result()
2020-07-23T22:02:50.393706+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 621, in runner
2020-07-23T22:02:50.394015+00:00 app[worker.1]:     await self.start(*args, **kwargs)
2020-07-23T22:02:50.394019+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 585, in start
2020-07-23T22:02:50.394321+00:00 app[worker.1]:     await self.connect(reconnect=reconnect)
2020-07-23T22:02:50.394325+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 499, in connect
2020-07-23T22:02:50.394608+00:00 app[worker.1]:     await self._connect()
2020-07-23T22:02:50.394612+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 463, in _connect
2020-07-23T22:02:50.394909+00:00 app[worker.1]:     await self.ws.poll_event()
2020-07-23T22:02:50.394913+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/gateway.py", line 471, in poll_event
2020-07-23T22:02:50.395194+00:00 app[worker.1]:     await self.received_message(msg)
2020-07-23T22:02:50.395199+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/gateway.py", line 425, in received_message
2020-07-23T22:02:50.395435+00:00 app[worker.1]:     func(data)
2020-07-23T22:02:50.395440+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/state.py", line 750, in parse_guild_create
2020-07-23T22:02:50.395873+00:00 app[worker.1]:     guild = self._get_create_guild(data)
2020-07-23T22:02:50.395878+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/state.py", line 725, in _get_create_guild
2020-07-23T22:02:50.396179+00:00 app[worker.1]:     guild._from_data(data)
2020-07-23T22:02:50.396180+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/guild.py", line 297, in _from_data
2020-07-23T22:02:50.396490+00:00 app[worker.1]:     self._sync(guild)
2020-07-23T22:02:50.396514+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/guild.py", line 326, in _sync
2020-07-23T22:02:50.396827+00:00 app[worker.1]:     self._add_channel(VoiceChannel(guild=self, data=c, state=self._state))
2020-07-23T22:02:50.396843+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/channel.py", line 553, in __init__
2020-07-23T22:02:50.397078+00:00 app[worker.1]:     self._update(guild, data)
2020-07-23T22:02:50.397098+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/channel.py", line 584, in _update
2020-07-23T22:02:50.397324+00:00 app[worker.1]:     self._fill_overwrites(data)
2020-07-23T22:02:50.397340+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/abc.py", line 294, in _fill_overwrites
2020-07-23T22:02:50.397509+00:00 app[worker.1]:     self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
2020-07-23T22:02:50.397530+00:00 app[worker.1]: TypeError: __new__() got an unexpected keyword argument 'deny_new'
2020-07-23T22:02:50.517034+00:00 heroku[worker.1]: Process exited with status 1
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.1-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.4.0-1074-aws #78-Ubuntu SMP Mon Jun 15 03:53:20 UTC 2020

**Comment by gogurtenjoyer** [comment] 2020-07-23 22:15
This was fixed in discord.py 1.3.4 - update, and you should be all set.

**Comment by Harmon758** [comment] 2020-07-23 22:15
Duplicate of #5109

**Closed** 2020-07-23 22:15 UTC
Labels: duplicate
