### ISSUE TITLE
Having issues with `client.run(token)`

### ISSUE THREAD

**Issue by Brown-1e** [Rapptz/discord.py#5815] opened 2020-09-12 08:47 UTC
```
# SwearBot made as a bit of a joke....

swears=0

import discord
import json
import os

os.chdir(r'C:\Users\Travis\Documents\_SwearBot')

token="token"

client = discord.Client()

@client.event
async def on_message(message):
    if "fuck" in message.content.lower():
        print(f"In Channel {message.channel},{message.author} wrote: {message.content}")
        swears=swears+1
        await message.channel.send('Swear added to the jar, total is now £',swears)

#DISCORD BOT ACTIVITY
@client.event
async def on_ready():
    activity = discord.Game(name="Counting up your sins...", type=3)
    await client.change_presence(status=discord.Status.online, activity=activity)
    print('------')
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

client.run(token)
```

I get an issue with the `client.run(token)` line, not exactly sure why. Token is correct but not quite sure whats going on. This is the error I get;

[Traceback (most recent call last):
  File "C:\Users\Travis\Documents\_SwearBot\swearbot.py", line 31, in <module>
    client.run(token)
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 640, in run
    return future.result()
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 499, in connect
    await self._connect()
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 463, in _connect
    await self.ws.poll_event()
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\gateway.py", line 471, in poll_event
    await self.received_message(msg)
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\gateway.py", line 425, in received_message
    func(data)
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\state.py", line 750, in parse_guild_create
    guild = self._get_create_guild(data)
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\state.py", line 725, in _get_create_guild
    guild._from_data(data)
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\guild.py", line 297, in _from_data
    self._sync(guild)
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\guild.py", line 324, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\channel.py", line 107, in __init__
    self._update(guild, data)
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "C:\Users\Travis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\abc.py", line 294, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'](url)
>

**Comment by Rapptz** [comment] 2020-09-12 08:48
Duplicate of https://github.com/Rapptz/discord.py/issues/5109

**Closed by Rapptz** 2020-09-12 08:48 UTC
