### ISSUE TITLE
member.top_role seems unreliable

### ISSUE THREAD

**Issue by MattIPv4** [Rapptz/discord.py#1577] opened 2018-09-11 19:11 UTC
In some situations (unfortunately I don't have definite reproduction conditions), top_role appears to ignore the bot's own managed role from where it was invited when calculating top role leading to it returning the incorrect role.

I recently had this on one of my own bots and have had to deploy a custom top_role bodge fix which resolves this issue.

#### D.py member.top_role
![oof](https://i.dabbitpri.me/dih2ofx35q.png)

#### Using sorted to get top role
![oof2](https://i.dabbitpri.me/2el58o3067.png)

**Comment by Harmon758** [comment] 2018-09-11 19:18
Possibly duplicate of #1518

**Comment by Werseter** [comment] 2018-09-12 02:13
#1313 - already acknowledged, presumably on TODO

**Comment by Rapptz** [comment] 2018-09-25 11:06
This should have been fixed.

**Closed by Rapptz** 2018-09-25 11:06 UTC
Labels: bug
