### ISSUE TITLE
Same series of errors whenever I try to import discord 

### ISSUE THREAD

**Issue by boyyprince** [Rapptz/discord.py#1471] opened 2018-07-31 05:09 UTC
Hi! Any time I try to import discord, I get this series of errors. 

<img width="568" alt="screen shot 2018-07-30 at 10 06 46 pm" src="https://user-images.githubusercontent.com/41937354/43438841-1d6dd8ec-9445-11e8-99e9-d3c09c1f13ae.png">

It doesn't matter what's in the file -- if import discord is in there, I get these errors. Does anyone know what I'm doing wrong? I checked my terminal and it says the requirements for import discord have been met, so I really don't know what to do and it's driving me crazy!

**Comment by Harmon758** [comment] 2018-07-31 05:10
Duplicate of #1249

**Closed** 2018-08-20 01:33 UTC
Labels: duplicate
