### ISSUE TITLE
__new__() got an unexpected keyword argument 'allow_new'

### ISSUE THREAD

**Issue by adenirlc** [Rapptz/discord.py#5117] opened 2020-07-10 19:05 UTC
### Summary

When I try to create a new text channel in a certain category, the console informs me of an error: "__new __ () got an unexpected keyword argument 'allow_new'".

### Reproduction Steps

channel_name = f'whitelist-{ctx.author.name}'
            overwrites = {
                ctx.guild.default_role: discord.PermissionOverwrite(read_messages=False),
                ctx.guild.me: discord.PermissionOverwrite(read_messages=True, send_messages=True),
                ctx.author: discord.PermissionOverwrite(read_messages=True, send_messages=True)
            }
            category = discord.utils.get(ctx.guild.categories, id=726608116271022141)
            channel = await ctx.guild.create_text_channel(channel_name, category=category,
                                                overwrites=overwrites, nsfw=False, position=1, reason="WhiteList IceRP")
            print(channel.id)
### Expected Results

Expected Result: <b>TheChannelID</b>
### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.1-final
- discord.py v1.3.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.19041

**Comment by Gobot1234** [comment] 2020-07-10 19:07
Update to v1.3.4.

**Comment by Harmon758** [comment] 2020-07-10 19:31
Duplicate of #5109 

For code block usage, see https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.

**Closed** 2020-07-10 19:31 UTC
