### ISSUE TITLE
CustomActivity

### ISSUE THREAD

**Issue by jtrenaud1s** [Rapptz/discord.py#2550] opened 2020-02-03 12:04 UTC
When setting the client's (bot) presence to an Activity with type custom and a name, the presence is blank on the discord server, even though it looks to me like discord's added the api, and it's written in discord.py. Listening works fine, changing discord.ActivityType.listening to custom just makes the existing presence text disappear on discord.

**Comment by numbermaniac** [comment] 2020-02-03 12:17
I don't believe custom statuses for bots are supported yet.

> * Note that as of now, bots cannot send custom activities yet.

https://discordpy.readthedocs.io/en/latest/whats_new.html#v1-3-0

**Comment by Harmon758** [comment] 2020-02-03 12:18
Duplicate of #2400

**Closed** 2020-02-03 12:18 UTC
Labels: discord bug, duplicate
