### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ack'

### ISSUE THREAD

**Issue by stayingqold** [Rapptz/discord.py#5911] opened 2020-10-08 20:36 UTC
## Summary

Looks like an error occurs that gets ignored, then the bot disconnects and reconnects a bunch of times. Apologies in advance for the long logs.

My bot runs fine for a few days or hours, then this happens and it goes offline. I run my bot across 3 physical servers and only one is having this problem.

You can see my source code here (I use the distributed branch): https://github.com/stayingqold/Poll-Bot/tree/distributed

## Reproduction Steps

I haven't been able to reproduce this on my test bot. 

## Expected Results

Continue running as usual.

## Actual Results

```
discord.ext.commands.errors.CommandNotFound: Command "poll" is not found
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Poll-Bot/cogs/poll.py", line 71, in on_message
    await message.add_reaction('👍')
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/message.py", line 953, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Logged in as
Poll Bot
298673420181438465
--------
Logged in as
Poll Bot
...
--------
Logged in as
Poll Bot
298673420181438465
Traceback (most recent call last):
  File "launcher.py", line 12, in <module>
    bot.run()
  File "/home/ubuntu/Poll-Bot/bot.py", line 50, in run
    super().run(self.config["discord_token"], reconnect=True)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 678, in run
    return future.result()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 658, in runner
    await self.start(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 622, in start
    await self.connect(reconnect=reconnect)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/shard.py", line 414, in connect
    raise item.error
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/shard.py", line 140, in worker
    await self.ws.poll_event()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/gateway.py", line 504, in poll_event
 File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/gateway.py", line 401, in received_message
    self._keep_alive.ack()
AttributeError: 'NoneType' object has no attribute 'ack'
Task exception was never retrieved
future: <Task finished coro=<BackgroundTasks.update_server_count() done, defined at /home/ubuntu/Poll-Bot/cogs/BackgroundTasks.py:13> exception=gaierror(-3, 'Temporary failure in name resolution')>
Traceback (most recent call last):
  File "/home/ubuntu/Poll-Bot/cogs/BackgroundTasks.py", line 16, in update_server_count
    await self.db.post_server_stats(self.bot.config["physical_server_name"], len(self.bot.guilds))
  File "/home/ubuntu/Poll-Bot/cogs/Database.py", line 38, in post_server_stats
    self.conn = await asyncpg.connect(user = self.user, password = self.password, database = self.database, host = self.host)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/asyncpg/connection.py", line 1727, in connect
    max_cacheable_statement_size=max_cacheable_statement_size)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 674, in _connect
    raise last_error
File "/home/ubuntu/.local/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 666, in _connect
    connection_class=connection_class)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 633, in _connect_addr 
    connector, timeout=timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 750, in create_connection
    infos = f1.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run 
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
Unclosed client session 
client_session: <aiohttp.client.ClientSession object at 0x7f28c90aa4e0>
```

## Intents

none

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.6.9-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Linux 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020

Let me know if you need any more information, or if there is any way I can help fix this.

**Comment by Rapptz** [comment] 2020-10-08 23:19
Duplicate of #5800. This was already fixed. Update your library to either 1.4.2 or 1.5.0.

**Closed** 2020-10-08 23:20 UTC
Labels: duplicate
