### ISSUE TITLE
Self-bot can only see its own messages

### ISSUE THREAD

**Issue by dolfies** [Rapptz/discord.py#6839] opened 2021-05-02 21:44 UTC
### Summary

When using a self-bot, message.content and message.embeds are both empty. This does not occur on a real bot. I can still view information such as message.author.id, etc. 

### Reproduction Steps

1. Run a simple bot with a user token (NOT a bot token).
2. Add the on_message event.
3. Add a command or some sort of response to a message, or just print(message.content)

### Minimal Reproducible Code

```python
import discord

class MyClient(discord.Client):
    async def on_ready(self):
        print('Logged on as', self.user)

    async def on_message(self, message):
        if message.content == 'ping':
            await message.channel.send('pong')

client = MyClient()
client.run('token', bot=False)
```

### Expected Results

It responds to the command / prints the contents of the message.

### Actual Results

It doesnt respond to anyone but itself / `message.content` is blank.
![Screenshot 2021-05-02 17 34 28](https://user-images.githubusercontent.com/47677887/116828610-bf0cbc80-ab6d-11eb-82ea-c629124e9e3c.png)

### Intents

None, I don't think they work for self-bots either.

### System Information

- Python v3.8.9-final
- discord.py v1.7.1-final
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-1042-gcp \#45-Ubuntu SMP Tue Apr 13 01:44:53 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I know self-bots are against ToS, and I accept the risks related to that.

**Comment by lgaan** [comment] 2021-05-02 21:46
Duplicate of #6820, and is a wontfix.

**Comment by dolfies** [comment] 2021-05-02 22:04
Does anyone at least know where I should start if I were to try and fix it myself?

**Comment by apple502j** [comment] 2021-05-02 22:05
Easy fix: don't use selfbots
Or: run `pip3 install -U git+https://github.com/Rapptz/discord.py`

**Closed** 2021-05-02 22:06 UTC
Labels: unconfirmed bug

**Comment by dolfies** [comment] 2021-05-03 00:29
> Easy fix: don't use selfbots
> Or: run `pip3 install -U git+https://github.com/Rapptz/discord.py`

Does that version even support self-bots? The bot parameter on start(), run(), or login() doesn't work. Checking the code it doesn't even exist.

**Comment by Tari-dev** [comment] 2021-05-03 00:33
selfbot methods are depreciated from 1.7.
You won't find help/support for selfbotting as it's against ToS of discord

**Comment by Vexs** [comment] 2021-05-03 00:35
It appears discord started doing this to anyone who connects as a user with intents- if you remove that, you'll get these.

**Comment by dolfies** [comment] 2021-05-03 02:54
> It appears discord started doing this to anyone who connects as a user with intents- if you remove that, you'll get these.

![image](https://user-images.githubusercontent.com/47677887/116837605-24c26e00-ab99-11eb-9845-ef30652d515d.png)

Trying the discord.py example code with `discord.Intents.none()` did not seem to work. With no intents it doesn't even acknowledge a message has been sent, while without overriding any intent settings it does recognize a message, but content is blank.

**Comment by Rapptz** [comment] 2021-05-03 02:55
User-bots and self-bots have been deprecated in the library since v1.7 and will no longer receive support. As of v2.0, they have been completely removed from the library as well. Consider using a real bot instead.
