### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by LucasColas** [Rapptz/discord.py#4160] opened 2020-05-30 21:09 UTC
### Summary

I got an error when I wanted to run my code. I'm working on this code since a few days and it was working.

### Reproduction Steps

I tried to run my code but I got an error : 

> Event loop is closed

My code : 
`client= discord.Client()
@client.event
async def on_message(message):
    if message.author == client.user:
        return
    id = client.get_guild(325925436804825111)` 

    if message.content.find("!Test") != -1 :
        await message.channel.send("Operational !")

    if message.content.find("!Hello") != -1 :
        await message.channel.send("Hi")

    if message.content.find("What's up !") != -1 :
        await message.channel.send("Hey!")

    if message.content == "!users": #Number of users
        await message.channel.send(f"users : {id.member_count}.")

    if message.content == "Super !":
        await message.add_reaction('\U0001F44D')

    if message.content == "GG":
        await message.channel.send('👍')

  
`client.run(token)`

### Expected Results

It expected to run my bot

### Actual Results

I got an error : 
 Event loop is closed

### Checklist

- [x ] I have searched the open issues for duplicates.
- [ x] I have shown the entire traceback, if possible.
- [ x] I have removed my token from display, if visible.

### System Information

When I try to run `python -m discord -v` I get 

> SyntaxError: invalid syntax

**Comment by Harmon758** [comment] 2020-11-06 04:39
There are numerous issues that can cause this, and it's not going to be possible to pinpoint one without a full traceback.
However, make sure you're using the right token and that you're not [blocking](https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean).

As for your system information, that [invokes Python on the command line](https://docs.python.org/3/using/cmdline.html).
It is not Python syntax to be used within the interpreter itself.

Since this is almost certainly not an issue with discord.py itself, doesn't provide any information as to the cause of the issue, and is months old now, I'm going to close this issue for now. Feel free to join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links, to provide your traceback for further help. 

For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.

For task list usage, see https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-task-lists.

**Closed** 2020-11-06 04:40 UTC
