### ISSUE TITLE
Player Error: AttributeError: 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by alvinzzzzz** [Rapptz/discord.py#6212] opened 2020-12-26 03:13 UTC
## Summary

Every time when I try to loop a song it rasies this error.

## Reproduction Steps
Do this: loop[str(ctx.guild.id)] = [ctx.voice_client.source]
Then try to play it:

player = loop[str(ctx.guild.id)][0]
music = ctx.voice_client.play(player)

## Expected Results
I expected it to loop the song no error should raised.

## Actual Results

```
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/player.py", line 598, in run
    self._do_run()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/player.py", line 585, in _do_run
    data = self.source.read()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/player.py", line 538, in read
    ret = self.original.read()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/player.py", line 223, in read
    ret = self._stdout.read(OpusEncoder.FRAME_SIZE)
AttributeError: 'NoneType' object has no attribute 'read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/player.py", line 611, in _call_after
    self.after(error)
  File "main.py", line 393, in play_next_song
    raise VoiceError(str(error))
VoiceError: 'NoneType' object has no attribute 'read'
```

## Intents
I don't really understand what it mean but I am using discord.ext commands

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information
- Python v3.8.7-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Linux 5.4.0-1019-gcp #19-Ubuntu SMP Tue Jun 23 15:46:40 UTC 2020

**Comment by Rapptz** [comment] 2020-12-26 03:15
Duplicate of #4003

**Closed** 2020-12-26 03:15 UTC
Labels: duplicate
