### ISSUE TITLE
Reactions crash bot. Can't update in heroku.

### ISSUE THREAD

**Issue by notclassix** [Rapptz/discord.py#2499] opened 2020-01-07 06:34 UTC
### Summary

My bot crashes when an emoji is added or removed. I would update to the latest development version but every time I do, it says it updates but it doesn't.

### Reproduction Steps

Added / removed a role from a message. I tried python3 -m pip install -U discord.py in the heroku console. I also tried pip install -U discord.py --force-reinstall.

### Expected Results

The opposite of what is happening. For heroku to update discord.py. It won't even update pip.

### Actual Results

2020-01-07T06:18:13.207009+00:00 app[worker.1]: Task exception was never retrieved
2020-01-07T06:18:13.207044+00:00 app[worker.1]: future: <Task finished coro=<Client.run.<locals>.runner() done, defined at /app/.heroku/python/lib/python3.6/site-packages/discord/client.py:545> exception=KeyError('animated',)>
2020-01-07T06:18:13.207047+00:00 app[worker.1]: Traceback (most recent call last):
2020-01-07T06:18:13.207049+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 547, in runner
2020-01-07T06:18:13.207052+00:00 app[worker.1]:     await self.start(*args, **kwargs)
2020-01-07T06:18:13.207054+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 511, in start
2020-01-07T06:18:13.207056+00:00 app[worker.1]:     await self.connect(reconnect=reconnect)
2020-01-07T06:18:13.207059+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 433, in connect
2020-01-07T06:18:13.207061+00:00 app[worker.1]:     await self._connect()
2020-01-07T06:18:13.207063+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 397, in _connect
2020-01-07T06:18:13.207065+00:00 app[worker.1]:     await self.ws.poll_event()
2020-01-07T06:18:13.207067+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/gateway.py", line 470, in poll_event
2020-01-07T06:18:13.207069+00:00 app[worker.1]:     await self.received_message(msg)
2020-01-07T06:18:13.207071+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/gateway.py", line 424, in received_message
2020-01-07T06:18:13.207073+00:00 app[worker.1]:     func(data)
2020-01-07T06:18:13.207075+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/state.py", line 410, in parse_message_reaction_add
2020-01-07T06:18:13.207077+00:00 app[worker.1]:     emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
2020-01-07T06:18:13.207088+00:00 app[worker.1]: KeyError: 'animated'
2020-01-07T06:18:13.330585+00:00 heroku[worker.1]: State changed from up to crashed
2020-01-07T06:18:13.334962+00:00 heroku[worker.1]: State changed from crashed to starting
2020-01-07T06:18:13.311504+00:00 heroku[worker.1]: Process exited with status 0

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

Python v3.6.8-final
- discord.py v1.1.1-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.4.0-1057-aws #61+hf245703v220191104b1-Ubuntu SMP Mon Nov 4 15:32:25 UTC 2019

**Comment by Harmon758** [comment] 2020-01-07 06:55
This is fixed in the latest version of discord.py, as it's a duplicate of the pinned issue, #2422.

I would recommend not using Heroku to host your bot, as that's not a type of purpose the platform was designed for and doing so comes with a lot of disadvantages.

However, GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Heroku. For that, you should contact Heroku's support or ask somewhere else (such as a Heroku community) where support for Heroku is provided and would be on-topic. For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Closed** 2020-01-07 06:56 UTC
Labels: duplicate, off-topic
