### ISSUE TITLE
Support for Discord API v9

### ISSUE THREAD

**Issue by phinnaeus** [Rapptz/discord.py#7356] opened 2021-08-10 00:01 UTC
### Summary

Discords new API v9 supports threads

### What is the feature request for?

The core library

### The Problem

Basically the current library version does not support any messages sent in threads. For more info on this update see https://discord.com/developers/docs/topics/threads

### The Ideal Solution

I'm really not sure how big of a change this is, from what I can tell the new API is almost completely backwards compatible.

### The Current Solution

I have a fork of the library using the v9 API and it seems to work in my limited testing. See: https://github.com/phinnaeus/discord.py/commit/ca790214a3050f593d6795753b221ca8d8622997

**Comment by mrvillage** [comment] 2021-08-10 00:07
This has been available for quite a while as part of the alpha for discord.py 2.0.0.

**Comment by Phxntxm** [comment] 2021-08-10 00:16
When you submit issues for the library you need to remember that the master branch exists to, and check against *that* version what's available. V9 and threads are already supported in the library and'll be out when 2.0 is released, that's how versions are normally handled... they're worked on in a branch on github then released later

**Comment by phinnaeus** [comment] 2021-08-10 00:28
Cheers

**Comment by phinnaeus** [comment] 2021-08-10 00:32
Wait what? I obviously checked the master branch, that still only has v8: https://github.com/Rapptz/discord.py/blob/master/discord/http.py#L112

Same with the `feature/threads` branch: https://github.com/Rapptz/discord.py/blob/feature/threads/discord/http.py#L70

Can you help me understand what I'm missing, perhaps with less snark?

**Comment by Rapptz** [comment] 2021-08-10 00:33
HTTP version is different from the Gateway version.

Duplicate of #6817 #7060 #7148 #7300

**Closed by Rapptz** 2021-08-10 00:33 UTC
Labels: feature request
