### ISSUE TITLE
Issue Running Discord.py

### ISSUE THREAD

**Issue by MineClipper** [Rapptz/discord.py#1408] opened 2018-07-10 20:20 UTC
![capture](https://user-images.githubusercontent.com/25290723/42535286-fa5892ae-845c-11e8-910d-ed948dcadb6f.PNG)
I can't figure out what my problem is or how to fix it. Also, I'm a beginner when it comes to programming so please make the responses easy to understand. Thanks!

EDIT: I'm using python 3.7.0

**Comment by mrc0mmand** [comment] 2018-07-10 20:24
Duplicate of #1249, #1393, and #1396.

**Comment by MineClipper** [comment] 2018-07-10 20:32
So switching to python 3.6.4 should solve the issue?

**Comment by mrc0mmand** [comment] 2018-07-10 20:32
Exactly.

**Comment by ItWasAllIntended** [comment] 2018-07-10 20:34
Though it would always be advised to use 3.6.6 as this is the latest working version

**Comment by FranciscoRamon** [comment] 2018-07-10 20:48
is this error in the package or its dependencies?

**Comment by ItWasAllIntended** [comment] 2018-07-10 20:49
As the file path shows, it's a discord.py issue

**Comment by Gorialis** [comment] 2018-07-10 20:58
This bug [**is** fixed on async](https://github.com/Rapptz/discord.py/blob/async/discord/compat.py#L32) but the latest changes on the branch are not available on PyPI. However, direct dependencies *do* have similar issues so even if you were to install direct from the branch (`pip install -U git+https://github.com/Rapptz/discord.py@async#egg=discord.py[voice]`) you would run into exactly the same issue but elsewhere.

**Comment by MineClipper** [comment] 2018-07-11 01:49
Thank you for getting back to me so quickly. Requesting close.

On Jul 10, 2018 4:32 PM, "Frantisek Sumsal" <notifications@github.com>
wrote:

Exactly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Rapptz/discord.py/issues/1408#issuecomment-403956402>,
or mute the thread

**Comment by iCrazyBlaze** [comment] 2018-07-30 13:16
When I use the above command to install directly from the async branch, I get this error:
https://gyazo.com/4e9392b61a845e5a2eda8996c8ca545b

**Comment by ItWasAllIntended** [comment] 2018-07-30 13:18
The error is due to the pinned version of PyNaCl not being compatible with 3.7. Either use 3.6.6 or don't instal with voice

**Comment by Harmon758** [comment] 2018-07-30 13:33
An alternative would be manually installing PyNaCl 1.2.1, the most recent version, which supports 3.7.
However, compatibility with discord.py, especially on the async branch, is not ensured.
See #1444.

**Comment by iCrazyBlaze** [comment] 2018-07-30 13:38
OK, thanks for the reply!

**Closed** 2018-08-20 01:32 UTC
Labels: duplicate
