### ISSUE TITLE
Calling client.close() does not make the bot go offline

### ISSUE THREAD

**Issue by overfl0** [Rapptz/discord.py#6719] opened 2021-04-14 01:24 UTC
### Summary

Calling client.close() stops the bot but does not make the it go offline

### Reproduction Steps

1. Run the example
2. Wait for the on_ready message
3. Press Ctrl+C

### Minimal Reproducible Code

```python
import discord

TOKEN = '...'
client = discord.Client()


@client.event
async def on_ready():
    print('We have logged in as {0.user}'.format(client))


try:
    client.loop.run_until_complete(client.start(TOKEN))
except KeyboardInterrupt:
    print('closing...')
    client.loop.run_until_complete(client.close())
finally:
    client.loop.close()
```

### Expected Results

The bot shown in the OFFLINE list

### Actual Results

The bot is still shown in the ONLINE list until Discord realizes that the connection has timed out

### Intents

Not passing any

### System Information

The last working version is v1.3.4
It doesn't work in v1.4.1 anymore (v1.4.0 had a bug that prevented stopping the bot completely so it is impossible to verify)

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

**Comment by SebbyLaw** [comment] 2021-04-14 01:26
Duplicate of #6134

**Closed** 2021-04-14 01:27 UTC
Labels: unconfirmed bug

**Comment by overfl0** [comment] 2021-04-14 02:02
> v1.3.x used a different websocket library, so, we're really just back to the same square

Could I get some pointers as to what exactly is supposed to happen when we're issuing .close() that actually makes the bot go offline?

Maybe I could take a look at that different library and figure out what it does that doesn't result in the bot going offline (as opposed to the old one, which resulted in the correct behavior of the bot correctly disconnecting)?

I'm willing to spend some time on this, myself, but I just need to know what to look for.

**Comment by Rapptz** [comment] 2021-04-14 02:07
Calling `close` already calls the underlying websocket library's `close` with a 1000 close code. Now, whether that request is being sent or not I don't know -- but I already do what is necessary to terminate the connection. If you want to tackle this problem you're free to check `aiohttp`'s websocket client implementation.

That aside, v1.3 and v1.4 are months old and EOL and are not supported so any issue involving those issues are inactionable.

**Comment by Coryf88** [comment] 2021-06-09 18:31
I'm using v1.7.2 and also have this issue.

Bot goes offline immediately if the closing of [aiohttp.client.ClientSession](https://github.com/Rapptz/discord.py/blob/9d2576e464bff87336c8b8134928c77e8d5ac55d/discord/client.py#L622) is done after the closing of [aiohttp.ClientWebSocketResponse](https://github.com/Rapptz/discord.py/blob/9d2576e464bff87336c8b8134928c77e8d5ac55d/discord/client.py#L633).

**Comment by overfl0** [comment] 2021-06-09 18:42
> That aside, v1.3 and v1.4 are months old and EOL and are not supported so any issue involving those issues are inactionable.

>I'm using v1.7.2 and also have this issue.

I didn't want to answer that earlier to prevent spam, but let me add that my earlier report pertained to 1.7.1 and the only reason I mentioned 1.3 and 1.4 was because I found the issue started happening with 1.4 (which Rapptz said coincides with the new websockets library being used, if I understood correctly)
