### ISSUE TITLE
Error when running bot

### ISSUE THREAD

**Issue by CookieKenneth** [Rapptz/discord.py#1594] opened 2018-09-19 01:28 UTC
**About**
My python bot was working normal, until i switched to PyCharm IDE and it messed with something that will make the bot to not start. I tried reinstalling python, discordpy but nothing works! I even deleted the files.

**Error**

```C:\Users\kenne\Desktop>C:\Users\kenne\Desktop\rocketflare.py
Traceback (most recent call last):
  File "C:\Users\kenne\Desktop\rocketflare.py", line 2, in <module>
    import discord
  File "C:\Users\kenne\CodingFiles\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\kenne\CodingFiles\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\kenne\CodingFiles\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\kenne\CodingFiles\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax```

**Comment by Harmon758** [comment] 2018-09-19 01:33
First of all, if that's a real token and you forgot to remove it, you're going to want to change your token now.
This is a duplicate of #1249 and #1401.

**Comment by CookieKenneth** [comment] 2018-09-19 01:35
> 
> 
> First of all, if that's a real token and you forgot to remove it, you're going to want to change your token now.
> This is a duplicate of #1249 and #1401.

That ticket is outdated, and it is not mine. And the token used was outdated.

**Comment by Harmon758** [comment] 2018-09-19 01:37
Those issues are still relevant if you're trying to use the async branch with Python 3.7.
Note that this might be the case for you since PyCharm sets up a virtualenv by default.

**Closed** 2018-09-19 01:36 UTC

**Comment by BluePhoenixGame** [comment] 2018-09-19 06:01
It's a very simple problem. The error tells us that you have no module named discord but before it worked. That tells us that PyCharm has made a venv(short for virtual environment) in this venv you have not installed discord.py . To fix, either install discord.py through PyCharm in your venv or disable the venv.
