### ISSUE TITLE
Issue with music play

### ISSUE THREAD

**Issue by Foxlider** [Rapptz/discord.py#1841] opened 2019-01-17 22:04 UTC
Hello everyone, 

I am having some weird issues lately with my discord bot while playing music... The music starts well and plays nicely but every time, after a minute or so I get this error while playing and everything stops. 
I think this is a ffmpeg error issue but after reinstalling different versions the error persists. 

```
[tls @ 0x8097aad0] Error in the pull function.
[matroska,webm @ 0x80978570] Read error
[tls @ 0x8097aad0] The specified session has been invalidated for some reason.
```

**Comment by Harmon758** [comment] 2019-01-18 00:41
Duplicate of #157, #315, #671, and #756.

**Closed** 2019-02-15 02:33 UTC
