### ISSUE TITLE
error in compat.py

### ISSUE THREAD

**Issue by TG-Techie** [Rapptz/discord.py#1774] opened 2018-12-14 00:56 UTC
trying to install on a mac running python 3.7.1

error message:

Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> import discord
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import discord
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
>>> 

I used "python3 -m pip install discord" to install it

Is it just me?

**Comment by Harmon758** [comment] 2018-12-14 00:56
Duplicate of #1249 and #1401

**Comment by FoxboyJT** [comment] 2018-12-16 11:48
This is because you are using python 3.7.1 and the async version of discord.py dosn't support it. Follow the instructions to install the developmental version (Rewrite)
`pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]`
To install without voice, simply remove [voice], you will need git to do this.

**Closed** 2018-12-17 06:52 UTC
Labels: duplicate
