### ISSUE TITLE
Refusing to continue code after joining voice

### ISSUE THREAD

**Issue by AlexFlipnote** [Rapptz/discord.py#6129] opened 2020-12-06 00:34 UTC
## Summary
When using Category.create_voice_channel() and then connect to the created channel, the bot joins but refuses to continue the code.

## Reproduction Steps
1. Try creating a channel and connect to it like this
```py
channel = ctx.guild.get_channel(category_id:int)
c = await channel.create_voice_channel("test")
await c.connect()
```
2. Wait for the bot to throw an error after timeout is called

## Expected Results
Bot joins channel and continues whatever code there is under it

## Actual Results
It stays on the `await c.connect()` and refuses to continue until it either times out or gives a AttributeError.

## Tracebacks
```py
File "C:\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\AlexFlipnote\Desktop\bot\cogs\station.py", line 97, in test
    prodcast = await self.create_channel()
  File "C:\Users\AlexFlipnote\Desktop\bot\cogs\station.py", line 68, in create_channel
    await c.connect()
  File "C:\Python38\lib\site-packages\discord\abc.py", line 1122, in connect
    await voice.connect(timeout=timeout, reconnect=reconnect)
  File "C:\Python38\lib\site-packages\discord\voice_client.py", line 346, in connect
    await self.disconnect(force=True)
  File "C:\Python38\lib\site-packages\discord\voice_client.py", line 460, in disconnect
    if self.ws:
AttributeError: 'VoiceClient' object has no attribute 'ws'
```
and sometimes the errors shifts to this
```py
  File "C:\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\AlexFlipnote\Desktop\bot\cogs\station.py", line 96, in test
    prodcast = await self.create_channel()
  File "C:\Users\AlexFlipnote\Desktop\bot\cogs\station.py", line 68, in create_channel
    await c.connect()
  File "C:\Python38\lib\site-packages\discord\abc.py", line 1154, in connect
    await voice.connect(timeout=timeout, reconnect=reconnect)
  File "C:\Python38\lib\site-packages\discord\voice_client.py", line 345, in connect
    await utils.sane_wait_for(futures, timeout=timeout)
  File "C:\Python38\lib\site-packages\discord\utils.py", line 350, in sane_wait_for
    raise asyncio.TimeoutError()
TimeoutError: 
```

## Intents
guilds, members, messages, reactions, presences

## Checklist
- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information
- Python v3.8.2-final
- discord.py v1.6.0-alpha
    - discord.py pkg_resources: v1.6.0a2598+g6ea7fce
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by Rapptz** [comment] 2020-12-06 01:01
Duplicate of already fixed #6039

**Closed by Rapptz** 2020-12-06 01:01 UTC
Labels: duplicate
