### ISSUE TITLE
rewrite : issue with channel.history(reverse=True)

### ISSUE THREAD

**Issue by flapili** [Rapptz/discord.py#1840] opened 2019-01-17 19:02 UTC
Hi, first I used discord.py version 1.0.0a1634+g7f4c57d, i noticed an issue with history(reverse=True)

This small code reproduce the issue:

```Python
import os

import discord
from discord.ext import commands

bot = commands.Bot(command_prefix='!', case_insensitive=True)

@bot.event
async def on_ready():
	print('ready\n')

@bot.command()
async def test(ctx):
	await ctx.message.delete()

	if not os.path.exists("test"):
		os.mkdir("test")

	msg_list = await ctx.channel.history(limit=None, reverse=False).flatten()
	with open(os.path.join("test", "None.txt"), "w") as f:
		for msg in msg_list:
			print(msg.content, file=f)

	msg_list = await ctx.channel.history(limit=10000, reverse=False).flatten()
	with open(os.path.join("test", "10000.txt"), "w") as f:
		for msg in msg_list:
			print(msg.content, file=f)

	msg_list = await ctx.channel.history(limit=None, reverse=True).flatten()
	with open(os.path.join("test", "None_reversed.txt"), "w") as f:
		for msg in msg_list:
			print(msg.content, file=f)

	msg_list = await ctx.channel.history(limit=10000, reverse=True).flatten()
	with open(os.path.join("test", "10000_reversed.txt"), "w") as f:
		for msg in msg_list:
			print(msg.content, file=f)

@bot.command()
async def spam(ctx):
	await ctx.message.delete()
	for i in range(10000):
		await ctx.send(i)

bot.run(foobar)
```

I don't know how explain this issue but when we use reverse=True channel.history only inverse the read of message in block of 100messages but the block still not reversed.
the best way I found to fix this problem is add msg_list.reverse()

[10000.txt](https://github.com/Rapptz/discord.py/files/2770158/10000.txt)
[10000_reversed.txt](https://github.com/Rapptz/discord.py/files/2770159/10000_reversed.txt)
[None.txt](https://github.com/Rapptz/discord.py/files/2770160/None.txt)
[None_reversed.txt](https://github.com/Rapptz/discord.py/files/2770161/None_reversed.txt)

**Comment by Harmon758** [comment] 2019-01-17 19:31
Duplicate of #548.
See [GitHub's documentation for code block formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by flapili** [comment] 2019-01-17 19:37
yeah, I understand the issue, I speak about the reduced utility of the flag `reversed=True`, it can be a source of issue and incomprehension I think.

**Comment by khazhyk** [comment] 2019-01-17 19:56
We could have reversed=True imply after=discord_epoch, and do the iterator that way? This would be breaking but might make sense

**Comment by Rapptz** [comment] 2019-04-08 12:02
Following #2048 this behaviour has been changed.

**Closed by Rapptz** 2019-04-08 12:02 UTC
Labels: rewrite
