### ISSUE TITLE
Random crashes when calling run function

### ISSUE THREAD

**Issue by programme-zero** [Rapptz/discord.py#2434] opened 2019-11-20 21:50 UTC
Hello,
recently I've been experiencing errors when starting the bot. I haven't chnaged the way I'm calling the function so I don't think the error is on my end.

The traceback 

![image](https://user-images.githubusercontent.com/48401036/69281142-10c6be80-0be8-11ea-9903-1dcb67e85456.png)

**Comment by avayert** [comment] 2019-11-20 21:51
Duplicate of #2422

**Closed** 2019-11-20 21:52 UTC
Labels: duplicate
