### ISSUE TITLE
After restarting a discord bot, it will no longer be active.

### ISSUE THREAD

**Issue by DerekLovesPandas** [Rapptz/discord.py#5145] opened 2020-07-22 05:34 UTC
A few minutes ago I tried to run my discord bot because I had turned my computer off, and I run it locally. It gave me an error saying: "TypeError: __new__() got an unexpected keyword argument 'deny_new'" for some reason. I checked with some friends, and they reran their bots and it gave the same issue.

**Comment by numbermaniac** [comment] 2020-07-22 05:34
Duplicate of #5109. Update your discord.py to fix the issue.

**Comment by DerekLovesPandas** [comment] 2020-07-22 05:35
Alright, thank you!

**Closed** 2020-07-22 05:39 UTC
