### ISSUE TITLE
ClientUser.permissions_in() throws AttributeError: 'ClientUser' object has no attribute '_roles'

### ISSUE THREAD

**Issue by osego** [Rapptz/discord.py#5979] opened 2020-10-27 17:10 UTC
## Summary

ClientUser.permissions_in() throws `AttributeError: 'ClientUser' object has no attribute '_roles'`

## Reproduction Steps

Minimal code that reproduces the issue:
```py
import discord

token = "TOKEN"
channel_id = 123
client = discord.Client(intents=discord.Intents.all())


@client.event
async def on_ready():
    channel = client.get_channel(channel_id)
    permissions = client.user.permissions_in(channel)

client.run(token)
```
Obviously, replace "TOKEN" with your preferred way of passing the token to the application and 123 with id of a channel that the bot can access.

## Expected Results

permissions_in() returning Permissions object.

## Actual Results

```py
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\xz\.virtualenvs\censored-project-name-9uTDvIzN\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "d:\code\pycharm\censored-project-name\src\main.py", line 14, in on_ready
    permissions = client.user.permissions_in(channel)
  File "C:\Users\xz\.virtualenvs\censored-project-name-9uTDvIzN\lib\site-packages\discord\user.py", line 239, in permissions_in
    return channel.permissions_for(self)
  File "C:\Users\xz\.virtualenvs\censored-project-name-9uTDvIzN\lib\site-packages\discord\channel.py", line 146, in permissions_for
    base = super().permissions_for(member)
  File "C:\Users\xz\.virtualenvs\censored-project-name-9uTDvIzN\lib\site-packages\discord\abc.py", line 486, in permissions_for
    roles = member._roles
AttributeError: 'ClientUser' object has no attribute '_roles'
```

This is caused by the fact that user.ClientUser inherits from user.BaseUser which defines permissions_in(channel) but it eventually gets deferred to abc.GuildChannel.permissions_for(member) which relies on the parameter being a member.Member.

## Intents

All intents enabled, passed intents=Intents.all() to the Client constructor.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.17763

**Comment by Rapptz** [comment] 2020-10-28 04:21
This is a duplicate of https://github.com/Rapptz/discord.py/issues/2025

**Closed by Rapptz** 2020-10-28 04:21 UTC
