### ISSUE TITLE
Crash on emote read

### ISSUE THREAD

**Issue by K-marad** [Rapptz/discord.py#2436] opened 2019-11-22 12:54 UTC
### Summary

The bot crashes when an emote is put on a line.

### Reproduction Steps

- Connect your bot to any discord server.
- On the server write a message
- On this message, append an emote, and the bot will crash

See image : I wrote "test". Then I put a cat or whatever that is emote on my message, and the bot crashes and restart. (The bot says "Sentinelle en position" when it connects to the server)

![Screenshot from 2019-11-22 13-51-26](https://user-images.githubusercontent.com/1223217/69427242-707bb180-0d2f-11ea-824e-59753f702a8b.png)

### Expected Results

I expected the bot not to crash...

### Actual Results

The bot crashed

```
sentinelle    | Traceback (most recent call last):
sentinelle    |   File "sentinelle.py", line 279, in <module>
sentinelle    |     client.run(DISCORD_TOKEN)
sentinelle    |   File "/usr/lib/python3.7/site-packages/discord/client.py", line 598, in run
sentinelle    |     return future.result()
sentinelle    |   File "/usr/lib/python3.7/site-packages/discord/client.py", line 579, in runner
sentinelle    |     await self.start(*args, **kwargs)
sentinelle    |   File "/usr/lib/python3.7/site-packages/discord/client.py", line 543, in start
sentinelle    |     await self.connect(reconnect=reconnect)
sentinelle    |   File "/usr/lib/python3.7/site-packages/discord/client.py", line 457, in connect
sentinelle    |     await self._connect()
sentinelle    |   File "/usr/lib/python3.7/site-packages/discord/client.py", line 421, in _connect
sentinelle    |     await self.ws.poll_event()
sentinelle    |   File "/usr/lib/python3.7/site-packages/discord/gateway.py", line 469, in poll_event
sentinelle    |     await self.received_message(msg)
sentinelle    |   File "/usr/lib/python3.7/site-packages/discord/gateway.py", line 423, in received_message
sentinelle    |     func(data)
sentinelle    |   File "/usr/lib/python3.7/site-packages/discord/state.py", line 409, in parse_message_reaction_add
sentinelle    |     emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
sentinelle    | KeyError: 'animated'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by avayert** [comment] 2019-11-22 12:55
Duplicate of the pinned issue #2422

**Closed** 2019-11-22 13:10 UTC
Labels: duplicate
