### ISSUE TITLE
websocket connection is closing + process hanging

### ISSUE THREAD

**Issue by Miolus** [Rapptz/discord.py#6048] opened 2020-11-16 18:06 UTC
My bot with 2 shards connects, and after 1 hour he is offline, the process hangs and in the console there stands:

websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
websocket connection is closing.
when I try to close the process, it hangs. Python 3.8.2, discord.py 1.5.1

**Comment by Miolus** [comment] 2020-11-16 18:08
If I pressed Ctrl+C 1000 times, it will close it sometimes and print cleanup_loop(loop)
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 92, in _cleanup_loop
    _cancel_tasks(loop)
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 77, in _cancel_tasks
    loop.run_until_complete(asyncio.gather(*tasks, return_exceptions=True))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 614, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

**Comment by TheRockettek** [comment] 2020-11-16 20:10
This information on this own does not help much. Can you provide any other information?

**Comment by Miolus** [comment] 2020-11-16 20:21
@TheRockettek i am using cogs (imported) + AutoSharded bot, my Network is safe (datacentre),  after the bot is offline no exception occurs, the bot just prints the message. There is not more i know.

**Comment by FightMan01** [comment] 2020-11-22 06:56
I also have this problem + Name or service not known spam.
![E15D1B7B-8B89-47A5-9EAB-232DC757FC04](https://user-images.githubusercontent.com/29693718/99897244-3887b100-2c98-11eb-9004-afb755bed3f0.png)

**Comment by Rapptz** [comment] 2020-11-22 11:22
This is a duplicate of prior discussion here: https://github.com/Rapptz/discord.py/discussions/6045

Your exception is a name resolution error which can be solved by placing a second DNS as backup. You can google how to do that since it depends on your circumstances.

**Closed by Rapptz** 2020-11-22 11:22 UTC
Labels: needs info
