### ISSUE TITLE
UnboundLocalError on any sort of connection blip/drop in 990fe24

### ISSUE THREAD

**Issue by sethwheway** [Rapptz/discord.py#4066] opened 2020-05-05 16:15 UTC
Quite simply, whenever something bad happens with your connection, this happens:
```
Traceback (most recent call last):
  File "C:/Users/sethw/PycharmProjects/ChatReviver/bot.py", line 54, in <module>
    bot.run(bot.config["bot"]["token"])
  File "C:\Users\sethw\PycharmProjects\ChatReviver\venv\lib\site-packages\discord\client.py", line 686, in run
    return future.result()
  File "C:\Users\sethw\PycharmProjects\ChatReviver\venv\lib\site-packages\discord\client.py", line 666, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\sethw\PycharmProjects\ChatReviver\venv\lib\site-packages\discord\client.py", line 630, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\sethw\PycharmProjects\ChatReviver\venv\lib\site-packages\discord\client.py", line 529, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Program Files\Python\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\sethw\PycharmProjects\ChatReviver\venv\lib\site-packages\discord\gateway.py", line 258, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "C:\Users\sethw\PycharmProjects\ChatReviver\venv\lib\site-packages\discord\http.py", line 859, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "C:\Users\sethw\PycharmProjects\ChatReviver\venv\lib\site-packages\discord\http.py", line 255, in request
    raise HTTPException(r, data)
UnboundLocalError: local variable 'r' referenced before assignment
```
I've been able to repro this with genuine disconnects, going into sleep mode and just disabling the
network adapter

### Checklist
- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
Latest commit of sharding-rework 990fe24
Windows 10, 3.8

**Comment by apple502j** [comment] 2020-05-05 16:32
NOTE: this can occur on master too

The problem is: r is only defined inside `async with`, which is inside the for loop. Maybe we should have a error for the retry (that doesn't require response as an argument)

**Comment by iomintz** [comment] 2020-05-05 18:39
That's odd. Alias variables defined by a with statement are accessible outside of the with block.

**Comment by iomintz** [comment] 2020-05-05 23:40
Oh I see. If the context manager's `__aenter__` raises an exception, `r` won't be defined. Could we just pass None instead?

**Comment by Rapptz** [comment] 2022-03-09 22:45
This has been fixed a while ago, just forgot to close this issue. Sorry.

**Closed by Rapptz** 2022-03-09 22:45 UTC
