### ISSUE TITLE
Add support for Connection Objects

### ISSUE THREAD

**Issue by rudes** [Rapptz/discord.py#714] opened 2017-08-13 06:46 UTC
I see in the Discord API spec there's an object for accessing linked account information. https://discordapp.com/developers/docs/resources/user#connection-object This would be really useful for integrations between steam and game trackers. I couldn't find anything for it in the docs. if i missed something i'm sorry.

**Comment by Vexs** [comment] 2017-08-13 06:54
The primary reason I don't think this has been implemented is because it's not usable by bot accounts- only user accounts.

**Comment by rudes** [comment] 2017-08-13 06:57
Wot? Sorry I missed where it specified users only. What a bummer I wish I could access public integrations.

**Comment by Rapptz** [comment] 2017-10-14 20:48
Duplicate of #521 I guess.

**Closed by Rapptz** 2017-10-14 20:48 UTC
Labels: duplicate
