### ISSUE TITLE
Keyerror = 'animated' crashing bot loop 

### ISSUE THREAD

**Issue by Willowlark** [Rapptz/discord.py#2423] opened 2019-11-18 23:53 UTC
### Summary

Crash related to animated emoji

### Reproduction Steps

Not sure what triggers the failure, it's all in the code library. I don't have anyone sending animated emoji, but I can't see every channel at every moment.

Apologies for crappy log format, came from docker logs

### Expected Results

Not crash

### Actual Results

application crash

### Checklist

-2019-11-18 23:34:49,stdout,KeyError: 'animated'

2019-11-18 23:34:49,stdout,"    emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
"
2019-11-18 23:34:49,stdout,"  File \"/usr/local/lib/python3.7/site-packages/discord/state.py\", line 406, in parse_message_reaction_add
"
2019-11-18 23:34:49,stdout,    func(data)

2019-11-18 23:34:49,stdout,"  File \"/usr/local/lib/python3.7/site-packages/discord/gateway.py\", line 419, in received_message
"
2019-11-18 23:34:49,stdout,    await self.received_message(msg)

2019-11-18 23:34:49,stdout,"  File \"/usr/local/lib/python3.7/site-packages/discord/gateway.py\", line 465, in poll_event
"
2019-11-18 23:34:49,stdout,    await self.ws.poll_event()

2019-11-18 23:34:49,stdout,"  File \"/usr/local/lib/python3.7/site-packages/discord/client.py\", line 395, in _connect
"
2019-11-18 23:34:49,stdout,    await self._connect()

2019-11-18 23:34:49,stdout,"  File \"/usr/local/lib/python3.7/site-packages/discord/client.py\", line 431, in connect
"
2019-11-18 23:34:49,stdout,    await self.connect(reconnect=reconnect)

2019-11-18 23:34:49,stdout,"  File \"/usr/local/lib/python3.7/site-packages/discord/client.py\", line 509, in start
"
2019-11-18 23:34:49,stdout,Traceback (most recent call last):

2019-11-18 23:34:49,stdout,"future: <Task finished coro=<Client.start() done, defined at /usr/local/lib/python3.7/site-packages/discord/client.py:500> exception=KeyError('animated')>
"
2019-11-18 23:34:49,stdout,Task exception was never retrieved

**Comment by TheRockettek** [comment] 2019-11-18 23:54
Update your discordpy version to the current master on github.

**Comment by ItWasAllIntended** [comment] 2019-11-19 00:00
Duplicate of #2422

**Comment by Harmon758** [comment] 2019-11-19 00:33
This should now be fixed with v1.2.5.
In the future, please make sure you're using the latest development version when reporting issues.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Closed** 2019-11-19 00:33 UTC
Labels: duplicate
