### ISSUE TITLE
Slash command

### ISSUE THREAD

**Issue by Cat4eve** [Rapptz/discord.py#7184] opened 2021-07-07 06:49 UTC
### Summary

Slash command for discord.py 2.0

### What is the feature request for?

discord.ext.commands

### The Problem

Recently, discord official api has been updated. Mostly, buttons and slash commands are the most remarkable and I want them to be added in discord.py 2.0. Buttons are something already created and somehow working. What about slash commands, we don't have them yet.

### The Ideal Solution

I think the best decision would be slash command code style like default command. 

from discord.ext.commands import Bot
client = Bot(# initial settings)

# we have this 
```
@client.command()
async def ping(ctx):
  print("pong")
```

# what I want slash command be like
# if slash command is multilevel, then name of function would reffer to the last option, while names and options of higher level would be provided in decorator body.
```
@client.slash()
async def ping(ctx):
  print("pong")
```

### The Current Solution

No solution yet.

### Additional Context

I hope people will correct and support both me and Danny.

**Comment by Rapptz** [comment] 2021-07-07 06:51
Duplicate of #6149

**Closed by Rapptz** 2021-07-07 06:51 UTC
Labels: feature request
