### ISSUE TITLE
Can't import discord

### ISSUE THREAD

**Issue by Moquo** [Rapptz/discord.py#2033] opened 2019-03-30 15:59 UTC
### Summary
When I try to import discord.py using `import discord`, I just get the output you can see below.

### Reproduction Steps
Install discord.py using pip.  
Then, I just open a python shell and type `import discord`.

### Expected Results
I should be able to normally import discord.py without any errors.

### Actual Results
```
>>> import discord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moritz/Documents/Projects/discord-account-bot2/venv/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/home/moritz/Documents/Projects/discord-account-bot2/venv/lib/python3.7/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/home/moritz/Documents/Projects/discord-account-bot2/venv/lib/python3.7/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/home/moritz/Documents/Projects/discord-account-bot2/venv/lib/python3.7/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
```

### Checklist
- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

- discord.py version: 0.16.12
- Python version: 3.7.2
- Operating system: Arch Linux

**Comment by laggycomputer** [comment] 2019-03-30 16:00
This problem's fix is already in this repo, but not on PyPi. Try reinstalling with `pip3 install git+https://github.com/Rapptz/discord.py@async -U`.

For further help, kindly join the support server at https://discord.gg/r3sSKJJ.

**Comment by Harmon758** [comment] 2019-03-30 16:04
Duplicate of #1249 and #1401

**Closed** 2019-03-30 16:04 UTC
