### ISSUE TITLE
Emote tag not stripped for clean_content

### ISSUE THREAD

**Issue by PikalaxALT** [Rapptz/discord.py#641] opened 2017-07-11 00:56 UTC
Messages with server emotes appear in `message.clean_content` as (for example)
 `<:EmoteString:12523463412413523>`.  They should appear as either `:EmoteString:` or `EmoteString` (no colons).

**Comment by Rapptz** [comment] 2017-07-11 00:56
Duplicate of #92

**Closed by Rapptz** 2017-07-11 00:56 UTC
