### ISSUE TITLE
Editing a Reply Message Does Not Conform to Allowed Mentions

### ISSUE THREAD

**Issue by MyerFire** [Rapptz/discord.py#6414] opened 2021-02-12 02:34 UTC
## Summary

If a message sent as a reply is edited, the occurring edited message will not have the proper allowed mentions applied to it.

## Reproduction Steps

To reproduce this bug, first, make sure the `discord.AllowedMentions` class passed during bot initialization disables mentions for `replied_users`. Then, fetch a message from a channel that you (the user trying to reproduce; this assumes that you are logged in to the Discord client) sent, reply to it, and assign the new message to a variable. Preferably, sleep a few seconds so this does not happen too fast, and then edit the message's content. Full code snippets are down below.

## Expected Results

I expected neither the message initially sent nor the edited version of the message sent later on to mention me ("mention me" here can be easily defined as the message turning yellow in the Discord application).

## Actual Results

The message sent initially did not mention me (expected), but after being edited, the message mentions me (the message turns yellow in the Discord client). This is unexpected.

## Intents

`discord.Intents.all()`

## System Information

$ `/home/myer/Myaer/bin/python -m discord -v`

- `Python v3.9.1-final`
- `discord.py v1.6.0-final`
- `aiohttp v3.7.3`
- `system info: Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020`

## Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

## In `bot.py`: 
```python
bot = commands.Bot(
    ...,
    allowed_mentions=discord.AllowedMentions(everyone=False, replied_user=False),
    ...,
)
```
## Testing In Jishaku:
```python
m = await message.reply("lol?")
await asyncio!.sleep(5)
m = await m.edit(content="xddd!!!!")
```

## Demonstration:
![Demonstration](https://i.myer.wtf/bxZui8s.gif)

**Comment by ImVaskel** [comment] 2021-02-12 02:35
Easily reproducible with jishaku.

**Comment by Zomatree** [comment] 2021-02-12 02:40
Duplicate of #6283

**Closed** 2021-02-12 02:44 UTC
Labels: bug
