### ISSUE TITLE
Bot Crashes when user makes new account

### ISSUE THREAD

**Issue by Eanae** [Rapptz/discord.py#87] opened 2016-01-14 03:57 UTC
Traceback (most recent call last):
  File "bot.py", line 321, in <module>
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/discord/client.py", line 550, in run
    self.ws.run()
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 427, in run
    if not self.once():
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 305, in once
    if not self.process(b):
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 377, in process
    self.received_message(s.message)
  File "/usr/local/lib/python2.7/dist-packages/discord/client.py", line 129, in received_message
    self.dispatch('socket_update', event, data)
  File "/usr/local/lib/python2.7/dist-packages/discord/client.py", line 527, in dispatch
    getattr(self, handle_method, utils._null_event)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/discord/client.py", line 535, in handle_socket_update
    getattr(self.connection, method)(data)
  File "/usr/local/lib/python2.7/dist-packages/discord/client.py", line 262, in handle_guild_member_add
    member = Member(server=server, deaf=False, mute=False, **data)
TypeError: type object got multiple values for keyword argument 'mute'

**Comment by Rapptz** [comment] 2016-01-14 03:59
Duplicate of #84.

**Closed by Rapptz** 2016-01-14 03:59 UTC
Labels: duplicate
