### ISSUE TITLE
Can anyone help me how to fix this error?

### ISSUE THREAD

**Issue by TunaHobby** [Rapptz/discord.py#1690] opened 2018-10-25 23:30 UTC
>>> import python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'python'
>>> import discord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

**Comment by crrapi** [comment] 2018-10-25 23:31
Duplicate of #1648, #1637, #1610, #1594, #1554, #1550, #1478, #1461, #1434, #1421, #1396, #1393, #1387, #1249, #1166, and #1116

**Comment by Harmon758** [comment] 2018-10-26 03:44
Also #1401

**Comment by lejakewolf** [comment] 2018-10-26 09:09
Quick question, why are you importing Python **_inside_** Python?

**Closed** 2018-11-25 04:39 UTC
Labels: duplicate
