### ISSUE TITLE
"reaction_remove" isn't known by wait_for

### ISSUE THREAD

**Issue by Fabetsol** [Rapptz/discord.py#6487] opened 2021-02-27 11:25 UTC
**Summary**

"reaction_remove" isn't known by wait_for

**Reproduction Steps**

I would make a "help message" where you can scroll with the reactions "left_arrow" and "right_arrow" when you react AND when you unreact.
So the "reaction_add" function works, but not the "reaction_remove" one, which cancels the command, without any error message.

**Expected Results**

I expected the bot showed the next (or previous) help message's page.

**Actual Results**

Nothing, the command just get canceled.

**Intents**

intents = discord.Intents.default()

**System Information**

- Python v3.8.3-final
- discord.py v1.6.0-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.18362

**Checklist**

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

Here is the code 

```
Help = ["First embed","second embed","third embed","fourth embed","fifth embed","sixth embed","seventh embed","eightth embed"]
@bot.command()
async def help(ctx):
        page = 0
        message = await ctx.send(embed = Help[page])
        await message.add_reaction("⬅️")
        await message.add_reaction("⏹️")
        await message.add_reaction("➡️")
        def checkEmoji(reaction, user):
                return ctx.message.author == user and message.id == reaction.message.id and (str(reaction.emoji) == "⬅️" or str(reaction.emoji) == "➡️" or str(reaction.emoji) == "⏹️")
        while True:
                try:
                        reaction, user = await bot.wait_for("reaction_add", timeout = 60, check = checkEmoji)
                        if reaction.emoji == "⬅️":
                                page -=1
                                if page < 0: page = 6
                        elif reaction.emoji == "➡️" :
                                page += 1
                                if page > 6: page = 0
                        elif reaction.emoji == "⏹️":
                                await message.delete()
                                return
                        await message.edit(embed = Help[page])
                        reaction, user = await bot.wait_for("reaction_remove", timeout = 60, check = checkEmoji)
                        if reaction.emoji == "⬅️":
                                page -=1
                                if page < 0: page = 6
                        elif reaction.emoji == "➡️" :
                                page += 1
                                if page > 6: page = 0
                        elif reaction.emoji == "⏹️":
                                await message.delete()
                                return
                        await message.edit(embed = Help[page])
                except:
                        return
```

**Comment by SebbyLaw** [comment] 2021-02-27 11:28
Duplicate of #6010

**Comment by Fabetsol** [comment] 2021-02-27 11:32
> Duplicate of #6010

No, because I don't use the **event** "on_reaction_remove", but the function `client.wait_for("reaction_remove", timeout = 60, check = checkEmoji)`

**Comment by Rapptz** [comment] 2021-02-27 11:33
`wait_for` and events operate under the same exact machinery. It's just waiting for the event to fire. If the conditions don't fire as explained in the original issue then the wait_for won't fire either.

**Closed by Rapptz** 2021-02-27 11:33 UTC
Labels: bug

**Comment by Fabetsol** [comment] 2021-02-27 12:12
> `wait_for` and events operate under the same exact machinery. It's just waiting for the event to fire. If the conditions don't fire as explained in the original issue then the wait_for won't fire either. Consider using the raw events instead.

It doesn't work too.
