### ISSUE TITLE
I need a bit of help, I am new to python and I have one issue.

### ISSUE THREAD

**Issue by ImMrMeseeks111** [Rapptz/discord.py#1478] opened 2018-08-02 13:43 UTC
Ok so basically i just started using python to make my first ever discord bot but i can apon one issue i was using the example from the discord.py and i tried to run it and i got this error 

Traceback (most recent call last):
  File "C:/Users/Brett/PycharmProjects/discordbot/oofbot", line 1, in <module>
    import discord
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

and i have no idea how to fix it. it is my first time using python and making my own discord bot so could you try to explain as easy to understand as possible? 

if anyone knows how to fix plz let me know im really trying to get this to work :(

**Comment by Harmon758** [comment] 2018-08-02 13:46
Duplicate of #1249

**Comment by ImMrMeseeks111** [comment] 2018-08-02 13:47
Oh sorry

**Comment by ImMrMeseeks111** [comment] 2018-08-02 13:47
is it resolved?

**Comment by Harmon758** [comment] 2018-08-02 13:49
See #1249

**Closed** 2018-08-20 01:34 UTC
Labels: duplicate
