### ISSUE TITLE
TextChannel.overwrites does not include members

### ISSUE THREAD

**Issue by bunny-foofoo** [Rapptz/discord.py#6150] opened 2020-12-10 21:27 UTC
## Summary

When trying to view a channel's permissions, roles will be returned as expected, but member permissions do not appear.

## Reproduction Steps

**First through the Discord app:**
1. Add a role to a channel's permissions.
2. Add a member to the channel's permissions.

**Then through discord.py:**
1. Check the channel's .overwrites value

## Expected Results

According to [the docs](https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.overwrites), .overwrites should contain all of the role permissions as well as permissions specific to a member.
The above steps should result in seeing permissions for: Role A, the default everyone role, and the added member.

## Actual Results

Printing out the TextChannel.overwrite value resulted in:

> {\<Role id=442518609185734657 name='@ everyone'>: <discord.permissions.PermissionOverwrite object at 0x7128bdc0>, \<Role id=786680559283470336 name='Role A'>: <discord.permissions.PermissionOverwrite object at 0x7128bcd0>}

## Intents

intents = discord.Intents.default()
intents.members = True
intents.typing = False
intents.presences = False

## Checklist

- [ x ] I have searched the open issues for duplicates.
- [ x ] I have shown the entire traceback, if possible.
- [ x ] I have removed my token from display, if visible.
- [ x ] I have provided the intents that my bot is using.

## System Information

Python v3.8.0-final
discord.py v1.5.1-final
aiohttp v3.6.3

**Comment by SebbyLaw** [comment] 2020-12-10 21:30
Duplicate of #5882 
Also see #6084

**Closed** 2020-12-10 22:57 UTC
Labels: duplicate
