### ISSUE TITLE
TypeError in channel.edit in the api itself

### ISSUE THREAD

**Issue by Ari24-cb24** [Rapptz/discord.py#5114] opened 2020-07-09 20:59 UTC
### Summary

So, im trying to edit a channel and the API just gives me an error. I know some other people having the same issue and I researched in the web but didnt found antyhing about it.

### Reproduction Steps

I build my own member counter a couple of months ago and today I just restarted my bot. And then this error happens with this code:

```py
async def set_member_count():
    channel = client.get_channel(653305074835128320)
    guild = discord.utils.get(client.guilds, id=511984457612394539)
    total = 0
    for member in guild.members:
        if not member.bot:
            total += 1
    await channel.edit(name="Mitglieder: " + str(total))
```

### Expected Results

Normally, it should just set the channels name 🤷 

### Actual Results

```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "/home/pi/Hosting/Tendo/Tendo.py", line 1048, in on_ready
    await set_member_count()
  File "/home/pi/Hosting/Tendo/Tendo.py", line 645, in set_member_count
    await channel.edit(name="Mitglieder: " + str(total))
  File "/home/pi/.local/lib/python3.7/site-packages/discord/channel.py", line 608, in edit
    await self._edit(options, reason=reason)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 262, in _edit
    self._update(self.guild, data)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/channel.py", line 535, in _update
    self._fill_overwrites(data)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'allow_new'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

```
- Python v3.7.3-final
- discord.py v1.2.5-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019
```

### Some extra infos
After I got this exception I upgraded discord.py but still the same error
Btw, my bot is currently running on a raspberrypi 3b

**Comment by Harmon758** [comment] 2020-07-09 21:08
Duplicate of #5109

**Closed** 2020-07-09 21:08 UTC
Labels: duplicate
