### ISSUE TITLE
audioop not found while run simple scripts

### ISSUE THREAD

**Issue by Quanvm0501alt1** [Rapptz/discord.py#10023] opened 2024-11-23 04:10 UTC
### Summary

Discord module importing audioop, but not found

### Reproduction Steps

Use under code, and run
_I knew it was removed, but I want you to replace audioop with the more complicated module_

### Minimal Reproducible Code

```python
import lib1
import discord, base64

intents = discord.Intents.default()
intents.message_content = True

client = discord.Client(intents=intents)

prefix = "$"

@client.event
async def on_ready():
	print(f'We have logged in as {client.user}')

@client.event
async def on_message(message):
	global prefix
	if message.author == client.user:
		return

	if message.content.startswith(f'{prefix}hello'):
		await message.channel.send('Hello!')

client.run("yourbottoken")
```

### Expected Results

Script ran sucessful after decode token base64 encoded

### Actual Results

![ảnh](https://github.com/user-attachments/assets/4c63cede-6452-4803-9aff-13163d983da5)

### Intents

discord.Intents.default()

### System Information

Discord v2.4.0
Python v3.13.0 (+)

### Checklist

- [ ] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Replace the audioop with pydub: https://github.com/jiaaro/pydub

**Comment by Quanvm0501alt1** [comment] 2024-11-23 04:11
Please Remove `import lib1`

**Comment by Rapptz** [comment] 2024-11-23 04:15
Dupe of https://github.com/Rapptz/discord.py/issues/9477

**Closed by Rapptz** 2024-11-23 04:15 UTC
Labels: duplicate
