### ISSUE TITLE
ClientConnectorCertificateError: Cannot connect to host discord.com:443

### ISSUE THREAD

**Issue by wevans16736** [Rapptz/discord.py#5880] opened 2020-10-02 14:21 UTC
Traceback (most recent call last):
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jeremy\Desktop\bot.py", line 19, in <module>
    client.run('NzYxNDA4NjMzMjQ5NzI2NDY0.X3aLDA.gRug_lcLFaex-bBfoL78abXNW7U')
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 708, in run
    return future.result()
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 687, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 650, in start
    await self.login(*args, bot=bot)
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 499, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\http.py", line 291, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 938, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')]
[Finished in 1.739s]

Code is:
import discord
from discord.ext import commands

client = commands.Bot(command_prefix = 'sudo')

@client.event
async def on_ready():
    print('Bot is ready.')

@client.event
async def on_member_join(member):
    print(f'{member} has joined the server.')

@client.event
async def on_member_remove(member):
    print(f'{member} has left the server')

client.run('notyourtoken')

Version 3.8.6 of Python

**Comment by TheRockettek** [comment] 2020-10-02 14:22
Duplicate of #4159

**Comment by wevans16736** [comment] 2020-10-02 15:00
> Duplicate of #4159

Do you have a solution or not?  I posted because I didn't find a solution in any other, not to have indian tech support come rant about it being a duplicate.

**Comment by averwhy** [comment] 2020-10-02 15:02
I mean... the solution is at issue #4159

**Comment by wevans16736** [comment] 2020-10-02 15:04
Could you please post it for me? If it's about the certificate thing, Explorer and chrome don't have an option to download certificates for me, so that solution is out.

**Comment by TheRockettek** [comment] 2020-10-02 15:07
Look at the other issue and it will say. Also you can install certificates on internet explorer, did you fully read it when it said run it as administrator? 
![iexplore_08hsgIcthT](https://user-images.githubusercontent.com/17106916/94938969-6a1aa200-04c9-11eb-8a92-16a5f7852dd7.png)

**Comment by wevans16736** [comment] 2020-10-02 15:11
I'm still getting the same error after installing a new certificate, is a restart required by any chance? I've put it into the folder they say to and it tells me the import was successful.

**Comment by fwrs** [comment] 2020-10-02 18:49
please don't delete the default issue template when creating a bug report, it has a lot of useful info that you should read before posting

**Closed** 2020-10-02 20:18 UTC
Labels: duplicate

**Comment by AAAGGG123** [comment] 2022-04-16 14:05
I just do like [#4519](https://github.com/Rapptz/discord.py/issues/4159) 

Windows:

Go to start, type internet explorer. Run as admin.
Go do https://discord.com/ click on the padlock icon.
Click view certificates
Click install certificates, choose either user or local machine.
Click Place all certificates in the following store
Choose Trusted Root Certification Authorities
Enjoy.

BUT still not work.

**Comment by VAUsIGT** [comment] 2024-03-27 21:58
"SSL: CERTIFICATE_VERIFY_FAILED" - the bot tries to contact the site, but sees an unknown certificate on it. You need to manually upload this certificate to trusted:
1. On the website, click on the lock (next to the url) --> find a valid certificate --> in the advanced tab, export it in the ".crt" format
2. Open "MMC" via start. Next, file --> add snap-in --> certificates --> add --> my account (then also add for local PC) --> open certificates - local PC through the root of the console --> action --> all tasks --> next and overview --> find the certificate downloaded in p.1 --> done!

**Comment by cordial-charles422** [comment] 2025-02-02 09:39
All set



https://pythoner.space/questions/the-onmemberjoin-and-onmemberremove-events-are-experiencing-technical-difficulties-and-are-not-functioning-properly
