### ISSUE TITLE
Python 3.7 Incompatibility

### ISSUE THREAD

**Issue by Coolguy3289** [Rapptz/discord.py#1648] opened 2018-10-06 18:55 UTC
New in Python 3.7:
```
Backwards incompatible syntax changes:
    async and await are now reserved keywords.
```
Due to this, the code in compat.py 
```
except AttributeError:
    create_task = asyncio.async
```
Discord will not run because of a syntax error:
```
Traceback (most recent call last):
  File "C:/Users/Ralph/PycharmProjects/asukabot/app/main.py", line 1, in <module>
    import discord
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
```

**Comment by Harmon758** [comment] 2018-10-06 18:56
Duplicate of #1249 and #1401

**Comment by Coolguy3289** [comment] 2018-10-06 19:13
Right, so just gonna switch to the rewrite.  Is there something in the docs to reference this?

**Comment by Harmon758** [comment] 2018-10-06 19:15
See https://discordpy.readthedocs.io/en/rewrite/migrating.html.
You should also join the [official discord.py server](https://discord.gg/r3sSKJJ) for news and updates, including breaking changes, about the rewrite branch.

**Comment by Harmon758** [comment] 2018-10-06 19:27
The rewrite branch is the next major version of the library.
For further questions about it should be directed to the [official discord.py server](https://discord.gg/r3sSKJJ).

**Closed** 2018-10-06 20:11 UTC
