### ISSUE TITLE
Add support for oauth2 / bearer token support

### ISSUE THREAD

**Issue by Merlintor** [Rapptz/discord.py#1525] opened 2018-08-19 11:15 UTC
Would be cool if the library would support bearer tokens. To make the oauth flow in python (aiohttp, django, flask) easier.
I think an implementation like the webhook support would make sense, so it's not really related with the bot oauth, but you can use it in your code.

**Comment by Harmon758** [comment] 2018-08-19 11:46
Duplicate of #521

**Closed** 2018-08-20 01:42 UTC
Labels: duplicate
