### ISSUE TITLE
Audio Recording Feature

### ISSUE THREAD

**Issue by Ariz-z** [Rapptz/discord.py#8162] opened 2022-06-19 07:05 UTC
### Summary

With the audio recording feature we can record the audio in voice channel with different extensions. Like mp3, mp4, wav, m4a and many more. This feature is already in pycord but i don't want to shift to pycord just because of 1 feature. 

### What is the feature request for?

The core library

### The Problem

Many of the user want's this feature so that they can't shift from this library to another library or language because this feature is very usefull.

### The Ideal Solution

With this feature bot will join the voice channel after running a specific command to start recording the voice in the voice channel. Then after running stop command to stop the recording after the recording is stoped it will automatically send the recorded file in that channel.

**Comment by Rapptz** [comment] 2022-06-19 07:25
> This feature is already in pycord but i don't want to shift to pycord just because of 1 feature.

Yes, because it was taken from the pull requests in this repository.

This is a duplicate of #444 and #1094.

**Closed by Rapptz** 2022-06-19 07:25 UTC
Labels: feature request

**Comment by Ariz-z** [comment] 2022-06-19 07:29
So will it be added in this library?

**Comment by HayBaleAv** [comment] 2022-06-19 08:44
> So will it be added in this library?

unlikely

**Comment by lol219** [comment] 2022-06-19 09:14
What's the point for recording audio.
