### ISSUE TITLE
discord.py bot working fine within venv on macOS, errors everywhere else?

### ISSUE THREAD

**Issue by k0rnsyrup** [Rapptz/discord.py#1617] opened 2018-09-26 09:48 UTC
Until today, I have excluslvely tested my program inside a virtual environment on macOS, and for the most part everything seems to be working smoothly. I decided it was time to host the bot on a windows server, so i compiled it and then ran it through the command line in windows 10, and was getting errors that i’d never seen before.

The errors are posted here.

```
creating account with blahblah@email.com

_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=ClientConnectorError(11001, 'getaddrinfo failed')>
Traceback (most recent call last):
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 843, in _create_direct_connection
traces=traces), loop=self._loop)
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 730, in _resolve_host
self._resolver.resolve(host, port, family=self._family)
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
host, port, type=socket.SOCK_STREAM, family=family)
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\thread.py", line 56, in run
result = self.fn(*self.args, **self.kwargs)
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 745, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\tammu\Desktop\ebaybot\ebay_discord.py", line 160, in create_account
async with session.post(url, headers=headers, data=data, proxy=proxy1) as resp:
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 855, in __aenter__
self._resp = await self._coro
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 370, in _request
timeout=timeout
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 445, in connect
proto = await self._create_connection(req, traces, timeout)
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 754, in _create_connection
req, traces, timeout)
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 896, in _create_proxy_connection
proxy_req, [], timeout, client_error=ClientProxyConnectionError)
File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 847, in _create_direct_connection
raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host us-dynamic-1.resd.leafproxies.com:10013 ssl:None [getaddrinfo failed]


creating account with blahblah@email.com
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=ClientConnectorError(11001, 'getaddrinfo failed')>
Traceback (most recent call last):
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 843, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 730, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tammu\Desktop\ebaybot\ebay_discord.py", line 160, in create_account
    async with session.post(url, headers=headers, data=data, proxy=proxy1) as resp:
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 855, in __aenter__
    self._resp = await self._coro
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 370, in _request
    timeout=timeout
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 445, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 754, in _create_connection
    req, traces, timeout)
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 896, in _create_proxy_connection
    proxy_req, [], timeout, client_error=ClientProxyConnectionError)
  File "C:\Users\tammu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 847, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host us-dynamic-1.resd.leafproxies.com:10013 ssl:None [getaddrinfo failed]
```
I then tried running the program through macOS terminal and got these errors as well.

```
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=RuntimeError('File descriptor 12 is used by transport <_SelectorSocketTransport fd=12 read=idle write=<idle, bufsize=0>>',)>
Traceback (most recent call last):
  File "/Users/me/anaconda3/lib/python3.6/asyncio/selector_events.py", line 455, in _sock_connect
    sock.connect(address)
BlockingIOError: [Errno 36] Operation now in progress

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ebay_discord.py", line 154, in create_account
    async with session.post(url, headers=headers, data=data, proxy=proxy1) as resp:
  File "/Users/me/anaconda3/lib/python3.6/site-packages/aiohttp/client.py", line 565, in __aenter__
    self._resp = yield from self._coro
  File "/Users/me/anaconda3/lib/python3.6/site-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/Users/me/anaconda3/lib/python3.6/site-packages/aiohttp/connector.py", line 304, in connect
    yield from self._create_connection(req)
  File "/Users/me/anaconda3/lib/python3.6/site-packages/aiohttp/connector.py", line 576, in _create_connection
    transport, proto = yield from self._create_proxy_connection(req)
  File "/Users/me/anaconda3/lib/python3.6/site-packages/aiohttp/connector.py", line 636, in _create_proxy_connection
    proxy_req)
  File "/Users/me/anaconda3/lib/python3.6/site-packages/aiohttp/connector.py", line 601, in _create_direct_connection
    local_addr=self._local_addr)
  File "/Users/me/anaconda3/lib/python3.6/asyncio/base_events.py", line 765, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Users/me/anaconda3/lib/python3.6/asyncio/selector_events.py", line 449, in sock_connect
    self._sock_connect(fut, sock, address)
  File "/Users/me/anaconda3/lib/python3.6/asyncio/selector_events.py", line 463, in _sock_connect
    self.add_writer(fd, self._sock_connect_cb, fut, sock, address)
  File "/Users/me/anaconda3/lib/python3.6/asyncio/selector_events.py", line 346, in add_writer
    self._ensure_fd_no_transport(fd)
  File "/Users/me/anaconda3/lib/python3.6/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
    fd, transport))
RuntimeError: File descriptor 12 is used by transport <_SelectorSocketTransport fd=12 read=idle write=<idle, bufsize=0>>
```

My source code is here.
https://pastebin.com/Awpq1A3x

Can you please help me figure out what is going wrong with my program?
Thank you very much for any assistance.

Jordan

**Comment by Rapptz** [comment] 2018-09-26 09:52
This issue is unrelated to the library itself, rather it is an issue with your DNS and `getaddrinfo`.

**Comment by scragly** [comment] 2018-09-26 09:52
Please avoid creating duplicate issues.
Also as far as I can see, this issue is not related to the functioning of discord.py, and is instead a general code assistance request, which doesn't belong as a github Issue for this lib.

If you wish for help with using the lib, and you have not found a bug in the lib code itself, please go to the [discord.py support server](https://discord.gg/r3sSKJJ) or [discord api support](https://discord.gg/discord-api).

If you wish for general code assistance that isn't related to the lib, please see any of the many general python support servers available, such as [this one](https://discord.gg/8NWhsvT).

In future, please avoid making issues for code help.

**Comment by Harmon758** [comment] 2018-09-26 09:52
As @scragly noted, you're going to want to change your token now if you haven't.
Closing the previous issue and creating this new one does not invalidate your leaked token.

The first set of errors is a failure to connect to`host us-dynamic-1.resd.leafproxies.com:10013`.
Based on information from [this blog post](http://www.codeghar.com/blog/use-select-in-python-socket-programming-at-your-own-risk.html), the second seems to be caused by your process creating too many socket connections.
Based on a cursory overview, what you're doing does not seem legitimate, and as such you're unlikely to get any further support.

For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Closed by Rapptz** 2018-09-26 09:52 UTC
