### ISSUE TITLE
"after" parameter of fetch_members does not work (well) using datetime

### ISSUE THREAD

**Issue by tilnow** [Rapptz/discord.py#5974] opened 2020-10-26 20:21 UTC
## Summary

the after parameter in fetch_members() does not work if after is a datetime object.

## Reproduction Steps

mem=await g.fetch_members(after=datetime.datetime.fromtimestamp(prevread)).flatten()

(where prevread is zero)

when run as `mem=await g.fetch_members()` it returns all 656 members

## Expected Results

656 members

## Actual Results

We have logged in as Shepherd#2960 [...  shard_id=None chunked=True member_count=656>]
...

.....
0 1970-01-01 00:00:00 ### is printed by `print(prevread,datetime.datetime.fromtimestamp(prevread))`
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/yak/.local/lib/python3.6/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "shepherd.py", line 49, in on_ready
    await update_database()
  File "shepherd.py", line 108, in update_database
    await read_and_add()
  File "shepherd.py", line 117, in read_and_add
    mem=await g.fetch_members(after=datetime.datetime.fromtimestamp(prevread)).flatten() # reads only ones added since prevread
  File "/home/yak/.local/lib/python3.6/site-packages/discord/iterators.py", line 75, in flatten
    item = await self.next()
  File "/home/yak/.local/lib/python3.6/site-packages/discord/iterators.py", line 605, in next
    await self.fill_members()
  File "/home/yak/.local/lib/python3.6/site-packages/discord/iterators.py", line 627, in fill_members
    data = await self.get_members(self.guild.id, self.retrieve, after)
  File "/home/yak/.local/lib/python3.6/site-packages/discord/http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In after: long value should be greater than or equal to 0.

*when prevread was set to be a timestamp of 1973, it also failed. when set to be 2019, a date when the guild did not exist yet, it read only 304 members out of >500 (maybe it used it as a snowflake?).

## Intents

intents = discord.Intents.default()
intents.members = True
client = discord.Client(intents=intents)

## Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.
- [x ] I have provided the intents that my bot is using.

## System Information
python3 -m discord -v
- Python v3.6.9-final
- discord.py v1.5.0-final
- aiohttp v3.6.2
- system info: Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020

**Comment by Rapptz** [comment] 2020-10-27 02:11
Duplicate of #5973

**Closed by Rapptz** 2020-10-27 02:11 UTC
Labels: bug, duplicate
