### ISSUE TITLE
channel.fetch_message(1).content returns blank string

### ISSUE THREAD

**Issue by ShareefAljuneidi** [Rapptz/discord.py#7858] opened 2022-04-08 23:34 UTC
### Summary

channel.fetch_message(1).content returns blank string

### Reproduction Steps

- Send a message in discord
- fetch the channel
- fetch the message by ID
- try to get the content on the newly fetched message

### Expected Results

Receive the actual message content

### Actual Results

Received empty string

### Intents

All intents

### System Information

- Python v3.8.2-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4062+gf078859
- aiohttp v3.7.4.post0
- system info: Linux 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by nerdguyahmad** [comment] 2022-04-08 23:43
Have you also enabled `message_content` intent in your code?

If so, try disabling and re-enabling the message content intent toggle in Dev portal.

**Comment by Rapptz** [comment] 2022-04-09 00:48
Dupe of https://github.com/Rapptz/discord.py/issues/7753

**Closed by Rapptz** 2022-04-09 00:48 UTC
Labels: duplicate

**Comment by ShareefAljuneidi** [comment] 2022-04-09 01:59
> Have you also enabled `message_content` intent in your code?
> 
> If so, try disabling and re-enabling the message content intent toggle in Dev portal.

I have all the intents enabled in my code and in the developer poral.
