### ISSUE TITLE
Stub file?

### ISSUE THREAD

**Issue by JellyWX** [Rapptz/discord.py#2252] opened 2019-06-28 15:08 UTC
### The Problem

Mypy and other static checkers have nothing to check against with D.py

### The Ideal Solution

A stub file compatible with Mypy that details types in D.py

### The Current Solution

None existing

### Summary

A types stub file would be useful (PEP 561 I think..?)

**Comment by bmintz** [comment] 2019-06-28 19:17
Duplicate of #1497

**Closed** 2019-06-28 19:22 UTC
