### ISSUE TITLE
bot.load_extension() relative imports

### ISSUE THREAD

**Issue by ghost** [Rapptz/discord.py#2609] opened 2020-03-23 00:18 UTC
### Summary

Failed to load extension general
ValueError: no package specified for '...cogs.general' (required for relative module names)

### Reproduction Steps

I tried to import a cog location in the parent of the working directory.
`extension = "general"
bot.load_extension(f"...cogs.{extension}")`

### Expected Results

Load the cog "general.py" that I have located in parent of the working directory.

### Actual Results

Traceback (most recent call last):
  File "c:\Users\adam\Desktop\bots\fnshop-bot\bot.py", line 93, in <module>
    bot.load_extension(f"...cogs.{extension}")
  File "C:\Users\adam\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 649, in load_extension
    spec = importlib.util.find_spec(name)
  File "C:\Users\adam\AppData\Local\Programs\Python\Python38\lib\importlib\util.py", line 90, in find_spec
    fullname = resolve_name(name, package) if name.startswith('.') else name
  File "C:\Users\adam\AppData\Local\Programs\Python\Python38\lib\importlib\util.py", line 32, in resolve_name
    raise ValueError(f'no package specified for {repr(name)} '
ValueError: no package specified for '...cogs.utility' (required for relative module names)

### Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

### System Information

- Python v3.8.1-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by Auxtal** [comment] 2020-07-08 11:29
Have you fixed this yet because i have the same problem

**Comment by Rapptz** [comment] 2021-02-18 05:31
Duplicate of #2465 more than likely.

**Closed by Rapptz** 2021-02-18 05:31 UTC
