### ISSUE TITLE
discord-py 1.5.1 requires aiohttp<3.7.0,>=3.6.0, but you'll have aiohttp 3.7.3 which is incompatible.

### ISSUE THREAD

**Issue by johnsturgeon** [Rapptz/discord.py#6081] opened 2020-11-24 17:53 UTC
## Summary

Need to support the new aiohttp

**Comment by johnsturgeon** [comment] 2020-11-24 17:54
using the new dependancy resolver on pip I get this:
```
ERROR: Cannot install aiohttp==3.7.3 and discord-py 1.5.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested aiohttp==3.7.3
    discord-py 1.5.1 depends on aiohttp<3.7.0 and >=3.6.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by Harmon758** [comment] 2020-11-24 19:00
Duplicate of #5970 and #5984 
This has already been resolved with https://github.com/Rapptz/discord.py/commit/7f3737fcc2fc32078b0904131adcaa75d5eda942 on the master branch. In the future, please make sure your issue exists with the latest development version when reporting issues.

**Closed** 2020-11-24 19:00 UTC
Labels: bug
