### ISSUE TITLE
Error with something

### ISSUE THREAD

**Issue by archiebaer** [Rapptz/discord.py#1610] opened 2018-09-23 20:55 UTC
Traceback (most recent call last):
  File "live.py", line 6, in <module>
    import discord
  File "C:\Users\Archie\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Archie\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\Archie\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\Archie\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

**Comment by Harmon758** [comment] 2018-09-23 20:56
Duplicate of #1249 and #1401

**Comment by archiebaer** [comment] 2018-09-23 20:57
Oh, Okay, Apparently I'm too modern.

**Comment by archiebaer** [comment] 2018-09-23 20:57
Thanks

**Comment by archiebaer** [comment] 2018-09-23 20:57
How do I close the issue?

**Comment by Harmon758** [comment] 2018-09-23 21:06
There should be a button to do so next to the Comment button.

In the future, please don't spam consecutive comments, as each comment on an issue is potentially a separate notification.

**Closed** 2018-09-23 21:08 UTC
