### ISSUE TITLE
Members

### ISSUE THREAD

**Issue by LeonidMem** [Rapptz/discord.py#5942] opened 2020-10-17 05:20 UTC
## Summary

All my bots with administator's role can't get any user or member of guild, but some days ago they could.

## Reproduction Steps

First of all, I created server, invited bot and gave him administrator's role.

After, I run this code:
`import discord
from discord.ext import commands

token = "..."
bot = commands.Bot(command_prefix='-')
guild_id = 765260553471918150
needed_role_id = 766291848758558792

@bot.event
async def on_connect():
    guild = await bot.fetch_guild(guild_id)
    print("Is guild is None?", guild is None)
    print("Guild members:", guild.members)
    role = guild.get_role(needed_role_id)
    async for i in guild.fetch_members():
        if role in i.roles:
            print("OK")

bot.run(token)`

## Expected Results

Members will be given as filled list and at least **for** cycle will do something. It worked without any problems some days ago.

## Actual Results

But I've got empty list of members and cycle **for** doesn't work.

Output _(stacktrace included)_:
`Is guild is None? False
Guild members: []
Ignoring exception in on_connect
Traceback (most recent call last):
  File "...\venv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File ".../main.py", line 67, in on_connect
    async for i in guild.fetch_members():
  File "...\venv\lib\site-packages\discord\iterators.py", line 86, in __anext__
    msg = await self.next()
  File "...\venv\lib\site-packages\discord\iterators.py", line 605, in next
    await self.fill_members()
  File "...\venv\lib\site-packages\discord\iterators.py", line 627, in fill_members
    data = await self.get_members(self.guild.id, self.retrieve, after)
  File "...\venv\lib\site-packages\discord\http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access`

## Intents

Code
`client = discord.Client()
print(client.intents)`
printed **<Intents value=32509>** _(I didn't change anything, so this value is probably default)_

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

I'm running my code using PyCharm with Python 3.7.

**Comment by SebbyLaw** [comment] 2020-10-17 05:23
Duplicate of #5867.

**Closed** 2020-10-17 05:25 UTC
Labels: intents related
