### ISSUE TITLE
Optionally allow commands.Bot to NOT ignore messages from other bots.

### ISSUE THREAD

**Issue by dyc3** [Rapptz/discord.py#6579] opened 2021-03-26 23:52 UTC
### Summary

Optionally allow commands.Bot to NOT ignore messages from other bots.

### What is the feature request for?

discord.ext.commands

### The Problem

I would like to automate the integration tests for my bot using https://github.com/JakeCover/distest. Unfortunately, the `process_commands` function checks messages to see if they come from a bot and ignores them, and this is not configurable.

### The Ideal Solution

A keyword argument or environment variable to disable the check for `message.author.bot`. Something like `allow_bot_messages=True`

### The Current Solution

Manually patch the check for `message.author.bot` out, or use `self_bot=True` but that requires the tested bot to be the same as the bot testing it.

**Comment by SebbyLaw** [comment] 2021-03-27 00:08
Duplicate of #2238

**Comment by Rapptz** [comment] 2021-03-27 00:09
If you want to do this then you can just override `on_message` and bypass `process_commands` by implementing it manually:

```py
async def on_message(self, message):
    ctx = await self.get_context(message)
    if ctx.valid:
        await bot.invoke(ctx)
```

Alternatively you can override `process_commands` to remove the check itself. 

These low level tools and their relationship with `process_commands` and `on_message` are already documented so the tools to do this are already there and don't require any sort of patching or modifying of anything.

**Closed by Rapptz** 2021-03-27 00:09 UTC
Labels: feature request
