### ISSUE TITLE
get_quoted_word is confused by u2019 (’)

### ISSUE THREAD

**Issue by GriffinG1** [Rapptz/discord.py#6296] opened 2021-01-12 09:15 UTC
## Summary

get_quoted_word throws an UnexpectedQuoteError when u2019 (`’`) is used in the contents of a command invoke

## Reproduction Steps

```py
@bot.command()
async def foo(ctx, s):
    await ctx.send(s)
```
Pass in a string containing characters combined with u2019 to foo (ex. `test’`)

## Expected Results

Foo then sends the passed in string

## Actual Results

Foo throws an UnexpectedQuoteError, based off of u2019
```
Traceback (most recent call last):
  File "C:\Users\gpgro\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\gpgro\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 856, in invoke
    await self.prepare(ctx)
  File "C:\Users\gpgro\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 790, in prepare
    await self._parse_arguments(ctx)
  File "C:\Users\gpgro\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 697, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "C:\Users\gpgro\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 549, in transform
    argument = view.get_quoted_word()
  File "C:\Users\gpgro\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\view.py", line 174, in get_quoted_word
    raise UnexpectedQuoteError(current)
discord.ext.commands.errors.UnexpectedQuoteError: Unexpected quote mark, '’', in non-quoted string
```

## Intents

All.

## Checklist

- [x] I have searched the open issues for duplicates. (#4175 seems tangentially related, but not directly)
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.1-final
- discord.py v1.6.0-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.18362

**Comment by Rapptz** [comment] 2021-01-12 10:46
Yes.

The ’ is meant to be matched with ‘ and it's not here. This is a duplicate of https://github.com/Rapptz/discord.py/issues/4175

**Closed by Rapptz** 2021-01-12 10:46 UTC
Labels: bug
