### ISSUE TITLE
Discord.py guild.owner is not working

### ISSUE THREAD

**Issue by izzetemredemir** [Rapptz/discord.py#5978] opened 2020-10-27 15:34 UTC
## Summary
guild.owner is not working
I was using discord.py 1.4.1 Some problems happened on my bot today. I updated package to 1.5.1 and It still continue.
So guild.owner returns none It was working. I solved this issue with using ctx.guild.owner_id insted of using ctx.guild.owner

**Comment by RealymanLP** [comment] 2020-10-27 15:46
Having the same issue.

**Comment by Gobot1234** [comment] 2020-10-27 15:50
Duplicate of #5867

Please see the documentation for intents which were introduced in 1.5 at https://discordpy.readthedocs.io/en/latest/intents.html

**Closed** 2020-10-28 04:19 UTC
Labels: duplicate, intents related
