### ISSUE TITLE
Cannot connect to host discordapp.com certificate verify failed

### ISSUE THREAD

**Issue by Sam2005xd** [Rapptz/discord.py#4169] opened 2020-06-01 23:14 UTC
I am getting this error when running my code, i have installed latest python and latest discord.py
Here is a pastebin of the error.

https://pastebin.com/45pSshsQ

**Comment by TheRealKeto** [comment] 2020-06-01 23:42
Refer to Issue https://github.com/Rapptz/discord.py/issues/4159

**Comment by IAmNotRyan** [comment] 2020-06-03 14:07
Windows:

Go to start, type internet explorer. Run as admin.
Go do https://discord.com click on the padlock icon.
Click view certificates
Click install certificates, choose either user or local machine.
Click Place all certificates in the following store
Choose Trusted Root Certification Authorities
Enjoy.

**Comment by bramnet** [comment] 2020-07-14 20:32
Just gonna drop this in here,
https://github.com/Rapptz/discord.py/issues/4159#issuecomment-640107584
fixed my problem in seconds.

**Comment by Richie-Moon** [comment] 2020-07-23 00:38
Duplicate of #4159

**Closed** 2020-07-25 14:02 UTC
Labels: duplicate
