### ISSUE TITLE
Is there audio receiver now? I didn't find any news about it

### ISSUE THREAD

**Issue by FrogX02** [Rapptz/discord.py#2568] opened 2020-02-14 16:49 UTC

**Comment by Harmon758** [comment] 2020-02-14 16:53
Duplicate of #444 and #1094

**Closed** 2020-02-14 16:53 UTC
Labels: duplicate

**Comment by FrogX02** [comment] 2020-02-14 16:59
These are old "issues", so that's why I asked again

**Comment by arkiven4** [comment] 2020-05-07 15:10
Agree

**Comment by Bebisty** [comment] 2020-05-12 12:27
Agree
