### ISSUE TITLE
Not working on Python 3.7

### ISSUE THREAD

**Issue by criyle** [Rapptz/discord.py#1565] opened 2018-09-08 13:57 UTC
It seems that the required version for aiohttp and websockets is too old to support python 3.7

**Comment by ItWasAllIntended** [comment] 2018-09-08 13:59
The async branch of Discord.py does not receive updates and will never support 3.7. The active rewrite branch has had this issue fixed. If you require 3.7, you will need to use this. For more information on the branch, join the official [Discord.py server](https://discord.gg/r3sSKJJ)

**Comment by Harmon758** [comment] 2018-09-08 18:27
Duplicate of #1249 and #1401

**Closed** 2018-09-24 11:37 UTC
Labels: duplicate
