### ISSUE TITLE
'Overwrites' got an unexpected keyword argument 'deny_new'

### ISSUE THREAD

**Issue by dovedevic** [Rapptz/discord.py#5142] opened 2020-07-22 00:08 UTC
### Summary

Not much of a summary perse, my bot was idling at the time of crash. Stack trace shown below:

```Traceback (most recent call last):
  File "/home/***/***/***/src/bot.py", line 1700, in <module>
    bot.run(creds)
  File "/home/***/.local/lib/python3.6/site-packages/discord/client.py", line 598, in run
    return future.result()
  File "/home/***/.local/lib/python3.6/site-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/home/***/.local/lib/python3.6/site-packages/discord/client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "/home/***/.local/lib/python3.6/site-packages/discord/client.py", line 457, in connect
    await self._connect()
  File "/home/***/.local/lib/python3.6/site-packages/discord/client.py", line 421, in _connect
    await self.ws.poll_event()
  File "/home/***/.local/lib/python3.6/site-packages/discord/gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "/home/***/.local/lib/python3.6/site-packages/discord/gateway.py", line 423, in received_message
    func(data)
  File "/home/***/.local/lib/python3.6/site-packages/discord/state.py", line 663, in parse_guild_create
    guild = self._get_create_guild(data)
  File "/home/***/.local/lib/python3.6/site-packages/discord/state.py", line 638, in _get_create_guild
    guild._from_data(data)
  File "/home/***/.local/lib/python3.6/site-packages/discord/guild.py", line 391, in _from_data
    self._sync(guild)
  File "/home/***/.local/lib/python3.6/site-packages/discord/guild.py", line 418, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "/home/***/.local/lib/python3.6/site-packages/discord/channel.py", line 107, in __init__
    self._update(guild, data)
  File "/home/***/.local/lib/python3.6/site-packages/discord/channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "/home/***/.local/lib/python3.6/site-packages/discord/abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
```

Seems to be similar to #5109?

### Reproduction Steps

Seems to be when a guild is created or during channel sync. Cannot repo as this seems to be dependent on some sort of internal state. Has only occurred for me once.

### Expected Results

For an error to not occur / fatally crash the bot.

### Actual Results

See stack trace above.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.6.9-final
- discord.py v1.2.5-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020

**Comment by Rapptz** [comment] 2020-07-22 00:10
Duplicate of #5109.

Update your library before opening an issue next time please.

**Closed by Rapptz** 2020-07-22 00:10 UTC
