### ISSUE TITLE
SSL Error [MAC]

### ISSUE THREAD

**Issue by eeelolmeisbol** [Rapptz/discord.py#5150] opened 2020-07-22 16:39 UTC
I keep on getting the error:
```
ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')]
```
I found some issues about it and how to fix it, but the problem is there was none actually working for mac. I've found only one thing that could help me but the only one was too outdated.
Can someone please help me on how to fix this bug or error? It would be greatly appreciated.
![Screenshot 2020-07-22 at 18 39 05](https://user-images.githubusercontent.com/65217369/88203799-a8cee900-cc4a-11ea-9c76-267d92d08bba.png)

**Comment by Phxntxm** [comment] 2020-07-22 16:40
Duplicate of #5100

**Comment by eeelolmeisbol** [comment] 2020-07-22 16:57
> Duplicate of #5100

Thanks

**Closed** 2020-07-22 19:22 UTC
