### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by ExpertsGaming** [Rapptz/discord.py#1702] opened 2018-11-01 17:43 UTC
`PS C:\Users\MrScamander1> & python c:/Users/MrScamander1/Desktop/bot.py
Traceback (most recent call last):
  File "c:/Users/MrScamander1/Desktop/bot.py", line 1, in <module>
    import discord
  File "C:\Users\MrScamander1\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\MrScamander1\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\MrScamander1\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\MrScamander1\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax`

**Comment by LucasCLuk** [comment] 2018-11-01 17:47
Duplicate of #1648, #1637, #1610, #1594, #1554, #1550, #1478, #1461, #1434, #1421, #1396, #1393, #1387, #1249, #1166,#1401 and #1690

**Comment by Skippern** [comment] 2018-11-04 19:12
Same with this?

```
Traceback (most recent call last):
  File "/home/skippern/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 848, in process_commands
    yield from command.invoke(ctx)
  File "/home/skippern/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 362, in invoke
    yield from self.prepare(ctx)
  File "/home/skippern/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 340, in prepare
    yield from self._parse_arguments(ctx)
  File "/home/skippern/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 299, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "/home/skippern/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 207, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.
```

Ubuntu 14.04, Python 3.5, discord.py 0.16.0

**Comment by Rapptz** [comment] 2018-11-04 19:13
@Skippern Unrelated.

**Comment by crrapi** [comment] 2018-11-04 19:13
@Skippern Don't forget to `pass_context=True` if you're on the async branch

**Closed** 2018-11-04 19:13 UTC
