### ISSUE TITLE
All Content and Embeds attributes missing

### ISSUE THREAD

**Issue by Jmarks199** [Rapptz/discord.py#6821] opened 2021-04-30 17:48 UTC
### Summary

Starting today, the content, clean_content, and embeds fields are all missing data. This was occurring on v 1.6 so I updated to v1.7 but the issue persists. I also tried it with two different tokens. Im not receiving the content from any messages from any channel.

### Reproduction Steps

Stop inside on_message() and observe the contents of the received message.

### Expected Results

Content is filled in.

### Actual Results

Content is blank

### Intents

None

### System Information

N/A

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I checked the discord api change notes but i don't see a release between yesterday and today.

**Comment by lgaan** [comment] 2021-04-30 17:51
This is potentially the same issue as #6820.

**Comment by TheRockettek** [comment] 2021-04-30 17:54
Hey there do you use bot=False

**Comment by Jmarks199** [comment] 2021-04-30 17:58
Yes, this is using bot=False

**Comment by lgaan** [comment] 2021-04-30 17:58
Then this is a duplicate of #6820, and subsequently is a nofix.

**Comment by Jmarks199** [comment] 2021-04-30 18:01
Can anyone speculate on a root cause analysis? What changed between yesterday and today? I need to fork and fix this, my application is down and for various reasons I need to be able to read messages from a channel I cannot place a bot account in.

**Comment by TheRockettek** [comment] 2021-04-30 18:04
Hey there, we did not make discord. I would recommend you ask discord why they stopped you selfbotting which is against tos. I recommend you do it on the official discord developers server at https://discord.gg/discord-developers

**Comment by sudosnok** [comment] 2021-04-30 18:05
Danny has already answered, https://github.com/Rapptz/discord.py/issues/6820#issuecomment-830181318, automating user accounts has been against the terms of service for a good while now

**Closed by sudosnok** 2021-04-30 18:05 UTC
Labels: duplicate, selfbot
