### ISSUE TITLE
on_shard_ready only fires if shard contains a large guild

### ISSUE THREAD

**Issue by KazWolfe** [Rapptz/discord.py#4108] opened 2020-05-18 01:07 UTC
### Summary

The `shard_ready` event is only dispatched if a specific shard has at least one large guild associated to it.

Per [L1098 in `state.py`](https://github.com/Rapptz/discord.py/blob/sharding-rework/discord/state.py#L1098), it appears that the `shard_ready` event only dispatches for shards that have at least one guild in `self._ready_state.guilds`.

`self._ready_state.guilds` is populated in [L1126](https://github.com/Rapptz/discord.py/blob/sharding-rework/discord/state.py#L1126) of the same file. However, this line is only run if the guild received in the ready data is considered a large guild.

Related to: #1427, #2541 

### Reproduction Steps

Any test code snippet (such as below) should work:
```
class TestBot(commands.AutoShardedBot):
    def __init__(self):
        print(f"ver {discord.__version__}")
        super().__init__(shard_count=4, command_prefix="!")

    async def on_ready(self):
        print(f"on_ready")

    async def on_shard_ready(self, shard_id):
        print(f"on_shard_ready({shard_id})")
```

Joining this bot to a small guild only (under 250 users) will result in only `on_ready` being printed to console.

### Expected Results

Each shard, regardless of the guilds on the shard (or if that shard even _has_ guilds) should publish a `shard_ready` event after the shard receives and parses the `READY` message.

### Actual Results

Only shards that have a member guild with `Guild#large` set will report `on_shard_ready`.

Both `on_ready` and `on_shard_ready` for the specified guild are only fired once.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

```
- Python v3.7.7-final
- discord.py v1.4.0-alpha
    - discord.py pkg_resources: v1.4.0a2325+g752081a
- aiohttp v3.6.2
- websockets v8.1
- system info: Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
```

Note: On `sharding-rework` branch.

**Comment by KazWolfe** [comment] 2020-05-18 01:55
Replacing L1088-L1098 with the following snippet appears to at least _work_ (all shards actually do report ready), but I'm not sure if there are any side effects.

```
for shard_id in self.shard_ids:
            for sub_guilds_info in itertools.filterfalse(lambda g: g[0].shard_id != shard_id, guilds):
                sub_guilds, sub_available = zip(*sub_guilds_info)
                if self._fetch_offline:
                    await self.request_offline_members(sub_guilds, shard_id=shard_id)

                for guild, unavailable in zip(sub_guilds, sub_available):
                    if unavailable is False:
                        self.dispatch('guild_available', guild)
                    else:
                        self.dispatch('guild_join', guild)

            self.dispatch('shard_ready', shard_id)
```

I can open a PR if this should be investigated further.

**Comment by Rapptz** [comment] 2020-05-24 02:40
This issue is because the ready state only contains large guilds (this is mainly by design). We don't want to chunk guilds that aren't large since it's a pointless operation (in the current code anyway...). I'm not sure of the way to fix it, but this isn't the way to go. For example if only one shard goes down then the entire cluster is going to get dispatched rather than the one that disconnected.

**Comment by Rapptz** [comment] 2021-02-18 05:26
This should be fixed now, feel free to open a new issue if it isn't.

**Closed by Rapptz** 2021-02-18 05:26 UTC
