### ISSUE TITLE
`guild.vanity_invite()` raises error even with correct permissions

### ISSUE THREAD

**Issue by scrazzz** [Rapptz/discord.py#7103] opened 2021-06-24 15:40 UTC
### Summary

`guild.vanity_invite()` raises error even when the bot has admin perms.

### Reproduction Steps

I made a command that returns the guild's vanity invite.

### Minimal Reproducible Code

```python
@bot.command()
async def foo(ctx):
    print(True if ctx.guild.me.guild_permissions.administrator else False)
    inv = await ctx.guild.vanity_invite()
    await ctx.send(inv)
```

### Expected Results

I expected it to not error.

### Actual Results

It errors. This is the output of the command below.
```py
True
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 46, in foo
    inv = await ctx.guild.vanity_invite()
  File "/python3/lib/python3.8/site-packages/discord/guild.py", line 2078, in vanity_invite
    payload = await self._state.http.get_vanity_code(self.id)
  File "/python3/lib/python3.8/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 82, in on_command_error
    raise error
  File "/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

### Intents

all

### System Information

- Python v3.8.10-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

N/A

**Comment by AbstractUmbra** [comment] 2021-06-24 15:48
What is the output of [`Guild.features`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=vanity#discord.Guild.features) for this specific guild?

If it does not have the feature for VANITY, this will raise a 403 error.

**Comment by scrazzz** [comment] 2021-06-24 16:07
Right. I was checking this in my private server so that's probably why.

I opened this issue because a member had this same issue where they couldn't get the guild vanity even with proper perms. And this is the error they got.

```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/daishiky/Ami/cogs/utility.py", line 74, in topguilds
    em = discord.Embed(title=f"{guild.name} (`{guild.id}`)", description=f"The guild owner is `{guild.owner}`\n{desc}\n\n<a:Casual_Crowe:853894751140446248> Members : {guild.member_count}\n<a:Casual_Crowe:853894751140446248> Emojis : {len(guild.emojis)}\n<a:Casual_Crowe:853894751140446248> Boosts & Tier : {guild.premium_subscription_count} / {guild.premium_tier}\n<a:Casual_Crowe:853894751140446248> Vanity URL : {vanity}\n<a:Casual_Crowe:853894751140446248> Text & Voice : <:text:843198832464625714> {len(guild.text_channels)} | <:voice:585783907673440266> {len(guild.voice_channels)}", color = 0xffcff1)
  File "/usr/local/lib/python3.9/site-packages/discord/invite.py", line 357, in __str__
    return self.url
  File "/usr/local/lib/python3.9/site-packages/discord/invite.py", line 375, in url
    return self.BASE + '/' + self.code
TypeError: can only concatenate str (not "NoneType") to str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/daishiky/Ami/jishaku/features/invocation.py", line 123, in jsk_debug
    await alt_ctx.command.invoke(alt_ctx)
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: can only concatenate str (not "NoneType") to str 
```
- Their bot has `manage_guild` perms.
- The server has `VANITY_URL` in guild.features.
- They are using discord.py 1.7.3

**Comment by AbstractUmbra** [comment] 2021-06-24 16:19
I have tested this with a 1.7.3 bot with administrator permissions in a guild with vanity.
![DiscordCanary_2021-06-24_17-17-45](https://user-images.githubusercontent.com/16031716/123298181-26ad0b80-d510-11eb-8507-4228e2608d3d.png)

In short I have no reproduction of this bug. Is there more context I am missing?

Generally - communicating on behalf of someone is not wise, there will be information gaps.

**Comment by Phxntxm** [comment] 2021-06-24 16:28
Since d.py hard [accesses the code](https://github.com/Rapptz/discord.py/blob/v1.7.3/discord/guild.py#L2082)

This means the code HAS to be provided, or else this would error on this line instead, apparently according to this screenshot you can request a `None` code... so this would not error if discord was returning `code: None` in the data for this method. This is what it seems to be from what I can see, a discord bug where it's returning None for the code somehow

![image](https://user-images.githubusercontent.com/3664828/123299424-fa6c9d00-d4c5-11eb-94b4-8f86856f6322.png)

**Closed** 2021-06-28 05:09 UTC
Labels: bug
