### ISSUE TITLE
Cannot use subcommand in different cog

### ISSUE THREAD

**Issue by thec0sm0s** [Rapptz/discord.py#1816] opened 2019-01-03 16:24 UTC
Is there any way I can define a subcommand of a `command.group()` present in another cog different from that of subcommand, something like,
```python
# cog1.py

class Test1:

    def __init__(self, bot):
        self.bot = bot

    @commands.group()
    async def foo(self, ctx):
        pass



# cog2.py

from cog1.Test1 import foo

class Test2:

    def __init__(self, bot):
        self.bot = bot

    @foo.command()
    async def baz(self, ctx):
        pass
```

**Comment by deepakraj-tc** [comment] 2019-01-03 17:23
Actually I want to split certain commands into two separate cogs. I have main command group: `guild` and wanna make subcommands for same. Put commands like `;guild info`, `;guild roles`, `;guild stats` and similar commands in one cog and other management commands like `;guild prefix set` `;guild mods set`, `;guild mute channel`, etc.
This would explicitly separate different commands on basis of their purpose and make code more readable. I know its not very much needed but yes may increase readability.

**Comment by Vexs** [comment] 2019-01-04 03:40
Its really not a great idea to do this for a number of reasons- you're now requiring cogs be loaded in a specific order, hotloading is probably right out, and overall the difficulty of writing good code increases. I'd seriously recommend against it. 

However if you really want to do this which you should very much not do as its going to result in nastier code all around, you can manually fetch the command and add command objects to it with `bot.get_command` and `command.add_command`. You'll want to look at how thats implemented and used in the library already. 

But again, don't do this.

**Comment by Rapptz** [comment] 2019-03-01 03:40
Duplicate of https://github.com/Rapptz/discord.py/issues/1942

**Closed by Rapptz** 2019-03-01 03:40 UTC
