### ISSUE TITLE
Pwease help me, Im on a macbook air m1 2020 and it keeps not working :( 

### ISSUE THREAD

**Issue by Prosleo** [Rapptz/discord.py#9631] opened 2023-10-26 17:18 UTC
### Summary

bunch of errors. I have tried diffrent intepreters in pycharm and visual studio code. (3.9, 3.10, 3.11, 3.12)

### Reproduction Steps

runs this (My code) with 3.11 python. with discord.py installed:
from discord import Intents, File
from discord.ext import commands
from random import randint, choice
from os import listdir
from credits import TOKEN

bot = commands.Bot(command_prefix="!", intents=Intents.all())

@bot.command("loot_box")
async def loot_box(ctx):
    random_number = randint(1, 100)
    if random_number < 80:
        directory_path = "img_common"
        comment = "Common prize"
    elif random_number < 95:
        directory_path = "img_rare"
        comment = "RARE prize, lucky you"
    else:
        directory_path = "img_super_rare"
        comment = "SUPER RARE, OMG YOU ARE SUPER LUCKY SO MUCH RESELL VALUE"

    img_path = choice(listdir(directory_path))

    await ctx.channel.send(comment, file=File(directory_path + "/" + img_path))

bot.run(TOKEN)

### Minimal Reproducible Code

```python
from discord import Intents, File
from discord.ext import commands
from random import randint, choice
from os import listdir
from credits import TOKEN

bot = commands.Bot(command_prefix="!", intents=Intents.all())


@bot.command("loot_box")
async def loot_box(ctx):
    random_number = randint(1, 100)
    if random_number < 80:
        directory_path = "img_common"
        comment = "Common prize"
    elif random_number < 95:
        directory_path = "img_rare"
        comment = "RARE prize, lucky you"
    else:
        directory_path = "img_super_rare"
        comment = "SUPER RARE, OMG YOU ARE SUPER LUCKY SO MUCH RESELL VALUE"

    img_path = choice(listdir(directory_path))

    await ctx.channel.send(comment, file=File(directory_path + "/" + img_path))


bot.run(TOKEN)
```

### Expected Results

it to work

### Actual Results

[2023-10-26 20:03:44] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leokp/Desktop/Docs For SCHOOL/Dbot LB/main.py", line 28, in <module>
    bot.run(TOKEN)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 612, in login
    data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/http.py", line 803, in static_login
    data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/http.py", line 625, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 562, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]

Process finished with exit code 1

### Intents

whats that

### System Information

Python 3.11
2.3.2
macbook air m1 2020

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by No767** [comment] 2023-10-26 17:24
See `?tag ssl` on the dpy server

Content of that tag posted here:

> Getting `[SSL: CERTIFICATE_VERIFY_FAILED]` on Python 3 on OS X?
Navigate to your `Applications/Python 3.X/` folder and double click the `Install Certificates.command` to fix this.
Happy coding!

**Comment by Rapptz** [comment] 2023-10-26 20:39
Duplicate of https://github.com/Rapptz/discord.py/issues/423#issuecomment-272093801

**Closed by Rapptz** 2023-10-26 20:39 UTC
Labels: unconfirmed bug
