### ISSUE TITLE
Commit 862d509d2e39f9d550ec3dff1e7d08fc6b3b5b8d breaks if strip_after_prefix does not exist

### ISSUE THREAD

**Issue by JamesZoft** [Rapptz/discord.py#6612] opened 2021-04-02 17:27 UTC
### Summary

When requiring discord.py/master and trying to use the get_context, it errors because strip_after_prefix doesn't exist

### Reproduction Steps

Use self.bot.get_context(message)

### Minimal Reproducible Code

```python
self.bot.get_context(message)
```

### Expected Results

It would return without an error

### Actual Results

[Cluster 1] Traceback (most recent call last):
[Cluster 1]   File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 343, in _run_event
[Cluster 1]     await coro(*args, **kwargs)
[Cluster 1]   File "/modmail/modmail/cogs/events.py", line 129, in on_message
[Cluster 1]     ctx = await self.bot.get_context(message)
[Cluster 1]   File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py", line 915, in get_context
[Cluster 1]     if self.strip_after_prefix:
[Cluster 1] AttributeError: 'ModMail' object has no attribute 'strip_after_prefix'

### Intents

32767

### System Information

- Python v3.8.5-final
- discord.py v1.7.0-alpha
    - discord.py pkg_resources: v1.7.0a2836+g6524869
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-48-generic #52 SMP Sat Sep 26 08:27:15 UTC 2020

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

**Comment by Rapptz** [comment] 2021-04-02 17:31
Did you forget to call `super()` inside `__init__`?

**Comment by Rapptz** [comment] 2021-04-03 00:14
I couldn't reproduce this with or without the option so I'm closing this.

**Closed by Rapptz** 2021-04-03 00:14 UTC
Labels: no repro

**Comment by JamesZoft** [comment] 2021-04-03 00:25
Hi, I’m not sure, sorry. It’s a problem I’m having whilst trying to run the latest version of modmail https://github.com/chamburr/modmail and send the ‘=help’ command - modmail depends on discord.py@master. If I revert to before the commit I’ve specified the problem goes away.

**Comment by Rapptz** [comment] 2021-04-03 00:28
Whoever wrote that bot decided that [writing all the attributes by hand](https://github.com/chamburr/modmail/blob/651d15fa714aa198b11b9ec2768c2d9713217976/classes/bot.py) was a good idea. So whenever the library updates, the code used in the bot will break which is what happened here. Unfortunately this is not an issue with the library but with the bot itself. You're better off opening an issue there -- and hopefully get them to avoid all the duplication of library code since it's fragile.

**Comment by JamesZoft** [comment] 2021-04-03 00:31
I see, I’ll pass it on, thanks!

**Comment by chamburr** [comment] 2021-04-03 00:40
Developer of the mentioned bot here. Since my bot does not use the built-in gateway, and neither does it use the built-in state cache, patching the methods is the best option for me.
