### ISSUE TITLE
SSLCertVerificationError: certificate has expired

### ISSUE THREAD

**Issue by TDmig** [Rapptz/discord.py#4159] opened 2020-05-30 18:09 UTC
**Today suddenly my bot can't be launched from Windows. As I see this problem is not in my code completely so I messaging here and to Discord Support.**

```
Traceback (most recent call last):
  File "...\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "...\lib\asyncio\base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "...\lib\asyncio\base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "...\lib\asyncio\sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "...\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "...\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  ...
  File "...", line 46, in main
    client.run(t)
  File "...\lib\site-packages\discord\client.py", line 640, in run
    return future.result()
  File "...\lib\site-packages\discord\client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "...\lib\site-packages\discord\client.py", line 584, in start
    await self.login(*args, bot=bot)
  File "...\lib\site-packages\discord\client.py", line 442, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "...\lib\site-packages\discord\http.py", line 261, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "...\lib\site-packages\discord\http.py", line 165, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "...\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "...\lib\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "...\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "...\lib\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "...\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "..\lib\site-packages\aiohttp\connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "...\lib\site-packages\aiohttp\connector.py", line 938, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discordapp.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')]
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 8.1 6.3.9600

### About

Problem with certification probably on Discord side, _but_ discord.py still tries to access discordapp, so maybe it can be problem. Also I am looking for _solution_.

Also it is not only my issue. [here](https://stackoverflow.com/questions/62102897/certifacte-verify-failed-certificate-has-expired-ssl-c1108/62104752) is stackoverflow question about it.

**Comment by Rapptz** [comment] 2020-05-30 18:15
A root certificate expired today on the Windows chain. Chances are there'll be an update soon to fix it on Windows. 

https://crt.sh/?id=1

**Comment by Preocts** [comment] 2020-05-30 19:08
> A root certificate expired today on the Windows chain. Chances are there'll be an update soon to fix it on Windows.
> 
> https://crt.sh/?id=1

Windows users: 
If y'all are needing a faster solution you can visit "discord.com" in a web-browser, click the lock icon next to the URL in your nav bar, and click on the certificate.  Should be a "export to file" option and from there you just save it, double click it (if you are an admin), and install it to Windows.

**Comment by yunolawliet** [comment] 2020-05-30 21:20
Windows:
1. Go to start, type internet explorer. Run as admin.
2. Go do https://discord.com click on the padlock icon.
3. Click view certificates
4. Click install certificates, choose either user or local machine.
5. Click Place all certificates in the following store
6. Trusted Root Certification Authorities

**Comment by mikeshardmind** [comment] 2020-05-30 23:33
> Click Place all certificates in the following store
> Choose Trusted Root Certification Authorities

Please don't recommend for users to manually add certs not issued with the intention of being used as a root CA as a trustable entity to the trusted root CA store. This will appear to fix the connection issue but has massive security implications beyond that. The trusted root authorities should not be modified in this way.

**Comment by Jessuhs** [comment] 2020-05-31 01:22
I generally agree with the above, however I'd like to point out that Sectigo, the root Certificate Authority in this case, released 4 "modern" certificates that should be installed. You can find more information in their release about this expiration here: https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

In my case only 3 of the modern certs were installed and I was missing the **COMODO ECC Certification Authority** root cert. This just so happens to be the root of the cert issued by Cloudflare for Discord.com this morning. Per that link from Sectigo, I was able to obtain the certificate by going to https://crt.sh/?id=2835394. There is a small link on the left side of the page that says "Download Certificate: PEM". This is a site operated by Sectigo.

My guess is that either MS or Sectigo screwed up here and somehow this 1 of 4 certs did not get included into some kind of update. After installing this certificate I'm back up and running just fine.

**Comment by Richie-Moon** [comment] 2020-06-03 01:57
Has Windows released the update yet?

**Comment by Jessuhs** [comment] 2020-06-04 22:41
Per Microsoft this root certificate _should_ be included in Win10. Here's a page about the Microsoft Root Certificate Program: https://docs.microsoft.com/en-us/security/trusted-root/program-requirements

And here's a list of current participants (as of June 4th 2020): https://ccadb-public.secure.force.com/microsoft/IncludedCACertificateReportForMSFT

Note the inclusion of the certificate I was missing above with a Ctrl-F of "COMODO ECC Certification Authority". I'm not sure if this was just added or has been in Win10 for a while. I was certainly missing it.

**Comment by TheLiche-Seregon** [comment] 2020-06-06 11:09
Hello, I've got the same issue, i tried everything but nothing has worked. I finally solved it; I've removed old certificates and reloaded the bot. https://www.thesslstore.com/blog/how-to-remove-a-root-certificate/. If it can help someone...

**Comment by Russian-Dev** [comment] 2020-06-06 19:07
Where do I save the certs?

**Comment by Russian-Dev** [comment] 2020-06-06 19:13
I also found the old certificate that i'm pretty sure is causing the problem. "AddTrust External CA Root" What do I do with it?

**Comment by AbstractUmbra** [comment] 2020-06-06 19:31
The method that has had success in the [help channels](https://discord.gg/dpy) is the following:

Download the required certificate manually: https://crt.sh/?id=2835394
The above link is provided by Sectigo.
[This](https://beans-took-my-kids.reeee.ee/38qB2n.png) is where the actual download button is.

Once it has downloaded, double click it to install it. I believe installing it to the local computer and not the running user is the correct way to proceed, correct me if I am wrong there.

**Comment by furkanu** [comment] 2020-06-07 20:27
> The method that has had success in the [help channels](https://discord.gg/dpy) is the following:
> 
> Download the required certificate manually: https://crt.sh/?id=2835394
> The above link is provided by Sectigo.
> [This](https://beans-took-my-kids.reeee.ee/38qB2n.png) is where the actual download button is.
> 
> Once it has downloaded, double click it to install it. I believe installing it to the local computer and not the running user is the correct way to proceed, correct me if I am wrong there.

So, is it safe to apply this?
no security implications as @mikeshardmind mentioned?

**Comment by AbstractUmbra** [comment] 2020-06-07 20:32
The certificate above comes from Sectigo themselves. You can run your own analysis of it if you like prior to installing. I can confirm this has fixed the issue for many users and afaik Windows has still not released an update to update their trust store.

**Comment by mikeshardmind** [comment] 2020-06-07 20:57
> no security implications as @mikeshardmind mentioned?

The security implications I mentioned were for just adding all the certs showing on a page as someone before me had suggested. There are still other security implications to adding the cert, but these are implications of trust. There is a potential break in a chain of trust here, use at your own risk as an informed decision. I can say that the cert as I saw on my machine was fine, but it is possible for a compromise to happen in delivering that, so *verify*. The other reason which I would not endorse one of these methods publicly on an issue like this is that most of the people with the issue will not verify, and just run something to fix it.

**Comment by Lutrome** [comment] 2020-06-14 00:23
@mikeshardmind So what do you suggest we do? I'd rather not introduce this kind of potential security breach, but I'd also like to get my bot up ASAP.

**Comment by TheLiche-Seregon** [comment] 2020-06-14 10:36
I can suggest you to remove all your old certificates (especially the one that discordapp.com uses [https://crt.sh/?id=1]) and try again... However i don't know if it makes security breach...

**Comment by AbstractUmbra** [comment] 2020-06-14 10:49
There is no security implications if you use the specific [certificate](https://crt.sh/?id=2835394) I linked earlier in this thread. Some common sense applies that you should not install anything you don't need / won't use, meaning just that one certificate should suffice. 
Again as I stated before, this is from Sectigo themselves, so if/when Windows releases their Trust Store update, it's just going to download this exact certificate anyway.

As for the status on the pending update Windows still has to issue: no sign of it yet.

**Comment by metiuu** [comment] 2020-06-18 07:51
Hi,
I'm also having this issue. I tried to fix it by following the instructions here, but no luck so far. This is a wild guess, but is it possibly because Discord recently moved domains from discordapp.com to discord.com?

If that's the case, how do we alter the script so that our code connects to discord.com? I apologize if my question is stupid as I'm a student learning this on my own. Thank you!

**Comment by TheLiche-Seregon** [comment] 2020-06-18 08:13
The problem isn't that; it is because the certificate has expired... Did you try downloading the new certificate or removing the old one and going on discordapp.com on internet explorer?

**Comment by AbstractUmbra** [comment] 2020-06-18 08:39
Did you _install_ the certificate to 'local computer' after downloading it?

I believe there's a link further up with the 'why it happened'.

**Comment by metiuu** [comment] 2020-06-18 09:59
> The problem isn't this; it is because the certificate has expired... Did you try downloading the new certificate or removing the old one and going on discordapp.com on internet explorer?

Hi, it was my error. I installed the cert manually on the user and not the local machine. The issue is solved now and I can continue working on my self-study project. Sorry for the inconveniencec and stupid question.

**Comment by kazuichisouda** [comment] 2020-06-21 00:44
Uh, i've also been experiencing this problem, but the links provided don't seem to load and Internet Explorer doesn't work on my computer. If I try and run it, it's just all white and then crashes.

**Comment by Rapptz** [comment] 2020-06-27 06:47
I believe the core issue is based off of OpenSSL versions being distributed with Python which is why only a minority of people have this issue. If OpenSSL is above 1.1.0 then this *should not* be happening. However I'm unsure how OpenSSL versions are bundled on Windows distributions to cause such discrepancies. For now, I'll close this issue since there are numerous workarounds provided.

**Closed by Rapptz** 2020-06-27 06:47 UTC

**Comment by sinkaroid** [comment] 2020-07-05 23:44
just install ssl valid from discord.com

**Comment by Richie-Moon** [comment] 2020-07-06 06:32
> just install ssl valid from discord.com

That opens the up the security implications mentioned above

**Comment by azriel423** [comment] 2020-07-14 14:58
Hej,
has someone here has experiences with this problem under macOS? It seems the workaround with the manually installed certificate doesn't work. Has someone any advice for me?

**Comment by Calabree** [comment] 2020-07-22 21:55
is there any fix for this on Mac?

**Comment by bnwlkr** [comment] 2020-09-12 04:48
Also looking for a solution to this on mac. Any help much appreciated

**Comment by numbermaniac** [comment] 2020-09-12 05:04
Is the error on Mac that the certificate *expired*, or that it's just missing? If it's the latter then https://github.com/Rapptz/discord.py/issues/423#issuecomment-272093801 might solve your issue.

**Comment by bnwlkr** [comment] 2020-09-12 05:27
It was that it was missing and #423 solved it. Beauty

**Comment by Wingfooted** [comment] 2020-09-29 10:26
I am having a similar problem, it is not the #423 one, but this one. I don't see a fix for Mac and all the advice so far is for windows. Any help? 

Thanks in advance.

**Comment by bijij** [comment] 2020-09-29 10:31
> I am having a similar problem, it is not the #423 one, but this one. I don't see a fix for Mac and all the advice so far is for windows. Any help?

If you're on macOS you'll want to go into the python 3.x folder in your Applications and double click `Install Certificates.command`

**Comment by ArnavNinja** [comment] 2020-10-14 17:53
> Windows:
> 
> 1. Go to start, type internet explorer. Run as admin.
> 2. Go do https://discord.com click on the padlock icon.
> 3. Click view certificates
> 4. Click install certificates, choose either user or local machine.
> 5. Click Place all certificates in the following store
> 6. Choose Trusted Root Certification Authorities
> 7. Enjoy.

It still didn't work, does anyone know why?

**Comment by Kle0s** [comment] 2020-10-16 07:00
After all this time, and after reading the whole thread, I still noticed the problem was not fixed.

**Comment by Kle0s** [comment] 2020-10-16 07:03
> > Windows:
> > 
> > 1. Go to start, type internet explorer. Run as admin.
> > 2. Go do https://discord.com click on the padlock icon.
> > 3. Click view certificates
> > 4. Click install certificates, choose either user or local machine.
> > 5. Click Place all certificates in the following store
> > 6. Choose Trusted Root Certification Authorities
> > 7. Enjoy.
> 
> It still didn't work, does anyone know why?

From what I've seen, the problem of the certificate was fixed (I noticed the expiry date is now 27/11/2020), so even that the symptom of the problem looks the same, I think it might be something else.

**Comment by Kle0s** [comment] 2020-10-16 07:27
> > Windows:
> > 
> > 1. Go to start, type internet explorer. Run as admin.
> > 2. Go do https://discord.com click on the padlock icon.
> > 3. Click view certificates
> > 4. Click install certificates, choose either user or local machine.
> > 5. Click Place all certificates in the following store
> > 6. Choose Trusted Root Certification Authorities
> > 7. Enjoy.
> 
> It still didn't work, does anyone know why?

After working on it for a few hours, here's what i came up with:
1. go to this link: https://crt.sh/?id=2835394&opt=cablint,zlint
2. click on the PEM (next to download certificate).
3. install the certificate (I did it for current user, but you might as well do it for local machine)

This fixed it for me, hope it will help everyone still looking for a solution :)

**Comment by flowl** [comment] 2020-10-18 14:09
I am pretty sure this all is due to misconfiguration of the infrastructure on discord side (intermediate certificate not always present in the chain or something like that), because even the discord app itself is throwing certificate errors every day which are resolved after restarting discord.

**Comment by lettow-humain** [comment] 2020-10-22 08:41
I have this issue on Ubuntu Server.

```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord_bot_3.6.py", line 1238, in <module>
    bot.run(TOKEN)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/client.py", line 708, in run
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/client.py", line 687, in runner
    await self.start(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/client.py", line 650, in start
    await self.login(*args, bot=bot)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/client.py", line 499, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/http.py", line 291, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 938, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
```

Is there a way to solve it? I've looked through the previews comments but haven't found anything useful. Thanks!

**Comment by gogurtenjoyer** [comment] 2020-10-22 08:50
Hi,
Your posted traceback is actually from MacOS, not Ubuntu Server ... in addition, your error is not the same as that of this (closed) issue. On MacOS, you'll find a script called 'Install Certificates.command' in your Python folder in Applications - have you run this?

**Comment by cedrick7** [comment] 2020-11-14 15:08
If you're using macOS go to Macintosh HD > Applications > Python3.X folder (X = whatever version of python you're using) > double click on "Install Certificates.command" and the issue went away!

**Comment by Akanate** [comment] 2020-11-21 19:51
Im using ubuntu and im getting this exact error this install script that everyone keeps mentioning doesnt work at all for me any help would be massively appreciated.

**Comment by MIvanchev** [comment] 2020-12-03 22:26
Here is a solution which doesn't compromise the security of the entire system, but is of course a TOTAL HACK and I hereby inform you that you alone bear the full responsibility for any damage that occurs from using it. It basically tells your bot to not use the certificates known to your OS but instead others which you download manually.

1. You'll need to modify the source of the discord.py module so I recommend to install it in the virtual environment of your bot (through pipenv) so your main Python installation is unaffected.

2. Open the [http.py](https://github.com/Rapptz/discord.py/blob/master/discord/http.py) file of the module, find the lines:

https://github.com/Rapptz/discord.py/blob/master/discord/http.py#L132
https://github.com/Rapptz/discord.py/blob/master/discord/http.py#L185

3. Open https://discord.com/ in Firefox, Chrome or whatever other browser. Download the whole certificate chain (PEM file). It's important that you get the whole chain. You can also use curl.

4. Add `import ssl` to the beginning of the file.

5. Prepend the following block to **each** of the above source lines:

```
context = ssl.SSLContext(ssl.PROTOCOL_TLS)
context.verify_mode = ssl.CERT_REQUIRED
context.load_verify_locations('<full path to the downloaded PEM file>')
```

6. If the chain is not enough, you can download the whole CRT file of Firefox (https://curl.se/docs/caextract.html) and try that instead of the PEM file.

7. Run your bot.

**Comment by CSAapps** [comment] 2021-01-06 06:41
https://stackoverflow.com/a/62104752/13396193 this method solved my problem

**Comment by flowl** [comment] 2021-01-06 17:28
The certificate problems appeared only temporary to me and should be resolved by a long time.
If you have a normal windows, linux or macos system with UPDATES enabled, this problem should no longer appear to you.
Instead of hacking into the discord client or manually installing certificates, properly update your core system and you have no problems with certificates.

**Comment by XxMicrowavexX** [comment] 2021-03-30 03:12
> https://stackoverflow.com/a/62104752/13396193 this method solved my problem

is there a macos version

also the Install certificate.command has no impact on the system

**Comment by 7fail** [comment] 2021-03-30 18:41
> Windows:
> 
> 1. Go to start, type internet explorer. Run as admin.
> 2. Go do https://discord.com click on the padlock icon.
> 3. Click view certificates
> 4. Click install certificates, choose either user or local machine.
> 5. Click Place all certificates in the following store
> 6. Choose Trusted Root Certification Authorities
> 7. Enjoy.

how does this work on Mac?

**Comment by SebbyLaw** [comment] 2021-03-30 19:12
Please stop necrobumping this issue.

If your issue is the same as the one outlined above: `Cannot connect to host discordapp.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')]` the solutions have already been posted in this thread.

Windows: https://github.com/Rapptz/discord.py/issues/4159#issuecomment-640107584
Mac: https://github.com/Rapptz/discord.py/issues/4159#issuecomment-700615568

**Comment by XxMicrowavexX** [comment] 2021-03-31 03:04
`Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL:CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')]`
this is my error

**Comment by XxMicrowavexX** [comment] 2021-03-31 03:28
> > https://stackoverflow.com/a/62104752/13396193 this method solved my problem
> 
> is there a macos version
> 
> also the Install certificate.command has no impact on the system

sorry i meant INstall certificate gives me an error

**Comment by issuesindiscord** [comment] 2021-04-17 17:09
Running into the same issues in Lubuntu 20. 
Lsb_release Ubuntu 20.10.
OpenSSL 1.1.1k.
Python 3.8.6

`[time_left_reminder] Waiting for the bot to start...
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "roulette.py", line 247, in <module>
    bot.run(token)
  File "/home/user/.local/lib/python3.8/site-packages/discord/client.py", line 708, in run
    return future.result()
  File "/home/user/.local/lib/python3.8/site-packages/discord/client.py", line 687, in runner
    await self.start(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/discord/client.py", line 650, in start
    await self.login(*args, bot=bot)
  File "/home/user/.local/lib/python3.8/site-packages/discord/client.py", line 499, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "/home/user/.local/lib/python3.8/site-packages/discord/http.py", line 291, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/user/.local/lib/python3.8/site-packages/discord/http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/user/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/user/.local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(                                                                                                                                                    
  File "/home/user/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect                                                                                            
    proto = await self._create_connection(req, traces, timeout)                                                                                                                              
  File "/home/user/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection                                                                                 
    _, proto = await self._create_direct_connection(                                                                                                                                         
  File "/home/user/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection                                                                         
    raise last_exc                                                                                                                                                                           
  File "/home/user/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/user/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 938, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')]
`

Unknown what to do.

`openssl s_client -showcerts -connect discordapp.com:443` shows `Verification error: unable to get local issuer certificate` after showing the certificates. Thank you for any help.

**Comment by flowl** [comment] 2021-04-19 09:30
It doesn't make sense having to download a public key/cert that is already in every keystore. When the certificate is expired, Discord officials need to renew or get rid of the outdated cert. I am unsubscribing to this thread as there are no new questions or answers other than from people with badly configured computers.
