### ISSUE TITLE
logs_from returns every message 50 times

### ISSUE THREAD

**Issue by Jeanolos** [Rapptz/discord.py#527] opened 2017-04-05 21:33 UTC
If you try to use the logs_from generator, the generator contains every message 50 times.

Example:
```py
ts = message.timestamp
d = datetime.timedelta(days=1)
t = ts - d
messages = yield from client.logs_from(channel, limit=5000, before=ts, after=t) #after fetching, contains every message 50 times
for m in messages:
    print(m)
```
returns (if only 1 message had been sent in a span of 1 day)
```
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
Message 1
```

**Comment by Rapptz** [comment] 2017-04-05 21:35
This is a duplicate of #280. I suggest switching to Python 3.5 or higher to get the better version with async iterables.

This bug is fixed in the rewrite by merging the code base of the async iterable and making Python 3.4 use it as well. However as it stands this bug will not be fixed pre-1.0.

**Closed** 2017-05-21 05:11 UTC
Labels: bug, duplicate
