### ISSUE TITLE
 guild.get_member(userid) returns None

### ISSUE THREAD

**Issue by simonsruggi** [Rapptz/discord.py#5889] opened 2020-10-04 15:57 UTC
## Summary

Hello, I have been using this repository for more than a year without any issues, but now I got an error in the get_member function.

## Reproduction Steps

guild = client.get_guild(GUILDID)
    
author = guild.get_member(ctx.author.id)

The author is None, even if the sender is in the discord server. I never had this issue before.

## Expected Results

Author info, in order to add roles, remove roles

## Actual Results

None

## Checklist

- [ ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.
- [ ] I have provided the intents that my bot is using.

**Comment by Gobot1234** [comment] 2020-10-04 16:05
Duplicate of #5867

**Closed** 2020-10-04 20:18 UTC
Labels: bug
