### ISSUE TITLE
client.get_all_members returns only its own self

### ISSUE THREAD

**Issue by danielthetam** [Rapptz/discord.py#5959] opened 2020-10-23 06:32 UTC
**CODE**
```
def add_all_users_to_db():
    for member in client.get_all_members():
        print(member.name, member.id)
```
**OUTPUT**
`KnightsRPG 742218608230269060
`
For some reason my bot is returning its own name and id, and it does it three times. Is this a bug?

**Comment by Rapptz** [comment] 2020-10-23 06:37
Next time you open an issue please do not delete the template. It's there for a reason.

This is a duplicate of https://github.com/Rapptz/discord.py/issues/5867 and the [documentation here](https://discordpy.readthedocs.io/en/latest/intents.html#where-d-my-members-go)

**Closed by Rapptz** 2020-10-23 06:37 UTC
Labels: intents related

**Comment by danielthetam** [comment] 2020-10-23 06:59
I see, sorry man. Thanks for letting me know
