### ISSUE TITLE
permissions_in and permissions_for cannot be used with discord.ext.commands.Bot object

### ISSUE THREAD

**Issue by nmarotte** [Rapptz/discord.py#6370] opened 2021-02-01 15:39 UTC
## Summary

When trying to resolve the permission for a discord.ext.commands.**Bot** object, we cannot use the correct way, that is permissions_in or permissions_for (works fine when using guild_permissions ) [as recommended by the documentation](https://discordpy.readthedocs.io/en/latest/api.html?highlight=guild_permissions#discord.Member.guild_permissions)

Calling permissions_for with the Bot object byitself, counting on BotBase and discord.Client class, as parameter, our object gets asked for the attribute id, that only exists under the user attribute of Bot
So we are tempted to call permission_for with the Bot.user object, that is a discord.ClientUser, our object gets for the attribute _roles that is _probably_ (didn't find much information about that) present in Bot object, but not it's user

## Reproduction Steps

Here's a simple code to test the problem, simply replace "A bot token" by a bot token to try it on a test server. We can see that we cannot call permissions_for or permissions_in with a Bot object
```Python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix="//", intents=discord.Intents.all())

bot_token = "A bot token"


@bot.event
async def on_ready():
    print("Ready!")


@bot.event
async def on_message(message: discord.Message):
    print("message sent")
    try:
        if message.channel.permissions_for(bot.user).manage_channels:
            print("Verification worked !")
        else:
            print("bot does not have the access")
    except AttributeError as e:
        print(e)
        try:
            if message.channel.permissions_for(bot).manage_channels:
                print("Verification worked !")
            else:
                print("bot does not have the access")
        except AttributeError as e:
            print(e)

            print("We can see that both exceptions arose, now let's see with permissions_in\n")

            try:
                if bot.user.permissions_in(message.channel).manage_channels:
                    print("Verification worked !")
                else:
                    print("bot does not have the permission")
            except AttributeError as e:
                print(e)
                try:
                    # This doesn't work for different reasons, bot is discord.Client but permissions_in is in discord.ClientUser
                    if bot.permissions_in(message.channel).manage_channels:
                        print("Verification worked !")
                    else:
                        print("bot does not have the permission")
                except AttributeError as e:
                    print(e)

                    print("All the exceptions occured")


if __name__ == '__main__':
    bot.run(bot_token)
```

## Expected Results

I think the id attribute of Bot should be found when calling for the id of a Bot object, by traversing the user attribute
There should be a correct way to resolve permission that is 100% accurate for a bot, since it is possible to do it for a member of a discord server

## Actual Results

For **permissions_for**

When using the object ClientUser of the Bot object via [.user](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Bot.user) method we get : 

> Traceback (most recent call last):
>   File "C:\Users\natha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_slash\client.py", line 704, in handle_subcommand
>     await selected.invoke(ctx, *args)
>   File "C:\Users\natha\PycharmProjects\TalyaBot\Cogs\AutoVoiceChannel.py", line 33, in _set_copy_channel
>     if channel.permissions_for(self.bot.user).manage_channels and \
>   File "C:\Users\natha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\channel.py", line 655, in permissions_for
>     base = super().permissions_for(member)
>   File "C:\Users\natha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\abc.py", line 486, in permissions_for
>     roles = member._roles
> AttributeError: 'ClientUser' object has no attribute '_roles'

 since the role attribute belongs to Member (if i'm correct, didn't find much information about that)

But if using directly the Bot (therefore using it's base class BotBase and discord.Client), we get 

> Traceback (most recent call last):
>   File "C:\Users\natha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_slash\client.py", line 704, in handle_subcommand
>     await selected.invoke(ctx, *args)
>   File "C:\Users\natha\PycharmProjects\TalyaBot\Cogs\AutoVoiceChannel.py", line 33, in _set_copy_channel
>     if channel.permissions_for(self.bot).manage_channels and \
>   File "C:\Users\natha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\channel.py", line 655, in permissions_for
>     base = super().permissions_for(member)
>   File "C:\Users\natha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\abc.py", line 481, in permissions_for
>     if self.guild.owner_id == member.id:
> AttributeError: 'Bot' object has no attribute 'id'

The same goes for permissions_in.

## Intents

discord.Intents.all() and they are enabled on the settings page for the both
![image](https://user-images.githubusercontent.com/32837941/106480455-b8f23b80-64ab-11eb-86dd-d392f75d9efb.png)

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Linux 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020

**Comment by AbstractUmbra** [comment] 2021-02-01 15:41
This is reliant on the undocumented `Member._roles` SnowflakeList attribute for Members.

Consider using `Guild.me` instead of `Bot.user` for this.

**Comment by Zomatree** [comment] 2021-02-01 15:42
This is a duplicate of #2025

**Comment by nmarotte** [comment] 2021-02-01 15:48
> This is reliant on the undocumented `Member._roles` SnowflakeList attribute for Members.
> 
> Consider using `Guild.me` instead of `Bot.user` for this.

Thank you, this is what I needed

**Closed** 2021-02-01 22:59 UTC
Labels: duplicate, question

**Comment by ActuallyAdasi** [comment] 2022-06-04 23:08
Why is this closed as completed? How is this not a design flaw? Either remove the method, or fix it, or make it clear in the documentation that this is broken. I'd consider that a pretty serious bug.

I'm still blocked because I can't get permissions from a discord.User in a discord.TextChannel.

Here is some example code (surrounded by try catch)
```
            print("is author instance discord.User:", isinstance(author, discord.User))
            print("is channel instance discord.abc.GuildChannel:", isinstance(channel, discord.abc.GuildChannel))
            print(f"permissions in: {author.permissions_in(channel)}")
```

results in

```
is author instance discord.User: True
is channel instance discord.abc.GuildChannel: True
2022-06-04 19:05:05,788:ERROR:root: An exception occurred, unable to continue syncing: 'User' object has no attribute '_roles'
```

Even though this is a valid use case, as documented here: https://discordpy.readthedocs.io/en/stable/api.html?highlight=history#discord.User.permissions_in

What makes you comfortable closing this issue?

**Comment by Rapptz** [comment] 2022-06-05 00:26
That method was removed in v2
