### ISSUE TITLE
UnexpectedQuoteError raised from message with an apostrophe 

### ISSUE THREAD

**Issue by Alyx-W** [Rapptz/discord.py#7270] opened 2021-07-23 16:00 UTC
### Summary

UnexpectedQuoteError raised from some messages with an apostrophe

### Reproduction Steps

Run this `-qotd What’s a game you think doesnt get enough attention?` from the code below

### Minimal Reproducible Code

```python
@commands.command(name="qotd")
async def new_q(self, ctx, arg, *args):
  if arg != 'hp':
    arg2 = " ".join(args[:])
    args = f"{arg} {arg2}"
    item = {
                "question": f"{args}",
                "priority": 1
            }
    await ctx.send(f"`{args}` has been added to the pool")
```

### Expected Results

It to work like it has been for over a month.

### Actual Results

It raised this error message:
```
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 789, in prepare
    await self._parse_arguments(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 697, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 549, in transform
    argument = view.get_quoted_word()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/view.py", line 174, in get_quoted_word
    raise UnexpectedQuoteError(current)
discord.ext.commands.errors.UnexpectedQuoteError: Unexpected quote mark, '’', in non-quoted string
```

### Intents

All

### System Information

- Python v3.8.10-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Linux 5.8.0-1038-gcp #40~20.04.1-Ubuntu SMP Thu Jul 15 11:55:03 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

My best guess for what's going on is that it has to do with arguments picked up by the commands extension?

**Comment by scrazzz** [comment] 2021-07-23 16:15
Duplicate of #6296

**Closed** 2021-07-31 18:06 UTC
Labels: unconfirmed bug
