### ISSUE TITLE
Invalid syntax in library code?

### ISSUE THREAD

**Issue by magicgoose** [Rapptz/discord.py#1421] opened 2018-07-15 10:17 UTC
```
  File "/usr/local/lib/python3.7/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
```

**Comment by EvieePy** [comment] 2018-07-15 10:19
Python 3.7 is not supported. You will need to downgrade to 3.6.

**Comment by ItWasAllIntended** [comment] 2018-07-15 10:31
Not really. The async branch of the library does not get updates anymore. This is fixed in the rewrite version and in the async repo but has not been pushed to pip

**Comment by Harmon758** [comment] 2018-07-16 02:19
This is a duplicate of #1249

**Closed** 2018-08-20 01:28 UTC
Labels: duplicate
