### ISSUE TITLE
Add a GuildConverter

### ISSUE THREAD

**Issue by sebkuip** [Rapptz/discord.py#6016] opened 2020-11-06 14:20 UTC
## The Problem

Add a commands.GuildConverter, to convert to guilds using typehinting

## The Ideal Solution

Just like other converters, go down a list, like first try get_guild(id), then fetch_guild(id) etc.

## The Current Solution

Using extra lines like guild = bot.get_guild(id)

## Summary

Add a GuildConverter that works like other guilds.

**Comment by Vexs** [comment] 2020-11-06 19:17
Duplicate of #5186

**Comment by mudkipdev** [comment] 2020-12-29 00:36
#5186 #1629 and #574 are already closed, i don't see much point in this anyway

**Comment by Rapptz** [comment] 2021-02-18 05:56
Fixed by #6365

**Closed by Rapptz** 2021-02-18 05:56 UTC
Labels: feature request
