### ISSUE TITLE
Lost audio can't not play 

### ISSUE THREAD

**Issue by duongtuan303030** [Rapptz/discord.py#7531] opened 2022-03-06 09:28 UTC
### Summary

not play audio

### Reproduction Steps

-re update 2.0.0a at 06/3/2022
-test music 
- bot join no error log but no audio

### Minimal Reproducible Code

```python
#code test for audio
#am use eval command
from discord import FFmpegPCMAudio
a = await ctx.author.voice.channel.connect()
source = FFmpegPCMAudio("https://radio.garden/api/ara/content/listen/P7TysNHJ/channel.mp3?1646558234850")
ctx.voice_client.play(source)
```

### Expected Results

bot join and play audio

### Actual Results

nothing bot just join and has no audio

### Intents

all

### System Information

- Python v3.10.1-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3733+g07a1311
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

![image](https://user-images.githubusercontent.com/80153297/156917201-9ae27cb0-26b8-42d7-9977-bf1cdee65c6c.png)

**Comment by qtds35k** [comment] 2022-03-06 09:39
I might +1 on this tho I'm not 100% sure -- are you hosting your app on heroku and using buildpack `https://github.com/xrisk/heroku-opus.git` as well?
My voice bot also started failing after a minimal deployment, and below is the only significant difference:
```
Successfully uninstalled discord.py-2.0.0a3738+g8360e4a
Successfully installed discord.py-2.0.0a3740+g9d3fa3d
```

If I host the app on my local machine, it works fine tho.
I'm wondering if there's a way to specify the build version in `requirement.txt` as a temporary fix?

**Comment by qtds35k** [comment] 2022-03-06 10:05
Quick update: although I still cannot root cause the issue, I'm able to fix the functionality by specifying an Aug 27, 2021 commit of `discord.py` in `requirement.txt` as below:
```
git+https://github.com/Rapptz/discord.py@45d498c1b76deaf3b394d17ccf56112fa691d160#egg=discord.py
```

**Comment by duongtuan303030** [comment] 2022-03-06 10:05
> I might +1 on this tho I'm not 100% sure -- are you hosting your app on heroku and using buildpack `https://github.com/xrisk/heroku-opus.git` as well? My voice bot also started failing after a minimal deployment, and below is the only significant difference:
> 
> ```
> Successfully uninstalled discord.py-2.0.0a3738+g8360e4a
> Successfully installed discord.py-2.0.0a3740+g9d3fa3d
> ```
> 
> If I host the app on my local machine, it works fine tho. I'm wondering if there's a way to specify the build version in `requirement.txt` as a temporary fix?

am host on my pc

**Comment by qtds35k** [comment] 2022-03-06 10:06
Got it. The we might not be having the same issue.
Good luck!

**Comment by duongtuan303030** [comment] 2022-03-06 10:08
> git+https://github.com/Rapptz/discord.py@45d498c1b76deaf3b394d17ccf56112fa691d160#egg=discord.py

thank

**Comment by duongtuan303030** [comment] 2022-03-06 10:11
> Quick update: although I still cannot root cause the issue, I'm able to fix the functionality by specifying an Aug 27, 2021 commit of `discord.py` in `requirement.txt` as below:
> 
> ```
> git+https://github.com/Rapptz/discord.py@45d498c1b76deaf3b394d17ccf56112fa691d160#egg=discord.py
> ```

it work

**Comment by qtds35k** [comment] 2022-03-06 10:11
Awesome!

**Comment by duongtuan303030** [comment] 2022-03-06 10:11
![image](https://user-images.githubusercontent.com/80153297/156918657-1e04e9c4-be07-4c6c-a687-b78fe4f0e805.png)

**Comment by DivyanshuLohani** [comment] 2022-03-06 17:32
Yeah this is the bug I am also facing it surely is a bug

**Comment by Rapptz** [comment] 2022-03-08 06:19
This should be fixed in the latest commit.

**Closed** 2022-03-08 06:18 UTC
Labels: bug
