### ISSUE TITLE
Can't remove role from member if add_roles is called after remove_roles

### ISSUE THREAD

**Issue by abluescarab** [Rapptz/discord.py#903] opened 2017-11-15 07:28 UTC
I'm using v0.16.12, installed in Python 3.5 with pip. Based on my testing, it looks like I have the same problem as issue #56. If I call `bot.remove_roles` followed by `bot.add_roles`, the old roles are not removed before adding the new ones. I've had to use the same workaround of looping through the roles manually. It works correctly if I remove the `add_roles` call.

**Comment by Rapptz** [comment] 2017-11-15 07:33
Duplicate of #56

**Comment by Rapptz** [comment] 2017-11-15 07:34
The way to fix this is to use replace_roles or switch to rewrite.

**Closed** 2017-11-15 07:35 UTC
