### ISSUE TITLE
Edit Channel Name causes a Delay

### ISSUE THREAD

**Issue by Brianbloke** [Rapptz/discord.py#5230] opened 2020-08-16 10:46 UTC
### Summary

I have a bot in which it ticks down a timer on the channel, and then deletes the channel when it hits 0. However, In my for loop
The edit channel seems to work for the first few times, and then just stops working at all after a longer period of time. There is no logic to this, but I think it may be hanging up under the channel.edit

### Reproduction Steps

Create a For Loop that runs of a Timer and already has a name.
```
 # for each minute, edit the channel name and sleep for 60 seconds
            #Time_LeftOn is total Time in Minutes
            for i in range(0, int(time_leftOn)):
                print("in timer")
                await channel.edit(name=name + '-' + str(int(finaltime)))
                print(finaltime)
                finaltime = int(finaltime) - 1
                print(str(finaltime) + " sleep start " + str(datetime.datetime.now().time()))
                await asyncio.sleep(60)
                print(str(finaltime) + " sleep end " + str(datetime.datetime.now().time()))
            # after loop has ran, delete channel
            await channel.delete()
            return
```

### Expected Results

For the loop to start, edit the name, sleep for 60 seconds, then go back in.
I know it is hanging on the channel.edit as I'm printing to the console.

### Actual Results

from the console-
```
in timer
59.2
58 sleep start 10:20:27.139295
58 sleep end 10:21:27.152255
in timer
58
57 sleep start 10:21:27.307034
57 sleep end 10:22:27.312993
in timer
57
56 sleep start 10:30:27.316321
56 sleep end 10:31:27.325464
in timer
56
55 sleep start 10:31:27.549100
55 sleep end 10:32:27.558203
in timer
```
As you can see there is almost a 10minute delay between the 60 seconds that has passed. The delay occurs after 'in timer', but before 'finaltime' gets printed hence my conclusion.

### Checklist

- [X ] I have searched the open issues for duplicates.
- [X ] I have shown the entire traceback, if possible.
- [X ] I have removed my token from display, if visible.

### System Information

- Python v3.6.9-final
- discord.py v1.3.4-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020

**Comment by Rapptz** [comment] 2020-08-16 10:48
Duplicate of https://github.com/Rapptz/discord.py/issues/4155 and https://github.com/Rapptz/discord.py/issues/5173

Basically you're being rate limited, the library is handling it for you.

**Closed by Rapptz** 2020-08-16 10:48 UTC
