### ISSUE TITLE
Sending an image to a text channel occasionally produces an Error 104

### ISSUE THREAD

**Issue by Jacobvs** [Rapptz/discord.py#4026] opened 2020-04-22 22:24 UTC
### Summary

When attempting to send an image to a text channel, occasionally I'll get an Error 104 (Connection reset) and the image won't send. This issue seems to pop up randomly and will occur for a couple hours until it randomly decides to work again with no changes made in between.

### Reproduction Steps

Send any image to a text channel (i.e.):
```python
 await ctx.send(file=discord.File('files/oogabooga.png'))
```
Nothing appears in the text channel, and ~30 seconds later I get the traceback from the error 104.

### Expected Results

The image to post.

### Actual Results

Traceback:
```
WARNING:root:Ignoring exception in command realmclear:
WARNING:root:
Traceback (most recent call last):
  File "/home/jacobvs2/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/jacobvs2/Rotmg-Bot/cogs/raiding.py", line 255, in realmclear
    state.mapmsg = await hc_channel.send("Current Map:", file=discord.File(f"world-maps/world_{world_num}.png", "current_map.png"))
  File "/home/jacobvs2/.local/lib/python3.7/site-packages/discord/abc.py", line 839, in send
    content=content, tts=tts, embed=embed, nonce=nonce)
  File "/home/jacobvs2/.local/lib/python3.7/site-packages/discord/http.py", line 165, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/jacobvs2/.local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/jacobvs2/.local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/jacobvs2/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/jacobvs2/.local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.5-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.3.0-1017-gcp #18-Ubuntu SMP Tue Mar 31 06:27:43 UTC 2020

**Comment by Jacobvs** [comment] 2020-04-22 23:15
Additionally, here's a log file wherein the error occurs: https://drive.google.com/file/d/1Yj_2MZxvvf-vg9LkPXrgGB5WdIbk8Svw/view?usp=sharing
(It's a long log fyi)
the command message occurs at: `2020-04-22 16:04:55,573`
The error event occurs at: `2020-04-22 16:05:10,592`

**Comment by aticie** [comment] 2020-05-04 15:47
I'm having the same issue, have you found any solution? I thought it happened after having the bot idle for a long time and the session with discord expired. But I don't know how to retry connection or renew the session. 

Also, I believe it is not related to #4037 because it doesn't get ratelimited to 30/60 rule from my testing and the error code is different.

### **System Information**

Python v3.7.5
discord.py v1.3.3
aiohttp v3.6.2
websockets v8.1
system info: Linux 5.3.0-1018-gcp #19-Ubuntu SMP Thu Apr 9 07:44:51 UTC 2020

### **Traceback**
```Traceback (most recent call last):
  File "/home/t-bot/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 83,
 in wrapped
    ret = await coro(*args, **kwargs)
  File "toxic_bot.py", line 546, in recent
    await ctx.send(embed=embed, file=file)
  File "/home/t-bot/.local/lib/python3.7/site-packages/discord/abc.py", line 839, in send
    content=content, tts=tts, embed=embed, nonce=nonce)
  File "/home/t-bot/.local/lib/python3.7/site-packages/discord/http.py", line 165, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/t-bot/.local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aen
ter__
    self._resp = await self._coro
  File "/home/t-bot/.local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _reque
st
    await resp.start(conn)
  File "/home/t-bot/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in
 start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/t-bot/.local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/t-bot/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 892,
 in invoke
    await ctx.command.invoke(ctx)
  File "/home/t-bot/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 797
, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/t-bot/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 92,
 in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientOSError: [Errno 1
04] Connection reset by peer
```

**Comment by Rapptz** [comment] 2021-02-18 05:38
This is a duplicate of https://github.com/Rapptz/discord.py/issues/2596

Chances are however, that this is a temporary networking issue.

**Closed by Rapptz** 2021-02-18 05:38 UTC
