### ISSUE TITLE
JSONDecoding Error

### ISSUE THREAD

**Issue by rocky1928** [Rapptz/discord.py#2475] opened 2019-12-13 23:11 UTC
### Summary:
All bot requirements are met except for discord.py being version discord.py==1.0.0a1477+g184c430. I believe this is the cause of the problem. The bot loads yet has a few errors that appear and repeat.

### Traceback

Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "appuselfbot.py", line 319, in on_ready
    opt = json.load(fp)
  File "C:\Program Files\Python\Python368\lib\json\__init__.py", line 299, in lo
ad
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files\Python\Python368\lib\json\__init__.py", line 354, in lo
ads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python\Python368\lib\json\decoder.py", line 339, in dec
ode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python\Python368\lib\json\decoder.py", line 357, in raw
_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000000058DF9B4E0>
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 568, in run
    return task.result()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoj
i_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 568, in run
    return task.result()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoj
i_data['name'])
KeyError: 'animated'

<removed tags>
anonymous tracking of bot usage is enabled
'unclosed client session' and 'unclosed connector' are not errors

Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "appuselfbot.py", line 319, in on_ready
    opt = json.load(fp)
  File "C:\Program Files\Python\Python368\lib\json\__init__.py", line 299, in lo
ad
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files\Python\Python368\lib\json\__init__.py", line 354, in lo
ads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python\Python368\lib\json\decoder.py", line 339, in dec
ode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python\Python368\lib\json\decoder.py", line 357, in raw
_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Something went wrong: 'Bot' object has no attribute 'default_status'
Task exception was never retrieved
future: <Task finished coro=<Track.heartbeat() done, defined at C:\Program Files
\Python\Python36\Discord-Selfbot-master (1)\Discord-Selfbot-master\cogs\track.py
:35> exception=ClientConnectorError(10060, "Connect call failed ('115.69.164.101
', 8080)")>
Traceback (most recent call last):
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\aio
http\connector.py", line 822, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "C:\Program Files\Python\Python368\lib\asyncio\base_events.py", line 794,
 in create_connection
    raise exceptions[0]
  File "C:\Program Files\Python\Python368\lib\asyncio\base_events.py", line 781,
 in create_connection
    yield from self.sock_connect(sock, address)
  File "C:\Program Files\Python\Python368\lib\asyncio\selector_events.py", line
439, in sock_connect
    return (yield from fut)
  File "C:\Program Files\Python\Python368\lib\asyncio\selector_events.py", line
469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 10060] Connect call failed ('115.69.164.101', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python36\Discord-Selfbot-master (1)\Discord-Self
bot-master\cogs\track.py", line 39, in heartbeat
    async with self.bot.session.post(self.url + "/ping", data={"user_hash": hash
lib.sha256(str(self.bot.user.id).encode()).hexdigest()}) as resp:
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\aio
http\client.py", line 843, in __aenter__
    self._resp = await self._coro
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\aio
http\client.py", line 366, in _request
    timeout=timeout
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\aio
http\connector.py", line 445, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\aio
http\connector.py", line 757, in _create_connection
    req, traces, timeout)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\aio
http\connector.py", line 879, in _create_direct_connection
    raise last_exc
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\aio
http\connector.py", line 862, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\aio
http\connector.py", line 829, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 115.69.16
4.101:8080 ssl:None [Connect call failed ('115.69.164.101', 8080)]
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 568, in run
    return task.result()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoj
i_data['name'])
KeyError: 'animated'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000000014DBDB518>

<removed tags>
anonymous tracking of bot usage is enabled
'unclosed client session' and 'unclosed connector' are not errors

Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "appuselfbot.py", line 319, in on_ready
    opt = json.load(fp)
  File "C:\Program Files\Python\Python368\lib\json\__init__.py", line 299, in lo
ad
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files\Python\Python368\lib\json\__init__.py", line 354, in lo
ads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python\Python368\lib\json\decoder.py", line 339, in dec
ode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python\Python368\lib\json\decoder.py", line 357, in raw
_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000000EE431FC4E0>
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 568, in run
    return task.result()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\dis
cord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoj
i_data['name'])
KeyError: 'animated'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python\Python368\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\PeteDad-Admin\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 74, in run
    f = asyncio.run_coroutine_threadsafe(coro, loop=self.ws.loop)
  File "C:\Program Files\Python\Python368\lib\asyncio\tasks.py", line 725, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "C:\Program Files\Python\Python368\lib\asyncio\base_events.py", line 637, in call_soon_threadsafe
    self._check_closed()
  File "C:\Program Files\Python\Python368\lib\asyncio\base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

### Expected Results
I expected the bot to run normally with no issues as there were no errors setting up the bot.

### Actual Results
The bot connects yet does not respond to any commands and will continue to loop these errors until the final iteration of errors occurs.

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
discord.py v1.0.1a for Python 3.6.5

**Comment by zomatree** [comment] 2019-12-13 23:14
update discord.py, also selfbots are against discord ToS so its best not to use them

**Comment by rocky1928** [comment] 2019-12-13 23:15
I'll test it out. One second.

**Comment by zomatree** [comment] 2019-12-13 23:17
also this is a pinned issue #2422, so please try search for dups before making a issue

**Comment by Harmon758** [comment] 2019-12-13 23:19
Duplicate of the pinned issue, #2422.

As explained, self-bots on [user accounts](https://discordapp.com/developers/docs/topics/oauth2#bot-vs-user-accounts) [are forbidden now](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Closed** 2019-12-13 23:19 UTC
Labels: duplicate

**Comment by rocky1928** [comment] 2019-12-13 23:28
Zoma, every time I update and then run the .bat file to run the bot, this occurs.

Requirement already satisfied: idna>=2.0 in c:\program files\python\python368\li
b\site-packages (from idna-ssl>=1.0->aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a14
77+g184c430->-r requirements.txt (line 1)) (2.8)
ERROR: discord 1.0.1 has requirement discord.py>=1.0.1, but you'll have discord-
py 1.0.0a1477+g184c430 which is incompatible.
Installing collected packages: websockets, discord.py
  Found existing installation: websockets 6.0
    Uninstalling websockets-6.0:
      Successfully uninstalled websockets-6.0
  Found existing installation: discord.py 1.2.5
    Uninstalling discord.py-1.2.5:
      Successfully uninstalled discord.py-1.2.5
    Running setup.py install for discord.py ... done
Successfully installed discord.py-1.0.0a1477+g184c430 websockets-5.0.1

Which is why I asked how to fix this permanently since running run.bat resets discord.py back to an outdated version.

**Comment by gogurtenjoyer** [comment] 2019-12-13 23:35
This is a question you should ask the author of the code you are using. The library doesn't supply this .bat file.
