### ISSUE TITLE
Trying to get the all the members

### ISSUE THREAD

**Issue by Bryan-u-2** [Rapptz/discord.py#6047] opened 2020-11-16 17:44 UTC
## Summary

 I am trying to generate list of all members but its not working as intented 

## Reproduction Steps

 import discord
from discord.ext import commands

prefix = '.'
bot = commands.Bot(prefix)

@bot.event
async def on_ready():
    for member in bot.get_all_members():
        print(member)
        
bot.run("...") 

## Expected Results

 It should print out user names of all the members in a server 

## Actual Results

Nameofthebot#2342 
the name of the bot is repeated for the total number of the server

## Checklist

- [ ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [ ] I have provided the intents that my bot is using.

## System Information

- Python v3.6.9-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Linux 5.4.0-53-generic #59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020

**Comment by Gobot1234** [comment] 2020-11-16 17:49
Duplicate of #5867.

**Closed** 2020-11-16 17:59 UTC
Labels: bug
