### ISSUE TITLE
close_connection() got an unexpected keyword argument 'force'

### ISSUE THREAD

**Issue by davioitu** [Rapptz/discord.py#1366] opened 2018-06-21 16:29 UTC
I was trying to get the command out and I came across this error
`Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\davi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:/Users/davi/PycharmProjects/Discord/bot.py", line 55, in on_message
    await canaldevoz.disconnect()
  File "C:\Users\davi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\voice_client.py", line 297, in disconnect
    yield from self.ws.close()
  File "C:\Users\davi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 421, in close
    yield from asyncio.shield(self.close_connection_task)
  File "C:\Users\davi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\gateway.py", line 686, in close_connection
    yield from super().close_connection(force=force)
TypeError: close_connection() got an unexpected keyword argument 'force'
`

**Comment by Harmon758** [comment] 2018-06-21 16:37
This is a duplicate of #973.
Downgrade your websockets version to >=3.1,<4.0 to meet the dependency requirements for the library.
If you're using the rewrite branch, the websockets requirement has been updated to >=5.0,<6.0, so all you need to do is update.

**Closed** 2018-06-22 21:08 UTC
Labels: question
