### ISSUE TITLE
message.stickers always return empty list

### ISSUE THREAD

**Issue by Poloin34** [Rapptz/discord.py#7186] opened 2021-07-07 12:42 UTC
### Summary

as title, stickers not listed and no way to get them (even just if there's one)

### Reproduction Steps

Get a message object, check for stickers attribut, it return an empty list, even if there is a Sticker

### Minimal Reproducible Code

```python
@bot.event
async def on_message(message):
    print( message.stickers ) # []
```

### Expected Results

Returning list of stickers object. Or at least if there is some

### Actual Results

Returned empty list

### Intents

all()

### System Information

> py -m discord -v
- Python v3.9.5-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment] 2021-07-07 12:42
Duplicate of https://github.com/Rapptz/discord.py/issues/7140. It's literally a few below this one. Search before opening an issue.

**Closed by Rapptz** 2021-07-07 12:42 UTC
Labels: unconfirmed bug

**Comment by Poloin34** [comment] 2021-07-07 12:57
> Duplicate of #7140. It's literally a few below this one. Search before opening an issue.

>  It sends a minimal sticker item object

Then, how to access this object?
