### ISSUE TITLE
Basic bot from readme not working

### ISSUE THREAD

**Issue by MrSandyWilly** [Rapptz/discord.py#5991] opened 2020-10-31 14:23 UTC
Hi,

I'm trying to get discord.py working, yet having copied the test bot from readme.md, it throws a rather large error, like so:

![image](https://user-images.githubusercontent.com/62423608/97781616-971faa80-1b84-11eb-93f4-30666c5dd46f.png)
![image](https://user-images.githubusercontent.com/62423608/97781622-a30b6c80-1b84-11eb-8161-e7dcab8b9cd4.png)

Am I doing something wrong? Thanks :)

**Comment by numbermaniac** [comment] 2020-10-31 14:43
(As a side note, while you did block out your token in the first image, it appears in the error log of the second image, so you may want to reset that as soon as possible.)

**Comment by MrSandyWilly** [comment] 2020-10-31 14:50
> (As a side note, while you did block out your token in the first image, it appears in the error log of the second image, so you may want to reset that as soon as possible.)

Ha ha thanks
In the end its doing nothing as of now, I'll reset it when I actually make some progress

**Comment by SebbyLaw** [comment] 2020-10-31 20:47
Duplicate of #4159.

**Closed** 2020-11-01 10:21 UTC
