### ISSUE TITLE
bot startup error

### ISSUE THREAD

**Issue by ttatanepvp123** [Rapptz/discord.py#1728] opened 2018-11-16 04:34 UTC
hello i wanted to try the rewrite version
and when I started I had this error:
```
  File "main.py", line 1, in <module>
    import discord
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/discord/client.py", line 30, in <module>
    from .guild import Guild
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/discord/guild.py", line 39, in <module>
    from .channel import *
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/discord/channel.py", line 31, in <module>
    from .webhook import Webhook
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/discord/webhook.py", line 27, in <module>
    import aiohttp
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 17, in <module>
    from .client_proto import ResponseHandler
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/aiohttp/client_proto.py", line 6, in <module>
    from .http import HttpResponseParser, StreamWriter
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/aiohttp/http.py", line 8, in <module>
    from .http_parser import (HttpParser, HttpRequestParser, HttpResponseParser,
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .http_writer import HttpVersion, HttpVersion10
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/aiohttp/http_writer.py", line 304, in <module>
    class URL(yarl.URL):
  File "/home/ttatanepvp123/.local/lib/python3.6/site-packages/yarl/__init__.py", line 232, in __init_subclass__
    "is forbidden".format(cls))
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden
```

**Comment by MusicOnline** [comment] 2018-11-16 04:40
You probably installed the wrong package. (pip install discord or discord-rewrite)
The correct command is:
```
pip install -U git+https://github.com/Rapptz/discord.py@rewrite
```
or with voice send support:
```
pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
```

**Comment by MusicOnline** [comment] 2018-11-16 04:42
obligatory text excerpt:

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Harmon758** [comment] 2018-11-16 04:43
Duplicate of #1280.
This should be fixed in the latest version of the rewrite branch.

**Closed** 2018-11-16 06:59 UTC
