### ISSUE TITLE
Python 3.9.0: No module named 'discord'

### ISSUE THREAD

**Issue by texasoriginal** [Rapptz/discord.py#6151] opened 2020-12-11 06:51 UTC
## Summary

I am using Visual Studio Code to start a new discord.py bot but whenever I run it, ModuleNotFoundError: No module named 'discord' pops up. I have installed python 3.9.0 from python.org and I have looked everywhere for solutions but I can't find anything.

## Reproduction Steps

import discord in VS Code running Python 3.9.0

## Expected Results

I expected the code to work and run and the bot will come online.

## Actual Results

ModuleNotFoundError: No module named 'discord'
Traceback (most recent call last): File "/Users/myname/Desktop/CM-Public/main.py", line 1, in <module> import discord ModuleNotFoundError: No module named 'discord'

## Intents

I am using all intents!

## Checklist

- [X] I have searched the open issues for duplicates.  (There is one "duplicate" with the same issue on python v3.7.9 but this is a different version and even though that was solved, it didn't work for me. I have looked and found all issues and soverflow posts and none have solved my issue)
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have provided the intents that my bot is using.

## System Information

Python -m discord -v does not work so here is some of the information

Python Version: Python 3.9.0
Library Version: discord.py v1.5.1-final

**Comment by Rapptz** [comment] 2020-12-11 06:53
All these "module not found" errors are duplicate of each other. They basically amount to the package not being installed in the appropriate (virtual) environment for that Python version.

**Closed by Rapptz** 2020-12-11 06:53 UTC
Labels: bug
