### ISSUE TITLE
discord.py/ext/cooldowns.py - add overwrites for specific user ids

### ISSUE THREAD

**Issue by TheOneMusic** [Rapptz/discord.py#2308] opened 2019-08-12 07:41 UTC
So, my idea was to modify the cooldowns so that if a user is in a specific list of ids, the cooldown will be reduced or even disabled for that person. For example, let's create two tuples:
```python
donators = id_1, id_2
trusted = id_3, id_4
```
But now, if I add a command in this way:
```python
@client.command()
@commands.cooldown(1, 5, commands.BucketType.user)
async def my_command(ctx):
    pass
```
The cooldown is 5 seconds for everyone. Is it possible to make it to 3 if the context invoker's id is in the `donators` list and to disable it completely if the user is in the `trusted` list?

**Comment by Rapptz** [comment] 2021-02-18 05:10
This seems like a duplicate of #1999

**Closed by Rapptz** 2021-02-18 05:10 UTC
