### ISSUE TITLE
Typing Issues (Private Import Usage in Public Namespace)

### ISSUE THREAD

**Issue by ImplyingICheck** [Rapptz/discord.py#9607] opened 2023-10-12 03:22 UTC
### Summary

Types are not correctly re-exported from `discord.ext.commands.bot`.

### Reproduction Steps

Attempt to import any types specified in the `if TYPE_CHECKING:` block.

### Minimal Reproducible Code

```python
import typing

import discord

BotT: typing.TypeAlias = discord.ext.commands.bot.BotT
```

### Expected Results

Types used in the public namespace of a py.typed package should all be exported.

Attempting to provide type information for any subclass of a `discord.ext.commands.bot` class cannot correctly inherit type information.

### Actual Results

Types not re-exported.

### Intents

N/A

### System Information

- Python v3.11.6-final
- discord.py v2.3.2-final
- aiohttp v3.8.6
- system info: Linux 5.15.90.1-microsoft-standard-WSL2 \# 1 SMP Fri Jan 27 02:56:13 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

There is a consensus in the typing community that imported private symbols should be explicitly exported. For example,

`from discord.ext.commands._types import BotT as BotT`

While the `as ...` seems redundant, the lack of an export keyword/construction in Python requires it to maintain consistent namespace standards.

**Comment by Rapptz** [comment] 2023-10-12 03:37
This is a private type and a private module, so this is by design. Duplicate of https://github.com/Rapptz/discord.py/pull/7743

**Closed by Rapptz** 2023-10-12 03:37 UTC
Labels: as designed

**Comment by ImplyingICheck** [comment] 2023-10-12 10:06
Having read #7743, I now see the intention. Would there be a possibility of renaming `discord.ext` to `discord._ext` to reflect the directory of sub-packages being private?

This would prevent confusion and bring consistency with PEP 561, "all [py.typed packages'] sub-packages MUST support type checking...".
