### ISSUE TITLE
Importing discord fails

### ISSUE THREAD

**Issue by noahhaasis** [Rapptz/discord.py#1550] opened 2018-08-30 06:43 UTC
Importing discord on windows 10(32bit) using Python 3.7 fails with the following exception:
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32 Type "help", "copyright", "credits" or "license" for more information.
>>> import discord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\leinw\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\leinw\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\leinw\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\leinw\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
```

**Comment by Vexs** [comment] 2018-08-30 06:45
Dupe of #1401 and a couple others

**Comment by ItWasAllIntended** [comment] 2018-08-30 09:02
Please check other issues before making your own. It's also best to check on the [d.py server](https://discord.gg/r3sSKJJ) before making one

**Closed** 2018-09-02 23:50 UTC
Labels: duplicate
