### ISSUE TITLE
Add "package" kwarg to load_extension.

### ISSUE THREAD

**Issue by uKaigo** [Rapptz/discord.py#6455] opened 2021-02-22 03:48 UTC
**Summary**

Add a package kwarg to [re]load_extension to allow relative imports.

**What is the feature request for?**

discord.ext.commands

**The Problem**

In the current implementation, you can't use relative names in extensions. Such as `.cogs.meta`.

If you try, you'll get this traceback:
```py
Traceback (most recent call last):
  File "/home/kaigo/Área de Trabalho/Projetos/KaiBOT/kaibot/bot.py", line 74, in load_all_extensions
    self.load_extension(extension)
  File "/home/kaigo/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 659, in load_extension
    spec = importlib.util.find_spec(name)
  File "/usr/lib/python3.8/importlib/util.py", line 90, in find_spec
    fullname = resolve_name(name, package) if name.startswith('.') else name
  File "/usr/lib/python3.8/importlib/util.py", line 32, in resolve_name
    raise ValueError(f'no package specified for {repr(name)} '
ValueError: no package specified for '.cogs.meta' (required for relative module names)
```

This is a problem if your bot is module-based.
The workaround is to manually add the package name to the extension name (`kaibot.cogs.meta`), but the problem is you always have to type the package name.

**The Ideal Solution**

```py
bot.load_extension('.cogs.meta', package=__package__)
...
bot.reload_extension('.cogs.meta', package=__package__)
```

**The Current Solution**

```py
bot.load_extension(f'{__package__}.cogs.meta')
...
bot.reload_extension(f'{__package__}.cogs.meta')
```

**Comment by SebbyLaw** [comment] 2021-02-22 03:51
Duplicate of #2465

**Closed** 2021-02-22 03:51 UTC
Labels: feature request
