### ISSUE TITLE
How can I fix this bug! I can't fix it

### ISSUE THREAD

**Issue by turandot1996** [Rapptz/discord.py#2424] opened 2019-11-19 02:35 UTC
### Summary

the bot shut down without any reaction!

### Reproduction Steps

My bot had already worked for a month . but it shut down this night. But  I don't know how to fix it! track back logs has pasted after this. Please help me . It's an urgent problem

### Expected Results

The bot can perfectly run.

### Actual Results

 File "bot1.py", line 280, in <module>
    bot.run('xxx')
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 598, in run
    return future.result()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 457, in connect
    await self._connect()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 421, in _connect
    await self.ws.poll_event()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/gateway.py", line 423, in received_message
    func(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/state.py", line 407, in parse_message_reaction_add
    emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.6.8-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.15.0-1054-aws #56-Ubuntu SMP Thu Nov 7 16:15:59 UTC 2019

**Comment by EndenDragon** [comment] 2019-11-19 02:36
Duplicate of #2422 
Please update your discord.py library to the lastest.

**Closed** 2019-11-19 02:37 UTC

**Comment by Harmon758** [comment] 2019-11-19 06:56
This should now be fixed with v1.2.5.
In the future, please make sure you're using the latest development version when reporting issues.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
