### ISSUE TITLE
How to listen voice channel audio???

### ISSUE THREAD

**Issue by Duerocraft** [Rapptz/discord.py#2598] opened 2020-03-14 02:55 UTC
hey i'm confused how to record audio via discord.py?? by reading the docu i found it'm possible but i don't understand how? if anyone know pls show me some examples

**Comment by Vexs** [comment] 2020-03-14 02:56
Discord.py does not support audio receive. There is a fork that does, but it's not really ready.

**Comment by Harmon758** [comment] 2020-03-18 22:18
Duplicate of #444 
Also see #1094

**Closed** 2020-03-18 22:18 UTC
Labels: duplicate, question
