### ISSUE TITLE
Cannot connect to host discordapp.com:443

### ISSUE THREAD

**Issue by Giancrafter** [Rapptz/discord.py#5119] opened 2020-07-11 19:33 UTC
### Summary

Discord Bot doesn't want to start

### Reproduction Steps

Ran the basic bot example with my key but got an SSL error

### Expected Results

The Bot does start

### Actual Results
It crashed on start and gave me the error below:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.6/asyncio/base_events.py", line 820, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 846, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 66, in <module>
    client.run('MY TOKEN')
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 640, in run
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 584, in start
    await self.login(*args, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 442, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 261, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 165, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 941, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host discordapp.com:443 ssl:default [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)]
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.6.9-final
- discord.py v1.3.4-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018

**Comment by Rapptz** [comment] 2020-07-11 23:40
Duplicate of #4146

**Closed by Rapptz** 2020-07-11 23:40 UTC

**Comment by Giancrafter** [comment] 2020-07-12 06:36
Its not a duplicate, I am on ubuntu 18.04  and not on linux

**Comment by numbermaniac** [comment] 2020-07-12 06:39
Ubuntu *is* a Linux operating system. You can see it mentioned in your original report:

`system info: Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018`

**Comment by Giancrafter** [comment] 2020-07-12 06:48
Guys chill down. I meant Windows NOT Linux, i messed something up. So i guess there wasnt an expired root certificate on linux so why do I still getthe error?
Sorry for disturbing you by creating new issues instead of commenting hetr

**Comment by numbermaniac** [comment] 2020-07-12 07:29
Perhaps try installing certifi using `pip install certifi`, and then try running the bot again. I don't know if it'll work for certain but I believe it has fixed the issue for some people.

**Comment by Giancrafter** [comment] 2020-07-12 07:45
Already tried, didnt work

**Comment by gogurtenjoyer** [comment] 2020-07-12 08:02
When is the last time you've updated your packages in Ubuntu? You could always try `sudo update-ca-certificates
` to update the actual certificates used by the operating system, if it's been awhile.

**Comment by Giancrafter** [comment] 2020-07-12 08:04
The vps i am running on is freshly installed. I could also run the bot fine a day ago. After entering `sudo update-ca-certificates` still nothing has changed...

**Comment by gogurtenjoyer** [comment] 2020-07-12 08:07
It may be freshly-installed, but that's a somewhat old distribution of Ubuntu, so it wouldn't hurt to update.

**Comment by Giancrafter** [comment] 2020-07-12 10:09
I‘ll try
