### ISSUE TITLE
Attribute error for unavailable guild

### ISSUE THREAD

**Issue by CHamburr** [Rapptz/discord.py#5115] opened 2020-07-10 06:35 UTC
### Summary

An attribute error is returned for `member_count` property on an unavailable guild.

Traceback:
```
  File "/home/chamburr/modmail/utils/eval.py", line 24, in evaluate
    ret = await func()
  File "<string>", line 4, in func
  File "/home/chamburr/.local/lib/python3.8/site-packages/discord/guild.py", line 680, in member_count
    return self._member_count
AttributeError: _member_count
```

### Checklist

- [ x ] I have searched the open issues for duplicates.
- [ x ] I have shown the entire traceback, if possible.
- [ x ] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.3.4-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.4.0-33-generic

**Comment by apple502j** [comment] 2020-07-10 06:38
Duplicate of #4008

**Closed** 2020-07-10 06:44 UTC
