### ISSUE TITLE
is it possible to perform unit tests on the commands using pytest?

### ISSUE THREAD

**Issue by modernNeo** [Rapptz/discord.py#1604] opened 2018-09-21 22:47 UTC

**Comment by imayhaveborkedit** [comment] 2019-03-01 04:08
More or less a dupe of #197.  Basically there's two ways to do this.  Either capture and replay gateway events to simulate a connection to discord, or separate your logic from your command structure and test it on its own.

**Closed by imayhaveborkedit** 2019-03-01 04:08 UTC

**Comment by SilentHacks** [comment] 2026-06-15 16:17
For anyone in the future, I made [SimCord](https://github.com/SilentHacks/simcord) which lets you simulate a Discord connection and mock commands, button interactions etc.
