### ISSUE TITLE
Message content is always empty when bot=False

### ISSUE THREAD

**Issue by BlueCannonBall** [Rapptz/discord.py#6925] opened 2021-05-18 19:21 UTC
### Summary

message.content always returns an empty string when using self bots, unless the message was sent from the bot.

### Reproduction Steps

1. Copy the quickstart example from the docs
2. Adapt it to self bots
3. Make it print all messages
4. Observer that nothing is printed

### Minimal Reproducible Code

```python
import discord

client = discord.Client()

@client.event
async def on_message(message):
    print(message.content)

client.run("insert token here", bot=False)
```

### Expected Results

I expected to see messages printed out as they came.

### Actual Results

For every message that wasn't sent by the bot, a newline was printed, since message.content is empty.

### Intents

None

### System Information

- Python v3.8.5-final
- discord.py v1.7.2-final
- aiohttp v3.6.2
- system info: Linux 5.11.0-21.2-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.11-36ubuntu1~focal (2021-05-17)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Zomatree** [comment] 2021-05-18 19:24
Duplicate of #6820.

**Closed** 2021-05-18 19:34 UTC
Labels: unconfirmed bug
