### ISSUE TITLE
'utf-8' codec can't decode byte 0xf3 in position 11: invalid continuation byte

### ISSUE THREAD

**Issue by Malvert223** [Rapptz/discord.py#1095] opened 2018-02-20 15:00 UTC
When i try tu update dependencies the console send me that message:

Found existing installation: aiohttp 3.0.1
    Uninstalling aiohttp-3.0.1:
      Successfully uninstalled aiohttp-3.0.1
  Running setup.py install for aiohttp ... error
  Rolling back uninstall of aiohttp
Exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 11: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 11: invalid continuation byte

I use visual studio 2017 with compatibility with python 3.6 and i have instaled the python 3.6 

What can i do?

**Comment by Harmon758** [comment] 2018-02-20 15:20
This is a duplicate of https://github.com/Rapptz/discord.py/issues/1075 and is an [issue with pip 9](https://github.com/pypa/pip/issues/4110), not discord.py.

**Closed** 2018-02-20 20:37 UTC
Labels: off-topic
