### ISSUE TITLE
Slash commands example

### ISSUE THREAD

**Issue by itzsimpleboii8282** [Rapptz/discord.py#7349] opened 2021-08-08 15:24 UTC
### Summary

Of adding slash commands/interaction commad in examples like views.

### What is the feature request for?

The core library

### The Problem

Currently the examples directory(as in master for v2.0) only has examples for the views buttons/select. The slash commands/interaction commands are still missing in that.

### The Ideal Solution

Add examples related to slash commands.

**Comment by XuaTheGrate** [comment] 2021-08-08 15:34
As of right now, slash commands are not implemented into discord.py. They will be in the future, but until then examples are unnecessary.

**Comment by itzsimpleboii8282** [comment] 2021-08-08 16:02
> As of right now, slash commands are not implemented into discord.py. They will be in the future, but until then examples are unnecessary.

It is to come in v2.0.

**Comment by mesub7** [comment] 2021-08-08 16:07
There's no guarantee that it'll be ready for V2.0.

**Comment by bartick** [comment] 2021-08-08 16:48
> There's no guarantee that it'll be ready for V2.0.

According to this card there is a guarantee 
https://github.com/Rapptz/discord.py/projects/3#card-58631961

But there isn't a guarantee when it will come (I mean time)

**Comment by itzsimpleboii8282** [comment] 2021-08-08 16:55
> There's no guarantee that it'll be ready for V2.0.

It is in one of the pins of official discord server.

Reference: 

https://discord.com/channels/336642139381301249/336642776609456130/824484026877214740

**Comment by XuaTheGrate** [comment] 2021-08-08 17:04
There has been a lot of debate since that pin on whether they will be supported or not. There is no guarantee it will be in 2.0.

**Comment by N-i-c-k-007** [comment] 2021-08-08 18:56
> There has been a lot of debate since that pin on whether they will be supported or not. There is no guarantee it will be in 2.0.

Are you indirectly saying that we should drop out our hopes to get slash commands in 2.0 and should start looking into any 3rd party libs to get that thing happened? Since discord is going to depreciate the message content from `April 22`.... Yeah i know it's a while from now but development and testing takes time too...ain't?

**Comment by lgaan** [comment] 2021-08-08 18:58
> > There has been a lot of debate since that pin on whether they will be supported or not. There is no guarantee it will be in 2.0.
> 
> Are you indirectly saying that we should drop out our hopes to get slash commands in 2.0 and should start looking into any 3rd party libs to get that thing happened? Since discord is going to depreciate the message content from `April 22`.... Yeah i know it's a while from now but development and testing takes time too...ain't?

It means we don’t know. They might be in there, they might not. Note that v2.0 still has no ETA. It could come out in one month, with slash commands implemented in another version (ie v2.1)

**Comment by N-i-c-k-007** [comment] 2021-08-08 19:01
> > > There has been a lot of debate since that pin on whether they will be supported or not. There is no guarantee it will be in 2.0.
> > 
> > 
> > Are you indirectly saying that we should drop out our hopes to get slash commands in 2.0 and should start looking into any 3rd party libs to get that thing happened? Since discord is going to depreciate the message content from `April 22`.... Yeah i know it's a while from now but development and testing takes time too...ain't?
> 
> It means we don’t know. They might be in there, they might not. Note that v2.0 still has no ETA. It could come out in one month, with slash commands implemented in another version (ie v2.1)

Uh oh got it! Since it's on 2.0 To-Do list i hope many users of d.py is hopping to get that in 2.0, Hopes get more increment when d.js have already implemented and launched it in v13. Danny said that he will make any announcement soon about some stuffs, hoping to get that soon too, to at least have a clear figure to plan out how to proceed.

**Comment by Rapptz** [comment] 2021-08-09 00:29
Duplicate of #6149

**Closed by Rapptz** 2021-08-09 00:29 UTC
Labels: feature request
