### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Leviaph** [Rapptz/discord.py#1393] opened 2018-07-04 07:11 UTC
C:\Users\Sydney\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master>py -3 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 2, in <module>
    from pokeball import PokeBall
  File "C:\Users\Sydney\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master\pokeball.py", line 2, in <module>
    import discord
  File "C:\Users\Sydney\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Sydney\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\Sydney\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\Sydney\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

C:\Users\Sydney\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master>timeout -1

Press any key to continue ...

**Comment by flamekong** [comment] 2018-07-04 07:13
The 0.16 branch of the lib doesn't support python3.7. Downgrade to 3.6.

**Comment by Harmon758** [comment] 2018-07-04 07:15
This is a duplicate of #1249.

**Comment by Leviaph** [comment] 2018-07-04 07:35
thank you guys! i didn't realize that, its all launched, but may i ask how to out this into a server?

**Comment by Harmon758** [comment] 2018-07-04 07:44
I'm not exactly sure what you're asking, but for further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Closed by Harmon758** 2018-07-04 07:44 UTC
