### ISSUE TITLE
Sending a message to a channel with await channel.send(message) does not work

### ISSUE THREAD

**Issue by asarra** [Rapptz/discord.py#6175] opened 2020-12-18 15:33 UTC
## Reproduction Steps

    message = "somerandomstring"    
    for x in text_channel_list:
            try:
                channel = bot.get_channel(x)  # gives me the name of the channel
                print(channel)
                await channel.send(message)  # bot for some reason this does not work
            except Exception as e:
                failed_channels.append(str(x))
                print(e)

## Expected Results

I expected it to send a message to a list of channels

## Actual Results

C:\languages\lib\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\languages\lib\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\languages\lib\site-packages\aiohttp\locks.py:21: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._event = asyncio.Event(loop=loop)

## Intents

I'm not using any intents.

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [ ] I have provided the intents that my bot is using.

## System Information

- Python v3.9.1-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

**Comment by SebbyLaw** [comment] 2020-12-18 23:58
Duplicate of #5867 

This is not a bug with the library. Please see the recently added [intents documentation](https://discordpy.readthedocs.io/en/latest/intents.html) and [v1.5 changelog](https://discordpy.readthedocs.io/en/latest/whats_new.html#v1-5-0).

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Rapptz** [comment] 2020-12-19 01:42
This issue doesn't have enough information to be actionable. Not using intents also means the `get_channel` call would fail.

**Closed by Rapptz** 2020-12-19 01:42 UTC
Labels: bug

**Comment by asarra** [comment] 2020-12-23 13:40
Thanks, using Intents fixed the issue.
