### ISSUE TITLE
Len of commands.Bot.guilds returning 0

### ISSUE THREAD

**Issue by Lost1419** [Rapptz/discord.py#5955] opened 2020-10-21 05:08 UTC
## Summary

When I do get the guilds the bot is in it returns 0 The bot is in 4 server and it seems like even when I try and get them in multiple ways such as using `guilds = [guild.id for guild in cient.guilds]` it still will return 0 or an empty list

## Reproduction Steps

`
guilds = client.guilds
print(len(guilds))
`

## Expected Results

It should print 4 or the list of guild the bot is in.

## Actual Results

Returns 0 when using `len` and an empty list when just using `print(guilds)`

## Intents

`
intents = discord.Intents.default()
`
`
intents.members = True
`
`
intents.presences = True
`

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.6-candidate
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

**Comment by SebbyLaw** [comment] 2020-10-21 05:12
Can't reproduce on v1.5.0, Probably a Duplicate of #5867 

Your library version is wrong as well. `v15` does not exist.

For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Lost1419** [comment] 2020-10-21 05:42
> Can't reproduce on v1.5.0, Probably a Duplicate of #5867
> 
> Your library version is wrong as well. `v15` does not exist.
> 
> For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

I have joined the discord there the ones who told me to add the issue. I will join the Discord API server, thanks for looking at it

**Comment by Vexs** [comment] 2020-10-21 05:45
It *sounds* like this is an intents issue but it could be one of any other- it's unlikely to be an issue with discord.py itself. The discord-api guild has the same people as the discord.py guild, and it would probably be easiest to link the messages where you were told to go here to further sort this.

**Comment by Rapptz** [comment] 2020-10-21 05:55
If this is outside of the `on_ready` event then the bot has not connected to Discord to give you this data.

**Closed** 2020-10-21 06:01 UTC
Labels: bug
