### ISSUE TITLE
Rich Presence

### ISSUE THREAD

**Issue by webmsgr** [Rapptz/discord.py#951] opened 2017-12-13 22:19 UTC
Is this currently supported?

**Comment by NCPlayz** [comment] 2017-12-13 22:20
No

**Comment by NCPlayz** [comment] 2017-12-13 22:21
There have been unconfirmed rumors that it will be a feature in the near-future

**Comment by DismissedGuy** [comment] 2017-12-27 12:32
I'd personally rather have a nice wrapper than it being built in into d.py, but oh well

**Comment by tilda** [comment] 2017-12-27 16:51
Wouldn't work, RP is on client side RPC

**Comment by MinnDevelopment** [comment] 2017-12-27 17:01
Bots can receive RPC but not set it. It is not client-side.

**Comment by Rapptz** [comment] 2018-02-18 17:07
Dupe of #890

**Closed by Rapptz** 2018-02-18 17:07 UTC
