### ISSUE TITLE
Cant run bot

### ISSUE THREAD

**Issue by ragor11** [Rapptz/discord.py#5144] opened 2020-07-22 03:56 UTC
File "C:\Users\Administrator\Desktop\lifebot\discord\client.py", line 640, in run
    return future.result()
  File "C:\Users\Administrator\Desktop\lifebot\discord\client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\lifebot\discord\client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Administrator\Desktop\lifebot\discord\client.py", line 499, in connect
    await self._connect()
  File "C:\Users\Administrator\Desktop\lifebot\discord\client.py", line 463, in _connect
    await self.ws.poll_event()
  File "C:\Users\Administrator\Desktop\lifebot\discord\gateway.py", line 471, in poll_event
    await self.received_message(msg)
  File "C:\Users\Administrator\Desktop\lifebot\discord\gateway.py", line 425, in received_message
    func(data)
  File "C:\Users\Administrator\Desktop\lifebot\discord\state.py", line 720, in parse_guild_create
    guild = self._get_create_guild(data)
  File "C:\Users\Administrator\Desktop\lifebot\discord\state.py", line 695, in _get_create_guild
    guild._from_data(data)
  File "C:\Users\Administrator\Desktop\lifebot\discord\guild.py", line 288, in _from_data
    self._sync(guild)
  File "C:\Users\Administrator\Desktop\lifebot\discord\guild.py", line 317, in _sync
    self._add_channel(VoiceChannel(guild=self, data=c, state=self._state))
  File "C:\Users\Administrator\Desktop\lifebot\discord\channel.py", line 550, in __init__
    self._update(guild, data)
  File "C:\Users\Administrator\Desktop\lifebot\discord\channel.py", line 581, in _update
    self._fill_overwrites(data)
  File "C:\Users\Administrator\Desktop\lifebot\discord\abc.py", line 296, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'

**Comment by Rapptz** [comment] 2020-07-22 03:57
Duplicate of #5109.

Update your library before opening an issue next time please.

**Closed by Rapptz** 2020-07-22 03:57 UTC
