### ISSUE TITLE
How do I change the "Playing" status?

### ISSUE THREAD

**Issue by NeviraOwner** [Rapptz/discord.py#1749] opened 2018-12-02 12:33 UTC
I've tried this code out, and it doesn't change the status from "Playing" to "Watching".
`await bot.change_presence(activity=discord.activity(type=discord.ActivityType.watching, name='some commands'))`
It gives me an `AttributeError` saying that `module 'discord' has no attribute 'activity'`, so how do I change the "playing" status?

**Comment by ItWasAllIntended** [comment] 2018-12-02 12:34
This is not an issue with Discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by ItWasAllIntended** [comment] 2018-12-02 12:35
As for your issue, you need to watch your casing. The docs will show you the correct way.

**Comment by sghosh1810** [comment] 2018-12-02 14:03
`await bot.change_presence(game=discord.Game(name='some game'))`

**Comment by crrapi** [comment] 2018-12-02 14:11
@sghosh1810 That doesn't really answer the question, as the type for Game will always be `ActivityType.playing`. The `Activity` class is preferred here.

**Comment by NeviraOwner** [comment] 2018-12-04 20:04
@sghosh1810 I already know how to change the status from '**Playing** some game' into '**Playing** another game', I just need to know how to change the 'Playing' part.

**Comment by Harmon758** [comment] 2018-12-04 20:08
As has been explained, you need to use [`Activity`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Activity).

**Comment by NeviraOwner** [comment] 2018-12-04 20:09
@Harmon758 Can you provide an example of how to use it?

**Comment by NeviraOwner** [comment] 2018-12-04 20:10
@ItWasAllIntended Then what is this an issue of if it's not about discord.py?

**Comment by Phxntxm** [comment] 2018-12-04 20:11
Issues like this are for *issues with the library* not *issues with not understanding how to use the library*; this is the difference. Questions like this really should be directed to the discord server as mentioned before.

**Comment by Harmon758** [comment] 2018-12-04 20:19
The line of code you provided should be fine, except that you're using a nonexistent `discord.activity` instead of [`discord.Activity`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Activity). As has been explained, your issue is simply the casing.

**Comment by NeviraOwner** [comment] 2018-12-04 20:24
@Harmon758 Now I'm getting an error that says `module 'discord' has no attribute 'Activity'`

**Comment by NeviraOwner** [comment] 2018-12-04 20:35
@ItWasAllIntended, the solution you provided me only taught me to change what game my bot is playing, not the **Playing** part. And yes, I read the documentation and only provided me that.

**Comment by Harmon758** [comment] 2018-12-04 20:36
Are you on the async branch?
Because  [`Activity`](https://discordpy.readthedocs.io/en/rewrite/api.html#activity) (and  [`discord.ActivityType`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.ActivityType)) are only on the rewrite branch.
For the async branch, you'll have to manually set [`discord.Game.type`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Game.type).
For those values, see:
https://github.com/Rapptz/discord.py/blob/66e5033785259400d340b8c00eaa8ad60fbbb82a/discord/enums.py#L227-L232

Also, I noticed that you've already seen and reacted to [a comment](https://github.com/Rapptz/discord.py/issues/1606#issuecomment-423747890), in an issue this is a duplicate of, where I explained this already. In the future, please refrain from making duplicate issues, especially with questions that have already been answered.
For further help, you should really join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api).

**Closed** 2018-12-17 06:49 UTC
