### ISSUE TITLE
WebSocket connection is closed: code = 1002, no reason.

### ISSUE THREAD

**Issue by 77Wertfuzzy77** [Rapptz/discord.py#550] opened 2017-04-29 20:19 UTC
```
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at /usr/local/lib/python3.5/dist-packages/discord/voice_client.py:269> exception=ConnectionClosed('WebSocket connection is closed: code = 1002, no reason.',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 635, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1002, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 276, in poll_voice_ws
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 638, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1002, no reason.
```
Every once in a while, when my bot is playing music, it will throw this error. I have no idea what's causing it, and the only way I get it to start again is by having him leave and re-join the voice channel.

**Comment by hedgehog1029** [comment] 2017-05-01 14:46
1xxx codes are standard codes defined by the WebSocket standard, which can be found [here.](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) 1002 indicates a protocol error, which may be caused by packet loss (lossy internet connection) or malformed packets sent by your websocket library.

**Comment by Rapptz** [comment] 2017-05-20 17:19
This is fixed in rewrite.

**Closed by Rapptz** 2017-05-20 17:19 UTC
Labels: enhancement
